nodeLinker: node-modules

npmAuthToken: "${NPM_TOKEN-ignore_for_gh_pages_action}"

# I was getting weird "Failed to save packument" 409 errors when publishing to yarnpkg.com
npmRegistryServer: "https://registry.npmjs.org/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
