import { Properties as Properties1 } from "csstype";

// This file is auto-generated by truss: https://github.com/homebound-team/truss.
// See your project's `truss-config.ts` to make configuration changes (fonts, increments, etc).
// Target: web (build-time plugin)

import { __invertTrussMediaQuery, trussProps, useRuntimeStyle as _useRuntimeStyle } from "@homebound/truss/runtime";

/** Given a type X, and the user's proposed type T, only allow keys in X and nothing else. */
export type Only<X, T> = X & Record<Exclude<keyof T, keyof X | "__kind">, never>;

type UnionToIntersection<U> = (U extends unknown ? (value: U) => void : never) extends (value: infer I) => void ? I
  : never;

/** Raw CSS properties from csstype, without any style-kind brand. */
type RawCssProperties = Properties1<string | 0, string>;

/**
 * CSS properties with an optional buildtime brand.
 *
 * `Properties` is the standard type for passing CSS style objects around.
 * It carries an optional `__kind` discriminator so that `RuntimeStyles`
 * (which has `__kind: "runtime"`) is rejected when assigned to a
 * `Properties` slot like the `css=` prop.
 */
export type Properties = RawCssProperties & { readonly __kind?: "buildtime" };

export type InlineStyle = Record<string, string | number | undefined>;

/** A marker token used with `when`/`markerOf` etc. */
export type Marker = symbol;

/** Discriminates between build-time and runtime Css expressions. */
export type StyleKind = "buildtime" | "runtime";

/** The result of `Css.*.$` — for use in `css=` props (transformed at build time). */
export type BuildtimeStyles = RawCssProperties & { readonly __kind: "buildtime" };

/** The result of `RuntimeCss.*.$` — for use in `useRuntimeStyle`. */
export type RuntimeStyles = RawCssProperties & { readonly __kind: "runtime" };

export type Typography = "f10" | "f12" | "f14" | "f24" | "tiny";

export type CssSetVarKeys = `--${string}`;

export type CssSetVarScalar = string | number;

export type CssSetVarValue = CssSetVarScalar | {
  default?: CssSetVarScalar;
  media?: Partial<Record<Breakpoint, CssSetVarScalar>>;
  container?: Array<{ name?: string; gt?: number; lt?: number; value: CssSetVarScalar }>;
};

// Augment React types so all JSX elements accept the `css` prop:
// - HTMLAttributes/SVGAttributes cover intrinsic elements (div, svg, etc.)
// - JSX.IntrinsicAttributes covers custom components (Card, Page, etc.)
declare module "react" {
  interface HTMLAttributes<T> {
    css?: Properties;
  }
  interface SVGAttributes<T> {
    css?: Properties;
  }
  namespace JSX {
    interface IntrinsicAttributes {
      css?: Properties;
    }
  }
}

type Opts<T> = {
  rules: T;
  enabled: boolean;
  selector: string | undefined;
  elseApplied: boolean;
  runtimeError: string | undefined;
};

class CssBuilder<T extends Properties, S extends StyleKind = "buildtime"> {
  constructor(private opts: Opts<T>) {}

  // border
  /** Sets `borderStyle: "solid"; borderWidth: "1px"`. */
  get ba() {
    return this.add("borderStyle", "solid").add("borderWidth", "1px");
  }
  /** Sets `borderTopStyle: "solid"; borderTopWidth: "1px"`. */
  get bt() {
    return this.add("borderTopStyle", "solid").add("borderTopWidth", "1px");
  }
  /** Sets `borderRightStyle: "solid"; borderRightWidth: "1px"`. */
  get br() {
    return this.add("borderRightStyle", "solid").add("borderRightWidth", "1px");
  }
  /** Sets `borderBottomStyle: "solid"; borderBottomWidth: "1px"`. */
  get bb() {
    return this.add("borderBottomStyle", "solid").add("borderBottomWidth", "1px");
  }
  /** Sets `borderLeftStyle: "solid"; borderLeftWidth: "1px"`. */
  get bl() {
    return this.add("borderLeftStyle", "solid").add("borderLeftWidth", "1px");
  }
  /** Sets `borderStyle: "none"; borderWidth: "0"`. */
  get bn() {
    return this.add("borderStyle", "none").add("borderWidth", "0");
  }

  // borderColor
  /** Sets `borderColor: "#353535"`. */
  get bcBlack() {
    return this.add("borderColor", "#353535");
  }
  /** Sets `borderColor: "#888888"`. */
  get bcMidGray() {
    return this.add("borderColor", "#888888");
  }
  /** Sets `borderColor: "#cecece"`. */
  get bcLightGray() {
    return this.add("borderColor", "#cecece");
  }
  /** Sets `borderColor: "#fcfcfa"`. */
  get bcWhite() {
    return this.add("borderColor", "#fcfcfa");
  }
  /** Sets `borderColor: "#526675"`. */
  get bcBlue() {
    return this.add("borderColor", "#526675");
  }
  /** Sets `borderColor: "rgba(82, 102, 117, 0.3)"`. */
  get bcBlueFaded() {
    return this.add("borderColor", "rgba(82, 102, 117, 0.3)");
  }
  /** Sets `borderColor: "rgba(0, 0, 0, 0)"`. */
  get bcHollow() {
    return this.add("borderColor", "rgba(0, 0, 0, 0)");
  }
  /** Sets `borderColor: value`. */
  bc(value: Properties["borderColor"]) {
    return this.add("borderColor", value);
  }

  // borderRadius
  /** Sets `borderRadius: "0"`. */
  get br0() {
    return this.add("borderRadius", "0");
  }
  /** Sets `borderRadius: ".125rem"`. */
  get br1() {
    return this.add("borderRadius", ".125rem");
  }
  /** Sets `borderRadius: ".25rem"`. */
  get br2() {
    return this.add("borderRadius", ".25rem");
  }
  /** Sets `borderRadius: ".5rem"`. */
  get br3() {
    return this.add("borderRadius", ".5rem");
  }
  /** Sets `borderRadius: "1rem"`. */
  get br4() {
    return this.add("borderRadius", "1rem");
  }
  /** Sets `borderRadius: "100%"`. */
  get br100() {
    return this.add("borderRadius", "100%");
  }
  /** Sets `borderRadius: "9999px"`. */
  get brPill() {
    return this.add("borderRadius", "9999px");
  }
  /** Sets `borderRadius: value`. */
  borderRadius(value: Properties["borderRadius"]) {
    return this.add("borderRadius", value);
  }

  // borderStyle
  /** Sets `borderStyle: "dashed"`. */
  get bsDashed() {
    return this.add("borderStyle", "dashed");
  }
  /** Sets `borderStyle: "dotted"`. */
  get bsDotted() {
    return this.add("borderStyle", "dotted");
  }
  /** Sets `borderStyle: "none"`. */
  get bsn() {
    return this.add("borderStyle", "none");
  }
  /** Sets `borderStyle: "solid"`. */
  get bss() {
    return this.add("borderStyle", "solid");
  }
  /** Sets `borderStyle: value`. */
  bs(value: Properties["borderStyle"]) {
    return this.add("borderStyle", value);
  }

  // borderWidth
  /** Sets `borderWidth: "1px"`. */
  get bw1() {
    return this.add("borderWidth", "1px");
  }
  /** Sets `borderWidth: "2px"`. */
  get bw2() {
    return this.add("borderWidth", "2px");
  }
  /** Sets `borderWidth: value`. */
  bw(value: Properties["borderWidth"]) {
    return this.add("borderWidth", value);
  }

  // boxShadow
  /** Sets `boxShadow: "none"`. */
  get shadowNone() {
    return this.add("boxShadow", "none");
  }

  // container
  /** Sets `containerType: "size"`. */
  get cts() {
    return this.add("containerType", "size");
  }
  /** Sets `containerType: "inline-size"`. */
  get ctis() {
    return this.add("containerType", "inline-size");
  }
  /** Sets `containerType: "normal"`. */
  get ctn() {
    return this.add("containerType", "normal");
  }
  /** Sets `containerType: value`. */
  ct(value: Properties["containerType"]) {
    return this.add("containerType", value);
  }
  /** Sets `containerName: value`. */
  cn(value: Properties["containerName"]) {
    return this.add("containerName", value);
  }

  // coordinates
  /** Sets `top: "calc(var(--t-spacing) * 0)"`. */
  get top0() {
    return this.add("top", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `top: "calc(var(--t-spacing) * 1)"`. */
  get top1() {
    return this.add("top", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `top: "calc(var(--t-spacing) * 2)"`. */
  get top2() {
    return this.add("top", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `top: "calc(var(--t-spacing) * 3)"`. */
  get top3() {
    return this.add("top", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `top: "calc(var(--t-spacing) * 4)"`. */
  get top4() {
    return this.add("top", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `top: "calc(var(--t-spacing) * 5)"`. */
  get top5() {
    return this.add("top", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `top: "calc(var(--t-spacing) * 6)"`. */
  get top6() {
    return this.add("top", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `top: "calc(var(--t-spacing) * 7)"`. */
  get top7() {
    return this.add("top", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `top: "v"`. */
  top(v: number | string) {
    return this.add("top", maybeInc(v));
  }
  /** Sets `top: px`. */
  topPx(px: number) {
    return this.add("top", `${px}px`);
  }
  /** Sets `right: "calc(var(--t-spacing) * 0)"`. */
  get right0() {
    return this.add("right", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `right: "calc(var(--t-spacing) * 1)"`. */
  get right1() {
    return this.add("right", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `right: "calc(var(--t-spacing) * 2)"`. */
  get right2() {
    return this.add("right", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `right: "calc(var(--t-spacing) * 3)"`. */
  get right3() {
    return this.add("right", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `right: "calc(var(--t-spacing) * 4)"`. */
  get right4() {
    return this.add("right", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `right: "calc(var(--t-spacing) * 5)"`. */
  get right5() {
    return this.add("right", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `right: "calc(var(--t-spacing) * 6)"`. */
  get right6() {
    return this.add("right", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `right: "calc(var(--t-spacing) * 7)"`. */
  get right7() {
    return this.add("right", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `right: "v"`. */
  right(v: number | string) {
    return this.add("right", maybeInc(v));
  }
  /** Sets `right: px`. */
  rightPx(px: number) {
    return this.add("right", `${px}px`);
  }
  /** Sets `bottom: "calc(var(--t-spacing) * 0)"`. */
  get bottom0() {
    return this.add("bottom", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `bottom: "calc(var(--t-spacing) * 1)"`. */
  get bottom1() {
    return this.add("bottom", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `bottom: "calc(var(--t-spacing) * 2)"`. */
  get bottom2() {
    return this.add("bottom", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `bottom: "calc(var(--t-spacing) * 3)"`. */
  get bottom3() {
    return this.add("bottom", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `bottom: "calc(var(--t-spacing) * 4)"`. */
  get bottom4() {
    return this.add("bottom", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `bottom: "calc(var(--t-spacing) * 5)"`. */
  get bottom5() {
    return this.add("bottom", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `bottom: "calc(var(--t-spacing) * 6)"`. */
  get bottom6() {
    return this.add("bottom", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `bottom: "calc(var(--t-spacing) * 7)"`. */
  get bottom7() {
    return this.add("bottom", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `bottom: "v"`. */
  bottom(v: number | string) {
    return this.add("bottom", maybeInc(v));
  }
  /** Sets `bottom: px`. */
  bottomPx(px: number) {
    return this.add("bottom", `${px}px`);
  }
  /** Sets `left: "calc(var(--t-spacing) * 0)"`. */
  get left0() {
    return this.add("left", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `left: "calc(var(--t-spacing) * 1)"`. */
  get left1() {
    return this.add("left", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `left: "calc(var(--t-spacing) * 2)"`. */
  get left2() {
    return this.add("left", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `left: "calc(var(--t-spacing) * 3)"`. */
  get left3() {
    return this.add("left", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `left: "calc(var(--t-spacing) * 4)"`. */
  get left4() {
    return this.add("left", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `left: "calc(var(--t-spacing) * 5)"`. */
  get left5() {
    return this.add("left", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `left: "calc(var(--t-spacing) * 6)"`. */
  get left6() {
    return this.add("left", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `left: "calc(var(--t-spacing) * 7)"`. */
  get left7() {
    return this.add("left", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `left: "v"`. */
  left(v: number | string) {
    return this.add("left", maybeInc(v));
  }
  /** Sets `left: px`. */
  leftPx(px: number) {
    return this.add("left", `${px}px`);
  }

  // cursor
  /** Sets `cursor: "pointer"`. */
  get cursorPointer() {
    return this.add("cursor", "pointer");
  }
  /** Sets `cursor: "not-allowed"`. */
  get cursorNotAllowed() {
    return this.add("cursor", "not-allowed");
  }
  /** Sets `cursor: value`. */
  cursor(value: Properties["cursor"]) {
    return this.add("cursor", value);
  }

  // display
  /** Sets `display: "none"`. */
  get dn() {
    return this.add("display", "none");
  }
  /** Sets `display: "block"`. */
  get db() {
    return this.add("display", "block");
  }
  /** Sets `display: "inline-block"`. */
  get dib() {
    return this.add("display", "inline-block");
  }
  /** Sets `display: "inline-table"`. */
  get dit() {
    return this.add("display", "inline-table");
  }
  /** Sets `display: "table"`. */
  get dt() {
    return this.add("display", "table");
  }
  /** Sets `display: "table-cell"`. */
  get dtc() {
    return this.add("display", "table-cell");
  }
  /** Sets `display: "table-row"`. */
  get dtRow() {
    return this.add("display", "table-row");
  }
  /** Sets `display: "table-column"`. */
  get dtColumn() {
    return this.add("display", "table-column");
  }
  /** Sets `display: "table-column-group"`. */
  get dtColumnGroup() {
    return this.add("display", "table-column-group");
  }
  /** Sets `display: "grid"`. */
  get dg() {
    return this.add("display", "grid");
  }
  /** Sets `display: "inline-grid"`. */
  get dig() {
    return this.add("display", "inline-grid");
  }
  /** Sets `display: "flex"`. */
  get df() {
    return this.add("display", "flex");
  }
  /** Sets `display: "inline-flex"`. */
  get dif() {
    return this.add("display", "inline-flex");
  }
  /** Sets `display: value`. */
  display(value: Properties["display"]) {
    return this.add("display", value);
  }

  // flexbox
  /** Sets `flex: "initial"`. */
  get fi() {
    return this.add("flex", "initial");
  }
  /** Sets `flex: "auto"`. */
  get fa() {
    return this.add("flex", "auto");
  }
  /** Sets `flex: "none"`. */
  get fn() {
    return this.add("flex", "none");
  }
  /** Sets `flex: "1"`. */
  get f1() {
    return this.add("flex", "1");
  }
  /** Sets `flex: "2"`. */
  get f2() {
    return this.add("flex", "2");
  }
  /** Sets `flex: "3"`. */
  get f3() {
    return this.add("flex", "3");
  }
  /** Sets `flex: "4"`. */
  get f4() {
    return this.add("flex", "4");
  }
  /** Sets `flex: "5"`. */
  get f5() {
    return this.add("flex", "5");
  }
  /** Sets `flex: value`. */
  f(value: Properties["flex"]) {
    return this.add("flex", value);
  }
  /** Sets `justifyContent: "flex-start"`. */
  get jcfs() {
    return this.add("justifyContent", "flex-start");
  }
  /** Sets `justifyContent: "flex-end"`. */
  get jcfe() {
    return this.add("justifyContent", "flex-end");
  }
  /** Sets `justifyContent: "center"`. */
  get jcc() {
    return this.add("justifyContent", "center");
  }
  /** Sets `justifyContent: "space-between"`. */
  get jcsb() {
    return this.add("justifyContent", "space-between");
  }
  /** Sets `justifyContent: "space-around"`. */
  get jcsa() {
    return this.add("justifyContent", "space-around");
  }
  /** Sets `justifyContent: "space-evenly"`. */
  get jcse() {
    return this.add("justifyContent", "space-evenly");
  }
  /** Sets `justifyContent: value`. */
  jc(value: Properties["justifyContent"]) {
    return this.add("justifyContent", value);
  }
  /** Sets `justifySelf: "auto"`. */
  get jsa() {
    return this.add("justifySelf", "auto");
  }
  /** Sets `justifySelf: "center"`. */
  get jsc() {
    return this.add("justifySelf", "center");
  }
  /** Sets `justifySelf: "start"`. */
  get jss() {
    return this.add("justifySelf", "start");
  }
  /** Sets `justifySelf: "end"`. */
  get jse() {
    return this.add("justifySelf", "end");
  }
  /** Sets `justifySelf: value`. */
  js(value: Properties["justifySelf"]) {
    return this.add("justifySelf", value);
  }
  /** Sets `justifyItems: "flex-start"`. */
  get jifs() {
    return this.add("justifyItems", "flex-start");
  }
  /** Sets `justifyItems: "flex-end"`. */
  get jife() {
    return this.add("justifyItems", "flex-end");
  }
  /** Sets `justifyItems: "center"`. */
  get jic() {
    return this.add("justifyItems", "center");
  }
  /** Sets `justifyItems: "space-between"`. */
  get jisb() {
    return this.add("justifyItems", "space-between");
  }
  /** Sets `justifyItems: "space-around"`. */
  get jisa() {
    return this.add("justifyItems", "space-around");
  }
  /** Sets `justifyItems: "space-evenly"`. */
  get jise() {
    return this.add("justifyItems", "space-evenly");
  }
  /** Sets `justifyItems: value`. */
  ji(value: Properties["justifyItems"]) {
    return this.add("justifyItems", value);
  }
  /** Sets `alignSelf: "flex-start"`. */
  get asfs() {
    return this.add("alignSelf", "flex-start");
  }
  /** Sets `alignSelf: "flex-end"`. */
  get asfe() {
    return this.add("alignSelf", "flex-end");
  }
  /** Sets `alignSelf: "center"`. */
  get asc() {
    return this.add("alignSelf", "center");
  }
  /** Sets `alignSelf: "baseline"`. */
  get asb() {
    return this.add("alignSelf", "baseline");
  }
  /** Sets `alignSelf: "stretch"`. */
  get asStretch() {
    return this.add("alignSelf", "stretch");
  }
  /** Sets `alignSelf: value`. */
  as(value: Properties["alignSelf"]) {
    return this.add("alignSelf", value);
  }
  /** Sets `alignItems: "flex-start"`. */
  get aifs() {
    return this.add("alignItems", "flex-start");
  }
  /** Sets `alignItems: "flex-end"`. */
  get aife() {
    return this.add("alignItems", "flex-end");
  }
  /** Sets `alignItems: "start"`. */
  get ais() {
    return this.add("alignItems", "start");
  }
  /** Sets `alignItems: "end"`. */
  get aie() {
    return this.add("alignItems", "end");
  }
  /** Sets `alignItems: "center"`. */
  get aic() {
    return this.add("alignItems", "center");
  }
  /** Sets `alignItems: "baseline"`. */
  get aib() {
    return this.add("alignItems", "baseline");
  }
  /** Sets `alignItems: "stretch"`. */
  get aiStretch() {
    return this.add("alignItems", "stretch");
  }
  /** Sets `alignItems: value`. */
  ai(value: Properties["alignItems"]) {
    return this.add("alignItems", value);
  }
  /** Sets `placeSelf: "auto"`. */
  get psa() {
    return this.add("placeSelf", "auto");
  }
  /** Sets `placeSelf: "center"`. */
  get psc() {
    return this.add("placeSelf", "center");
  }
  /** Sets `placeSelf: "start"`. */
  get pss() {
    return this.add("placeSelf", "start");
  }
  /** Sets `placeSelf: "end"`. */
  get pse() {
    return this.add("placeSelf", "end");
  }
  /** Sets `placeSelf: "flex-start"`. */
  get psfs() {
    return this.add("placeSelf", "flex-start");
  }
  /** Sets `placeSelf: "flex-end"`. */
  get psfe() {
    return this.add("placeSelf", "flex-end");
  }
  /** Sets `placeSelf: "stretch"`. */
  get psStretch() {
    return this.add("placeSelf", "stretch");
  }
  /** Sets `placeSelf: value`. */
  ps(value: Properties["placeSelf"]) {
    return this.add("placeSelf", value);
  }
  /** Sets `placeContent: "center"`. */
  get pcc() {
    return this.add("placeContent", "center");
  }
  /** Sets `placeContent: "start"`. */
  get pcs() {
    return this.add("placeContent", "start");
  }
  /** Sets `placeContent: "end"`. */
  get pce() {
    return this.add("placeContent", "end");
  }
  /** Sets `placeContent: "space-between"`. */
  get pcsb() {
    return this.add("placeContent", "space-between");
  }
  /** Sets `placeContent: "space-around"`. */
  get pcsa() {
    return this.add("placeContent", "space-around");
  }
  /** Sets `placeContent: "space-evenly"`. */
  get pcse() {
    return this.add("placeContent", "space-evenly");
  }
  /** Sets `placeContent: "baseline"`. */
  get pcb() {
    return this.add("placeContent", "baseline");
  }
  /** Sets `placeContent: "stretch"`. */
  get pcStretch() {
    return this.add("placeContent", "stretch");
  }
  /** Sets `placeContent: value`. */
  pc(value: Properties["placeContent"]) {
    return this.add("placeContent", value);
  }
  /** Sets `placeItems: "center"`. */
  get pic() {
    return this.add("placeItems", "center");
  }
  /** Sets `placeItems: "start"`. */
  get pis() {
    return this.add("placeItems", "start");
  }
  /** Sets `placeItems: "end"`. */
  get pie() {
    return this.add("placeItems", "end");
  }
  /** Sets `placeItems: "space-between"`. */
  get pisb() {
    return this.add("placeItems", "space-between");
  }
  /** Sets `placeItems: "space-around"`. */
  get pisa() {
    return this.add("placeItems", "space-around");
  }
  /** Sets `placeItems: "space-evenly"`. */
  get pise() {
    return this.add("placeItems", "space-evenly");
  }
  /** Sets `placeItems: "baseline"`. */
  get pib() {
    return this.add("placeItems", "baseline");
  }
  /** Sets `placeItems: "stretch"`. */
  get piStretch() {
    return this.add("placeItems", "stretch");
  }
  /** Sets `placeItems: value`. */
  pi(value: Properties["placeItems"]) {
    return this.add("placeItems", value);
  }
  /** Sets `flexBasis: "100%"`. */
  get fb1() {
    return this.add("flexBasis", "100%");
  }
  /** Sets `flexBasis: "50%"`. */
  get fb2() {
    return this.add("flexBasis", "50%");
  }
  /** Sets `flexBasis: "33.333333%"`. */
  get fb3() {
    return this.add("flexBasis", "33.333333%");
  }
  /** Sets `flexBasis: "25%"`. */
  get fb4() {
    return this.add("flexBasis", "25%");
  }
  /** Sets `flexBasis: "20%"`. */
  get fb5() {
    return this.add("flexBasis", "20%");
  }
  /** Sets `flexBasis: "16.666666%"`. */
  get fb6() {
    return this.add("flexBasis", "16.666666%");
  }
  /** Sets `flexBasis: "14.285714%"`. */
  get fb7() {
    return this.add("flexBasis", "14.285714%");
  }
  /** Sets `flexBasis: "12.5%"`. */
  get fb0() {
    return this.add("flexBasis", "12.5%");
  }
  /** Sets `flexBasis: value`. */
  fb(value: Properties["flexBasis"]) {
    return this.add("flexBasis", value);
  }
  /** Sets `flexGrow: 0`. */
  get fg0() {
    return this.add("flexGrow", 0);
  }
  /** Sets `flexGrow: 1`. */
  get fg1() {
    return this.add("flexGrow", 1);
  }
  /** Sets `flexGrow: value`. */
  flexGrow(value: Properties["flexGrow"]) {
    return this.add("flexGrow", value);
  }
  /** Sets `flexShrink: 0`. */
  get fs0() {
    return this.add("flexShrink", 0);
  }
  /** Sets `flexShrink: 1`. */
  get fs1() {
    return this.add("flexShrink", 1);
  }
  /** Sets `flexShrink: value`. */
  flexShrink(value: Properties["flexShrink"]) {
    return this.add("flexShrink", value);
  }
  /** Sets `flexDirection: "row"`. */
  get fdr() {
    return this.add("flexDirection", "row");
  }
  /** Sets `flexDirection: "row-reverse"`. */
  get fdrr() {
    return this.add("flexDirection", "row-reverse");
  }
  /** Sets `flexDirection: "column"`. */
  get fdc() {
    return this.add("flexDirection", "column");
  }
  /** Sets `flexDirection: "column-reverse"`. */
  get fdcr() {
    return this.add("flexDirection", "column-reverse");
  }
  /** Sets `flexDirection: value`. */
  fd(value: Properties["flexDirection"]) {
    return this.add("flexDirection", value);
  }
  /** Sets `flexWrap: "wrap"`. */
  get fww() {
    return this.add("flexWrap", "wrap");
  }
  /** Sets `flexWrap: "wrap-reverse"`. */
  get fwr() {
    return this.add("flexWrap", "wrap-reverse");
  }
  /** Sets `flexWrap: "nowrap"`. */
  get fwnw() {
    return this.add("flexWrap", "nowrap");
  }
  /** Sets `flexWrap: value`. */
  flexWrap(value: Properties["flexWrap"]) {
    return this.add("flexWrap", value);
  }
  /** Sets `order: value`. */
  order(value: Properties["order"]) {
    return this.add("order", value);
  }

  // float
  /** Sets `float: "left"`. */
  get fl() {
    return this.add("float", "left");
  }
  /** Sets `float: "right"`. */
  get fr() {
    return this.add("float", "right");
  }
  /** Sets `float: value`. */
  float(value: Properties["float"]) {
    return this.add("float", value);
  }

  // fontWeight
  /** Sets `fontWeight: "normal"`. */
  get fwn() {
    return this.add("fontWeight", "normal");
  }
  /** Sets `fontWeight: "bold"`. */
  get fwb() {
    return this.add("fontWeight", "bold");
  }
  /** Sets `fontWeight: 100`. */
  get fw1() {
    return this.add("fontWeight", 100);
  }
  /** Sets `fontWeight: 200`. */
  get fw2() {
    return this.add("fontWeight", 200);
  }
  /** Sets `fontWeight: 300`. */
  get fw3() {
    return this.add("fontWeight", 300);
  }
  /** Sets `fontWeight: 400`. */
  get fw4() {
    return this.add("fontWeight", 400);
  }
  /** Sets `fontWeight: 500`. */
  get fw5() {
    return this.add("fontWeight", 500);
  }
  /** Sets `fontWeight: 600`. */
  get fw6() {
    return this.add("fontWeight", 600);
  }
  /** Sets `fontWeight: 700`. */
  get fw7() {
    return this.add("fontWeight", 700);
  }
  /** Sets `fontWeight: 800`. */
  get fw8() {
    return this.add("fontWeight", 800);
  }
  /** Sets `fontWeight: 900`. */
  get fw9() {
    return this.add("fontWeight", 900);
  }
  /** Sets `fontWeight: value`. */
  fw(value: Properties["fontWeight"]) {
    return this.add("fontWeight", value);
  }

  // grid
  /** Sets `gridTemplateColumns: value`. */
  gtc(value: Properties["gridTemplateColumns"]) {
    return this.add("gridTemplateColumns", value);
  }
  /** Sets `gridTemplateRows: value`. */
  gtr(value: Properties["gridTemplateRows"]) {
    return this.add("gridTemplateRows", value);
  }
  /** Sets `gridRow: value`. */
  gr(value: Properties["gridRow"]) {
    return this.add("gridRow", value);
  }
  /** Sets `gridColumn: value`. */
  gc(value: Properties["gridColumn"]) {
    return this.add("gridColumn", value);
  }
  /** Sets `gridAutoRows: value`. */
  gar(value: Properties["gridAutoRows"]) {
    return this.add("gridAutoRows", value);
  }
  /** Sets `gridAutoColumns: value`. */
  gac(value: Properties["gridAutoColumns"]) {
    return this.add("gridAutoColumns", value);
  }
  /** Sets `gap: "calc(var(--t-spacing) * 0)"`. */
  get gap0() {
    return this.add("gap", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `gap: "calc(var(--t-spacing) * 1)"`. */
  get gap1() {
    return this.add("gap", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `gap: "calc(var(--t-spacing) * 2)"`. */
  get gap2() {
    return this.add("gap", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `gap: "calc(var(--t-spacing) * 3)"`. */
  get gap3() {
    return this.add("gap", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `gap: "calc(var(--t-spacing) * 4)"`. */
  get gap4() {
    return this.add("gap", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `gap: "calc(var(--t-spacing) * 5)"`. */
  get gap5() {
    return this.add("gap", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `gap: "calc(var(--t-spacing) * 6)"`. */
  get gap6() {
    return this.add("gap", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `gap: "calc(var(--t-spacing) * 7)"`. */
  get gap7() {
    return this.add("gap", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `gap: "v"`. */
  gap(v: number | string) {
    return this.add("gap", maybeInc(v));
  }
  /** Sets `gap: px`. */
  gapPx(px: number) {
    return this.add("gap", `${px}px`);
  }
  /** Sets `rowGap: "calc(var(--t-spacing) * 0)"`. */
  get rg0() {
    return this.add("rowGap", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `rowGap: "calc(var(--t-spacing) * 1)"`. */
  get rg1() {
    return this.add("rowGap", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `rowGap: "calc(var(--t-spacing) * 2)"`. */
  get rg2() {
    return this.add("rowGap", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `rowGap: "calc(var(--t-spacing) * 3)"`. */
  get rg3() {
    return this.add("rowGap", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `rowGap: "calc(var(--t-spacing) * 4)"`. */
  get rg4() {
    return this.add("rowGap", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `rowGap: "calc(var(--t-spacing) * 5)"`. */
  get rg5() {
    return this.add("rowGap", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `rowGap: "calc(var(--t-spacing) * 6)"`. */
  get rg6() {
    return this.add("rowGap", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `rowGap: "calc(var(--t-spacing) * 7)"`. */
  get rg7() {
    return this.add("rowGap", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `rowGap: "v"`. */
  rg(v: number | string) {
    return this.add("rowGap", maybeInc(v));
  }
  /** Sets `rowGap: px`. */
  rgPx(px: number) {
    return this.add("rowGap", `${px}px`);
  }
  /** Sets `columnGap: "calc(var(--t-spacing) * 0)"`. */
  get cg0() {
    return this.add("columnGap", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `columnGap: "calc(var(--t-spacing) * 1)"`. */
  get cg1() {
    return this.add("columnGap", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `columnGap: "calc(var(--t-spacing) * 2)"`. */
  get cg2() {
    return this.add("columnGap", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `columnGap: "calc(var(--t-spacing) * 3)"`. */
  get cg3() {
    return this.add("columnGap", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `columnGap: "calc(var(--t-spacing) * 4)"`. */
  get cg4() {
    return this.add("columnGap", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `columnGap: "calc(var(--t-spacing) * 5)"`. */
  get cg5() {
    return this.add("columnGap", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `columnGap: "calc(var(--t-spacing) * 6)"`. */
  get cg6() {
    return this.add("columnGap", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `columnGap: "calc(var(--t-spacing) * 7)"`. */
  get cg7() {
    return this.add("columnGap", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `columnGap: "v"`. */
  cg(v: number | string) {
    return this.add("columnGap", maybeInc(v));
  }
  /** Sets `columnGap: px`. */
  cgPx(px: number) {
    return this.add("columnGap", `${px}px`);
  }

  // height
  /** Sets `height: "calc(var(--t-spacing) * 0)"`. */
  get h0() {
    return this.add("height", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `height: "calc(var(--t-spacing) * 1)"`. */
  get h1() {
    return this.add("height", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `height: "calc(var(--t-spacing) * 2)"`. */
  get h2() {
    return this.add("height", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `height: "calc(var(--t-spacing) * 3)"`. */
  get h3() {
    return this.add("height", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `height: "calc(var(--t-spacing) * 4)"`. */
  get h4() {
    return this.add("height", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `height: "calc(var(--t-spacing) * 5)"`. */
  get h5() {
    return this.add("height", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `height: "calc(var(--t-spacing) * 6)"`. */
  get h6() {
    return this.add("height", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `height: "calc(var(--t-spacing) * 7)"`. */
  get h7() {
    return this.add("height", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `height: "auto"`. */
  get ha() {
    return this.add("height", "auto");
  }
  /** Sets `height: "v"`. */
  h(v: number | string) {
    return this.add("height", maybeInc(v));
  }
  /** Sets `height: px`. */
  hPx(px: number) {
    return this.add("height", `${px}px`);
  }
  /** Sets `height: "25%"`. */
  get h25() {
    return this.add("height", "25%");
  }
  /** Sets `height: "50%"`. */
  get h50() {
    return this.add("height", "50%");
  }
  /** Sets `height: "75%"`. */
  get h75() {
    return this.add("height", "75%");
  }
  /** Sets `height: "100%"`. */
  get h100() {
    return this.add("height", "100%");
  }
  /** Sets `height: "25vh"`. */
  get vh25() {
    return this.add("height", "25vh");
  }
  /** Sets `height: "50vh"`. */
  get vh50() {
    return this.add("height", "50vh");
  }
  /** Sets `height: "75vh"`. */
  get vh75() {
    return this.add("height", "75vh");
  }
  /** Sets `height: "100vh"`. */
  get vh100() {
    return this.add("height", "100vh");
  }
  /** Sets `height: "fit-content"`. */
  get hfc() {
    return this.add("height", "fit-content");
  }
  /** Sets `height: "max-content"`. */
  get hmaxc() {
    return this.add("height", "max-content");
  }
  /** Sets `height: "min-content"`. */
  get hminc() {
    return this.add("height", "min-content");
  }
  /** Sets `minHeight: 0`. */
  get mh0() {
    return this.add("minHeight", 0);
  }
  /** Sets `minHeight: "25%"`. */
  get mh25() {
    return this.add("minHeight", "25%");
  }
  /** Sets `minHeight: "50%"`. */
  get mh50() {
    return this.add("minHeight", "50%");
  }
  /** Sets `minHeight: "75%"`. */
  get mh75() {
    return this.add("minHeight", "75%");
  }
  /** Sets `minHeight: "100%"`. */
  get mh100() {
    return this.add("minHeight", "100%");
  }
  /** Sets `minHeight: "100vh"`. */
  get mvh100() {
    return this.add("minHeight", "100vh");
  }
  /** Sets `minHeight: value`. */
  mh(value: Properties["minHeight"]) {
    return this.add("minHeight", value);
  }
  /** Sets `minHeight: px`. */
  mhPx(px: number) {
    return this.mh(`${px}px`);
  }
  /** Sets `maxHeight: "0"`. */
  get maxh0() {
    return this.add("maxHeight", "0");
  }
  /** Sets `maxHeight: "25%"`. */
  get maxh25() {
    return this.add("maxHeight", "25%");
  }
  /** Sets `maxHeight: "50%"`. */
  get maxh50() {
    return this.add("maxHeight", "50%");
  }
  /** Sets `maxHeight: "75%"`. */
  get maxh75() {
    return this.add("maxHeight", "75%");
  }
  /** Sets `maxHeight: "100%"`. */
  get maxh100() {
    return this.add("maxHeight", "100%");
  }
  /** Sets `maxHeight: value`. */
  maxh(value: Properties["maxHeight"]) {
    return this.add("maxHeight", value);
  }
  /** Sets `maxHeight: px`. */
  maxhPx(px: number) {
    return this.maxh(`${px}px`);
  }
  /** Sets `height: px; width: px`. */
  sqPx(px: number) {
    return this.add("height", `${px}px`).add("width", `${px}px`);
  }

  // lineClamp
  /** Sets `overflow: "hidden"; display: "-webkit-box"; WebkitBoxOrient: "vertical"; textOverflow: "ellipsis"; WebkitLineClamp: 1`. */
  get lineClamp1() {
    return this.add("overflow", "hidden").add("display", "-webkit-box").add("WebkitBoxOrient", "vertical").add(
      "textOverflow",
      "ellipsis",
    ).add("WebkitLineClamp", 1);
  }
  /** Sets `overflow: "hidden"; display: "-webkit-box"; WebkitBoxOrient: "vertical"; textOverflow: "ellipsis"; WebkitLineClamp: 2`. */
  get lineClamp2() {
    return this.add("overflow", "hidden").add("display", "-webkit-box").add("WebkitBoxOrient", "vertical").add(
      "textOverflow",
      "ellipsis",
    ).add("WebkitLineClamp", 2);
  }
  /** Sets `overflow: "hidden"; display: "-webkit-box"; WebkitBoxOrient: "vertical"; textOverflow: "ellipsis"; WebkitLineClamp: 3`. */
  get lineClamp3() {
    return this.add("overflow", "hidden").add("display", "-webkit-box").add("WebkitBoxOrient", "vertical").add(
      "textOverflow",
      "ellipsis",
    ).add("WebkitLineClamp", 3);
  }
  /** Sets `overflow: "hidden"; display: "-webkit-box"; WebkitBoxOrient: "vertical"; textOverflow: "ellipsis"; WebkitLineClamp: 4`. */
  get lineClamp4() {
    return this.add("overflow", "hidden").add("display", "-webkit-box").add("WebkitBoxOrient", "vertical").add(
      "textOverflow",
      "ellipsis",
    ).add("WebkitLineClamp", 4);
  }
  /** Sets `overflow: "hidden"; display: "-webkit-box"; WebkitBoxOrient: "vertical"; textOverflow: "ellipsis"; WebkitLineClamp: 5`. */
  get lineClamp5() {
    return this.add("overflow", "hidden").add("display", "-webkit-box").add("WebkitBoxOrient", "vertical").add(
      "textOverflow",
      "ellipsis",
    ).add("WebkitLineClamp", 5);
  }
  /** Sets `overflow: "hidden"; display: "-webkit-box"; WebkitBoxOrient: "vertical"; textOverflow: "ellipsis"; WebkitLineClamp: 6`. */
  get lineClamp6() {
    return this.add("overflow", "hidden").add("display", "-webkit-box").add("WebkitBoxOrient", "vertical").add(
      "textOverflow",
      "ellipsis",
    ).add("WebkitLineClamp", 6);
  }
  /** Sets `WebkitLineClamp: "unset"`. */
  get lineClampNone() {
    return this.add("WebkitLineClamp", "unset");
  }
  /** Sets `WebkitLineClamp: value`. */
  lineClamp(value: Properties["WebkitLineClamp"]) {
    return this.add("WebkitLineClamp", value).add("overflow", "hidden").add("display", "-webkit-box").add(
      "WebkitBoxOrient",
      "vertical",
    ).add("textOverflow", "ellipsis");
  }

  // objectFit
  /** Sets `objectFit: "contain"`. */
  get objectContain() {
    return this.add("objectFit", "contain");
  }
  /** Sets `objectFit: "cover"`. */
  get objectCover() {
    return this.add("objectFit", "cover");
  }
  /** Sets `objectFit: "fill"`. */
  get objectFill() {
    return this.add("objectFit", "fill");
  }
  /** Sets `objectFit: "none"`. */
  get objectNone() {
    return this.add("objectFit", "none");
  }
  /** Sets `objectFit: "scale-down"`. */
  get objectScaleDown() {
    return this.add("objectFit", "scale-down");
  }
  /** Sets `objectFit: value`. */
  objectFit(value: Properties["objectFit"]) {
    return this.add("objectFit", value);
  }

  // opacity
  /** Sets `opacity: "0"`. */
  get o0() {
    return this.add("opacity", "0");
  }
  /** Sets `opacity: "0.25"`. */
  get o25() {
    return this.add("opacity", "0.25");
  }
  /** Sets `opacity: "0.5"`. */
  get o50() {
    return this.add("opacity", "0.5");
  }
  /** Sets `opacity: "0.75"`. */
  get o75() {
    return this.add("opacity", "0.75");
  }
  /** Sets `opacity: "1"`. */
  get o100() {
    return this.add("opacity", "1");
  }
  /** Sets `opacity: value`. */
  o(value: Properties["opacity"]) {
    return this.add("opacity", value);
  }

  // outline
  /** Sets `outline: "1px solid"`. */
  get outline1() {
    return this.add("outline", "1px solid");
  }
  /** Sets `outline: "1px solid transparent"`. */
  get outlineTransparent() {
    return this.add("outline", "1px solid transparent");
  }
  /** Sets `outline: "0"`. */
  get outline0() {
    return this.add("outline", "0");
  }
  /** Sets `outline: value`. */
  outline(value: Properties["outline"]) {
    return this.add("outline", value);
  }

  // overflow
  /** Sets `overflow: "visible"`. */
  get ov() {
    return this.add("overflow", "visible");
  }
  /** Sets `overflow: "hidden"`. */
  get oh() {
    return this.add("overflow", "hidden");
  }
  /** Sets `overflow: "scroll"`. */
  get os() {
    return this.add("overflow", "scroll");
  }
  /** Sets `overflow: "auto"`. */
  get oa() {
    return this.add("overflow", "auto");
  }
  /** Sets `overflow: value`. */
  overflow(value: Properties["overflow"]) {
    return this.add("overflow", value);
  }
  /** Sets `overflowY: "visible"`. */
  get oyv() {
    return this.add("overflowY", "visible");
  }
  /** Sets `overflowY: "hidden"`. */
  get oyh() {
    return this.add("overflowY", "hidden");
  }
  /** Sets `overflowY: "scroll"`. */
  get oys() {
    return this.add("overflowY", "scroll");
  }
  /** Sets `overflowY: "auto"`. */
  get oya() {
    return this.add("overflowY", "auto");
  }
  /** Sets `overflowY: value`. */
  overflowY(value: Properties["overflowY"]) {
    return this.add("overflowY", value);
  }
  /** Sets `overflowX: "visible"`. */
  get oxv() {
    return this.add("overflowX", "visible");
  }
  /** Sets `overflowX: "hidden"`. */
  get oxh() {
    return this.add("overflowX", "hidden");
  }
  /** Sets `overflowX: "scroll"`. */
  get oxs() {
    return this.add("overflowX", "scroll");
  }
  /** Sets `overflowX: "auto"`. */
  get oxa() {
    return this.add("overflowX", "auto");
  }
  /** Sets `overflowX: value`. */
  overflowX(value: Properties["overflowX"]) {
    return this.add("overflowX", value);
  }

  // position
  /** Sets `position: "absolute"`. */
  get absolute() {
    return this.add("position", "absolute");
  }
  /** Sets `position: "fixed"`. */
  get fixed() {
    return this.add("position", "fixed");
  }
  /** Sets `position: "static"`. */
  get static() {
    return this.add("position", "static");
  }
  /** Sets `position: "relative"`. */
  get relative() {
    return this.add("position", "relative");
  }
  /** Sets `position: "sticky"`. */
  get sticky() {
    return this.add("position", "sticky");
  }
  /** Sets `position: value`. */
  position(value: Properties["position"]) {
    return this.add("position", value);
  }

  // skins
  /** Sets `color: "#353535"`. */
  get black() {
    return this.add("color", "#353535");
  }
  /** Sets `color: "#888888"`. */
  get midGray() {
    return this.add("color", "#888888");
  }
  /** Sets `color: "#cecece"`. */
  get lightGray() {
    return this.add("color", "#cecece");
  }
  /** Sets `color: "#fcfcfa"`. */
  get white() {
    return this.add("color", "#fcfcfa");
  }
  /** Sets `color: "#526675"`. */
  get blue() {
    return this.add("color", "#526675");
  }
  /** Sets `color: "rgba(82, 102, 117, 0.3)"`. */
  get blueFaded() {
    return this.add("color", "rgba(82, 102, 117, 0.3)");
  }
  /** Sets `color: "rgba(0, 0, 0, 0)"`. */
  get hollow() {
    return this.add("color", "rgba(0, 0, 0, 0)");
  }
  /** Sets `color: value`. */
  color(value: Properties["color"]) {
    return this.add("color", value);
  }
  /** Sets `backgroundColor: "#353535"`. */
  get bgBlack() {
    return this.add("backgroundColor", "#353535");
  }
  /** Sets `backgroundColor: "#888888"`. */
  get bgMidGray() {
    return this.add("backgroundColor", "#888888");
  }
  /** Sets `backgroundColor: "#cecece"`. */
  get bgLightGray() {
    return this.add("backgroundColor", "#cecece");
  }
  /** Sets `backgroundColor: "#fcfcfa"`. */
  get bgWhite() {
    return this.add("backgroundColor", "#fcfcfa");
  }
  /** Sets `backgroundColor: "#526675"`. */
  get bgBlue() {
    return this.add("backgroundColor", "#526675");
  }
  /** Sets `backgroundColor: "rgba(82, 102, 117, 0.3)"`. */
  get bgBlueFaded() {
    return this.add("backgroundColor", "rgba(82, 102, 117, 0.3)");
  }
  /** Sets `backgroundColor: "rgba(0, 0, 0, 0)"`. */
  get bgHollow() {
    return this.add("backgroundColor", "rgba(0, 0, 0, 0)");
  }
  /** Sets `backgroundColor: value`. */
  bgColor(value: Properties["backgroundColor"]) {
    return this.add("backgroundColor", value);
  }
  /** Sets `fill: "#353535"`. */
  get fBlack() {
    return this.add("fill", "#353535");
  }
  /** Sets `fill: "#888888"`. */
  get fMidGray() {
    return this.add("fill", "#888888");
  }
  /** Sets `fill: "#cecece"`. */
  get fLightGray() {
    return this.add("fill", "#cecece");
  }
  /** Sets `fill: "#fcfcfa"`. */
  get fWhite() {
    return this.add("fill", "#fcfcfa");
  }
  /** Sets `fill: "#526675"`. */
  get fBlue() {
    return this.add("fill", "#526675");
  }
  /** Sets `fill: "rgba(82, 102, 117, 0.3)"`. */
  get fBlueFaded() {
    return this.add("fill", "rgba(82, 102, 117, 0.3)");
  }
  /** Sets `fill: "rgba(0, 0, 0, 0)"`. */
  get fHollow() {
    return this.add("fill", "rgba(0, 0, 0, 0)");
  }
  /** Sets `fill: value`. */
  fill(value: Properties["fill"]) {
    return this.add("fill", value);
  }

  // spacing
  /** Sets `marginTop: "calc(var(--t-spacing) * 0)"`. */
  get mt0() {
    return this.add("marginTop", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 1)"`. */
  get mt1() {
    return this.add("marginTop", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 2)"`. */
  get mt2() {
    return this.add("marginTop", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 3)"`. */
  get mt3() {
    return this.add("marginTop", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 4)"`. */
  get mt4() {
    return this.add("marginTop", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 5)"`. */
  get mt5() {
    return this.add("marginTop", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 6)"`. */
  get mt6() {
    return this.add("marginTop", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 7)"`. */
  get mt7() {
    return this.add("marginTop", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `marginTop: "auto"`. */
  get mta() {
    return this.add("marginTop", "auto");
  }
  /** Sets `marginTop: "v"`. */
  mt(v: number | string) {
    return this.add("marginTop", maybeInc(v));
  }
  /** Sets `marginTop: px`. */
  mtPx(px: number) {
    return this.add("marginTop", `${px}px`);
  }
  /** Sets `marginRight: "calc(var(--t-spacing) * 0)"`. */
  get mr0() {
    return this.add("marginRight", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `marginRight: "calc(var(--t-spacing) * 1)"`. */
  get mr1() {
    return this.add("marginRight", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `marginRight: "calc(var(--t-spacing) * 2)"`. */
  get mr2() {
    return this.add("marginRight", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `marginRight: "calc(var(--t-spacing) * 3)"`. */
  get mr3() {
    return this.add("marginRight", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `marginRight: "calc(var(--t-spacing) * 4)"`. */
  get mr4() {
    return this.add("marginRight", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `marginRight: "calc(var(--t-spacing) * 5)"`. */
  get mr5() {
    return this.add("marginRight", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `marginRight: "calc(var(--t-spacing) * 6)"`. */
  get mr6() {
    return this.add("marginRight", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `marginRight: "calc(var(--t-spacing) * 7)"`. */
  get mr7() {
    return this.add("marginRight", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `marginRight: "auto"`. */
  get mra() {
    return this.add("marginRight", "auto");
  }
  /** Sets `marginRight: "v"`. */
  mr(v: number | string) {
    return this.add("marginRight", maybeInc(v));
  }
  /** Sets `marginRight: px`. */
  mrPx(px: number) {
    return this.add("marginRight", `${px}px`);
  }
  /** Sets `marginBottom: "calc(var(--t-spacing) * 0)"`. */
  get mb0() {
    return this.add("marginBottom", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `marginBottom: "calc(var(--t-spacing) * 1)"`. */
  get mb1() {
    return this.add("marginBottom", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `marginBottom: "calc(var(--t-spacing) * 2)"`. */
  get mb2() {
    return this.add("marginBottom", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `marginBottom: "calc(var(--t-spacing) * 3)"`. */
  get mb3() {
    return this.add("marginBottom", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `marginBottom: "calc(var(--t-spacing) * 4)"`. */
  get mb4() {
    return this.add("marginBottom", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `marginBottom: "calc(var(--t-spacing) * 5)"`. */
  get mb5() {
    return this.add("marginBottom", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `marginBottom: "calc(var(--t-spacing) * 6)"`. */
  get mb6() {
    return this.add("marginBottom", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `marginBottom: "calc(var(--t-spacing) * 7)"`. */
  get mb7() {
    return this.add("marginBottom", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `marginBottom: "auto"`. */
  get mba() {
    return this.add("marginBottom", "auto");
  }
  /** Sets `marginBottom: "v"`. */
  mb(v: number | string) {
    return this.add("marginBottom", maybeInc(v));
  }
  /** Sets `marginBottom: px`. */
  mbPx(px: number) {
    return this.add("marginBottom", `${px}px`);
  }
  /** Sets `marginLeft: "calc(var(--t-spacing) * 0)"`. */
  get ml0() {
    return this.add("marginLeft", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `marginLeft: "calc(var(--t-spacing) * 1)"`. */
  get ml1() {
    return this.add("marginLeft", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `marginLeft: "calc(var(--t-spacing) * 2)"`. */
  get ml2() {
    return this.add("marginLeft", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `marginLeft: "calc(var(--t-spacing) * 3)"`. */
  get ml3() {
    return this.add("marginLeft", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `marginLeft: "calc(var(--t-spacing) * 4)"`. */
  get ml4() {
    return this.add("marginLeft", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `marginLeft: "calc(var(--t-spacing) * 5)"`. */
  get ml5() {
    return this.add("marginLeft", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `marginLeft: "calc(var(--t-spacing) * 6)"`. */
  get ml6() {
    return this.add("marginLeft", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `marginLeft: "calc(var(--t-spacing) * 7)"`. */
  get ml7() {
    return this.add("marginLeft", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `marginLeft: "auto"`. */
  get mla() {
    return this.add("marginLeft", "auto");
  }
  /** Sets `marginLeft: "v"`. */
  ml(v: number | string) {
    return this.add("marginLeft", maybeInc(v));
  }
  /** Sets `marginLeft: px`. */
  mlPx(px: number) {
    return this.add("marginLeft", `${px}px`);
  }
  /** Sets `marginLeft: "calc(var(--t-spacing) * 0)"; marginRight: "calc(var(--t-spacing) * 0)"`. */
  get mx0() {
    return this.add("marginLeft", "calc(var(--t-spacing) * 0)").add("marginRight", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `marginLeft: "calc(var(--t-spacing) * 1)"; marginRight: "calc(var(--t-spacing) * 1)"`. */
  get mx1() {
    return this.add("marginLeft", "calc(var(--t-spacing) * 1)").add("marginRight", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `marginLeft: "calc(var(--t-spacing) * 2)"; marginRight: "calc(var(--t-spacing) * 2)"`. */
  get mx2() {
    return this.add("marginLeft", "calc(var(--t-spacing) * 2)").add("marginRight", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `marginLeft: "calc(var(--t-spacing) * 3)"; marginRight: "calc(var(--t-spacing) * 3)"`. */
  get mx3() {
    return this.add("marginLeft", "calc(var(--t-spacing) * 3)").add("marginRight", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `marginLeft: "calc(var(--t-spacing) * 4)"; marginRight: "calc(var(--t-spacing) * 4)"`. */
  get mx4() {
    return this.add("marginLeft", "calc(var(--t-spacing) * 4)").add("marginRight", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `marginLeft: "calc(var(--t-spacing) * 5)"; marginRight: "calc(var(--t-spacing) * 5)"`. */
  get mx5() {
    return this.add("marginLeft", "calc(var(--t-spacing) * 5)").add("marginRight", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `marginLeft: "calc(var(--t-spacing) * 6)"; marginRight: "calc(var(--t-spacing) * 6)"`. */
  get mx6() {
    return this.add("marginLeft", "calc(var(--t-spacing) * 6)").add("marginRight", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `marginLeft: "calc(var(--t-spacing) * 7)"; marginRight: "calc(var(--t-spacing) * 7)"`. */
  get mx7() {
    return this.add("marginLeft", "calc(var(--t-spacing) * 7)").add("marginRight", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `marginLeft: "auto"; marginRight: "auto"`. */
  get mxa() {
    return this.add("marginLeft", "auto").add("marginRight", "auto");
  }
  /** Sets `marginLeft: "v"; marginRight: "v"`. */
  mx(v: number | string) {
    return this.add("marginLeft", maybeInc(v)).add("marginRight", maybeInc(v));
  }
  /** Sets `marginLeft: px; marginRight: px`. */
  mxPx(px: number) {
    return this.add("marginLeft", `${px}px`).add("marginRight", `${px}px`);
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 0)"; marginBottom: "calc(var(--t-spacing) * 0)"`. */
  get my0() {
    return this.add("marginTop", "calc(var(--t-spacing) * 0)").add("marginBottom", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 1)"; marginBottom: "calc(var(--t-spacing) * 1)"`. */
  get my1() {
    return this.add("marginTop", "calc(var(--t-spacing) * 1)").add("marginBottom", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 2)"; marginBottom: "calc(var(--t-spacing) * 2)"`. */
  get my2() {
    return this.add("marginTop", "calc(var(--t-spacing) * 2)").add("marginBottom", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 3)"; marginBottom: "calc(var(--t-spacing) * 3)"`. */
  get my3() {
    return this.add("marginTop", "calc(var(--t-spacing) * 3)").add("marginBottom", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 4)"; marginBottom: "calc(var(--t-spacing) * 4)"`. */
  get my4() {
    return this.add("marginTop", "calc(var(--t-spacing) * 4)").add("marginBottom", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 5)"; marginBottom: "calc(var(--t-spacing) * 5)"`. */
  get my5() {
    return this.add("marginTop", "calc(var(--t-spacing) * 5)").add("marginBottom", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 6)"; marginBottom: "calc(var(--t-spacing) * 6)"`. */
  get my6() {
    return this.add("marginTop", "calc(var(--t-spacing) * 6)").add("marginBottom", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 7)"; marginBottom: "calc(var(--t-spacing) * 7)"`. */
  get my7() {
    return this.add("marginTop", "calc(var(--t-spacing) * 7)").add("marginBottom", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `marginTop: "auto"; marginBottom: "auto"`. */
  get mya() {
    return this.add("marginTop", "auto").add("marginBottom", "auto");
  }
  /** Sets `marginTop: "v"; marginBottom: "v"`. */
  my(v: number | string) {
    return this.add("marginTop", maybeInc(v)).add("marginBottom", maybeInc(v));
  }
  /** Sets `marginTop: px; marginBottom: px`. */
  myPx(px: number) {
    return this.add("marginTop", `${px}px`).add("marginBottom", `${px}px`);
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 0)"; marginBottom: "calc(var(--t-spacing) * 0)"; marginRight: "calc(var(--t-spacing) * 0)"; marginLeft: "calc(var(--t-spacing) * 0)"`. */
  get m0() {
    return this.add("marginTop", "calc(var(--t-spacing) * 0)").add("marginBottom", "calc(var(--t-spacing) * 0)").add(
      "marginRight",
      "calc(var(--t-spacing) * 0)",
    ).add("marginLeft", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 1)"; marginBottom: "calc(var(--t-spacing) * 1)"; marginRight: "calc(var(--t-spacing) * 1)"; marginLeft: "calc(var(--t-spacing) * 1)"`. */
  get m1() {
    return this.add("marginTop", "calc(var(--t-spacing) * 1)").add("marginBottom", "calc(var(--t-spacing) * 1)").add(
      "marginRight",
      "calc(var(--t-spacing) * 1)",
    ).add("marginLeft", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 2)"; marginBottom: "calc(var(--t-spacing) * 2)"; marginRight: "calc(var(--t-spacing) * 2)"; marginLeft: "calc(var(--t-spacing) * 2)"`. */
  get m2() {
    return this.add("marginTop", "calc(var(--t-spacing) * 2)").add("marginBottom", "calc(var(--t-spacing) * 2)").add(
      "marginRight",
      "calc(var(--t-spacing) * 2)",
    ).add("marginLeft", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 3)"; marginBottom: "calc(var(--t-spacing) * 3)"; marginRight: "calc(var(--t-spacing) * 3)"; marginLeft: "calc(var(--t-spacing) * 3)"`. */
  get m3() {
    return this.add("marginTop", "calc(var(--t-spacing) * 3)").add("marginBottom", "calc(var(--t-spacing) * 3)").add(
      "marginRight",
      "calc(var(--t-spacing) * 3)",
    ).add("marginLeft", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 4)"; marginBottom: "calc(var(--t-spacing) * 4)"; marginRight: "calc(var(--t-spacing) * 4)"; marginLeft: "calc(var(--t-spacing) * 4)"`. */
  get m4() {
    return this.add("marginTop", "calc(var(--t-spacing) * 4)").add("marginBottom", "calc(var(--t-spacing) * 4)").add(
      "marginRight",
      "calc(var(--t-spacing) * 4)",
    ).add("marginLeft", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 5)"; marginBottom: "calc(var(--t-spacing) * 5)"; marginRight: "calc(var(--t-spacing) * 5)"; marginLeft: "calc(var(--t-spacing) * 5)"`. */
  get m5() {
    return this.add("marginTop", "calc(var(--t-spacing) * 5)").add("marginBottom", "calc(var(--t-spacing) * 5)").add(
      "marginRight",
      "calc(var(--t-spacing) * 5)",
    ).add("marginLeft", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 6)"; marginBottom: "calc(var(--t-spacing) * 6)"; marginRight: "calc(var(--t-spacing) * 6)"; marginLeft: "calc(var(--t-spacing) * 6)"`. */
  get m6() {
    return this.add("marginTop", "calc(var(--t-spacing) * 6)").add("marginBottom", "calc(var(--t-spacing) * 6)").add(
      "marginRight",
      "calc(var(--t-spacing) * 6)",
    ).add("marginLeft", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `marginTop: "calc(var(--t-spacing) * 7)"; marginBottom: "calc(var(--t-spacing) * 7)"; marginRight: "calc(var(--t-spacing) * 7)"; marginLeft: "calc(var(--t-spacing) * 7)"`. */
  get m7() {
    return this.add("marginTop", "calc(var(--t-spacing) * 7)").add("marginBottom", "calc(var(--t-spacing) * 7)").add(
      "marginRight",
      "calc(var(--t-spacing) * 7)",
    ).add("marginLeft", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `marginTop: "auto"; marginBottom: "auto"; marginRight: "auto"; marginLeft: "auto"`. */
  get ma() {
    return this.add("marginTop", "auto").add("marginBottom", "auto").add("marginRight", "auto").add(
      "marginLeft",
      "auto",
    );
  }
  /** Sets `marginTop: "v"; marginBottom: "v"; marginRight: "v"; marginLeft: "v"`. */
  m(v: number | string) {
    return this.add("marginTop", maybeInc(v)).add("marginBottom", maybeInc(v)).add("marginRight", maybeInc(v)).add(
      "marginLeft",
      maybeInc(v),
    );
  }
  /** Sets `marginTop: px; marginBottom: px; marginRight: px; marginLeft: px`. */
  mPx(px: number) {
    return this.add("marginTop", `${px}px`).add("marginBottom", `${px}px`).add("marginRight", `${px}px`).add(
      "marginLeft",
      `${px}px`,
    );
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 0)"`. */
  get pt0() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 1)"`. */
  get pt1() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 2)"`. */
  get pt2() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 3)"`. */
  get pt3() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 4)"`. */
  get pt4() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 5)"`. */
  get pt5() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 6)"`. */
  get pt6() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 7)"`. */
  get pt7() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `paddingTop: "v"`. */
  pt(v: number | string) {
    return this.add("paddingTop", maybeInc(v));
  }
  /** Sets `paddingTop: px`. */
  ptPx(px: number) {
    return this.add("paddingTop", `${px}px`);
  }
  /** Sets `paddingRight: "calc(var(--t-spacing) * 0)"`. */
  get pr0() {
    return this.add("paddingRight", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `paddingRight: "calc(var(--t-spacing) * 1)"`. */
  get pr1() {
    return this.add("paddingRight", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `paddingRight: "calc(var(--t-spacing) * 2)"`. */
  get pr2() {
    return this.add("paddingRight", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `paddingRight: "calc(var(--t-spacing) * 3)"`. */
  get pr3() {
    return this.add("paddingRight", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `paddingRight: "calc(var(--t-spacing) * 4)"`. */
  get pr4() {
    return this.add("paddingRight", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `paddingRight: "calc(var(--t-spacing) * 5)"`. */
  get pr5() {
    return this.add("paddingRight", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `paddingRight: "calc(var(--t-spacing) * 6)"`. */
  get pr6() {
    return this.add("paddingRight", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `paddingRight: "calc(var(--t-spacing) * 7)"`. */
  get pr7() {
    return this.add("paddingRight", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `paddingRight: "v"`. */
  pr(v: number | string) {
    return this.add("paddingRight", maybeInc(v));
  }
  /** Sets `paddingRight: px`. */
  prPx(px: number) {
    return this.add("paddingRight", `${px}px`);
  }
  /** Sets `paddingBottom: "calc(var(--t-spacing) * 0)"`. */
  get pb0() {
    return this.add("paddingBottom", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `paddingBottom: "calc(var(--t-spacing) * 1)"`. */
  get pb1() {
    return this.add("paddingBottom", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `paddingBottom: "calc(var(--t-spacing) * 2)"`. */
  get pb2() {
    return this.add("paddingBottom", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `paddingBottom: "calc(var(--t-spacing) * 3)"`. */
  get pb3() {
    return this.add("paddingBottom", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `paddingBottom: "calc(var(--t-spacing) * 4)"`. */
  get pb4() {
    return this.add("paddingBottom", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `paddingBottom: "calc(var(--t-spacing) * 5)"`. */
  get pb5() {
    return this.add("paddingBottom", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `paddingBottom: "calc(var(--t-spacing) * 6)"`. */
  get pb6() {
    return this.add("paddingBottom", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `paddingBottom: "calc(var(--t-spacing) * 7)"`. */
  get pb7() {
    return this.add("paddingBottom", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `paddingBottom: "v"`. */
  pb(v: number | string) {
    return this.add("paddingBottom", maybeInc(v));
  }
  /** Sets `paddingBottom: px`. */
  pbPx(px: number) {
    return this.add("paddingBottom", `${px}px`);
  }
  /** Sets `paddingLeft: "calc(var(--t-spacing) * 0)"`. */
  get pl0() {
    return this.add("paddingLeft", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `paddingLeft: "calc(var(--t-spacing) * 1)"`. */
  get pl1() {
    return this.add("paddingLeft", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `paddingLeft: "calc(var(--t-spacing) * 2)"`. */
  get pl2() {
    return this.add("paddingLeft", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `paddingLeft: "calc(var(--t-spacing) * 3)"`. */
  get pl3() {
    return this.add("paddingLeft", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `paddingLeft: "calc(var(--t-spacing) * 4)"`. */
  get pl4() {
    return this.add("paddingLeft", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `paddingLeft: "calc(var(--t-spacing) * 5)"`. */
  get pl5() {
    return this.add("paddingLeft", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `paddingLeft: "calc(var(--t-spacing) * 6)"`. */
  get pl6() {
    return this.add("paddingLeft", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `paddingLeft: "calc(var(--t-spacing) * 7)"`. */
  get pl7() {
    return this.add("paddingLeft", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `paddingLeft: "v"`. */
  pl(v: number | string) {
    return this.add("paddingLeft", maybeInc(v));
  }
  /** Sets `paddingLeft: px`. */
  plPx(px: number) {
    return this.add("paddingLeft", `${px}px`);
  }
  /** Sets `paddingLeft: "calc(var(--t-spacing) * 0)"; paddingRight: "calc(var(--t-spacing) * 0)"`. */
  get px0() {
    return this.add("paddingLeft", "calc(var(--t-spacing) * 0)").add("paddingRight", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `paddingLeft: "calc(var(--t-spacing) * 1)"; paddingRight: "calc(var(--t-spacing) * 1)"`. */
  get px1() {
    return this.add("paddingLeft", "calc(var(--t-spacing) * 1)").add("paddingRight", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `paddingLeft: "calc(var(--t-spacing) * 2)"; paddingRight: "calc(var(--t-spacing) * 2)"`. */
  get px2() {
    return this.add("paddingLeft", "calc(var(--t-spacing) * 2)").add("paddingRight", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `paddingLeft: "calc(var(--t-spacing) * 3)"; paddingRight: "calc(var(--t-spacing) * 3)"`. */
  get px3() {
    return this.add("paddingLeft", "calc(var(--t-spacing) * 3)").add("paddingRight", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `paddingLeft: "calc(var(--t-spacing) * 4)"; paddingRight: "calc(var(--t-spacing) * 4)"`. */
  get px4() {
    return this.add("paddingLeft", "calc(var(--t-spacing) * 4)").add("paddingRight", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `paddingLeft: "calc(var(--t-spacing) * 5)"; paddingRight: "calc(var(--t-spacing) * 5)"`. */
  get px5() {
    return this.add("paddingLeft", "calc(var(--t-spacing) * 5)").add("paddingRight", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `paddingLeft: "calc(var(--t-spacing) * 6)"; paddingRight: "calc(var(--t-spacing) * 6)"`. */
  get px6() {
    return this.add("paddingLeft", "calc(var(--t-spacing) * 6)").add("paddingRight", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `paddingLeft: "calc(var(--t-spacing) * 7)"; paddingRight: "calc(var(--t-spacing) * 7)"`. */
  get px7() {
    return this.add("paddingLeft", "calc(var(--t-spacing) * 7)").add("paddingRight", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `paddingLeft: "v"; paddingRight: "v"`. */
  px(v: number | string) {
    return this.add("paddingLeft", maybeInc(v)).add("paddingRight", maybeInc(v));
  }
  /** Sets `paddingLeft: px; paddingRight: px`. */
  pxPx(px: number) {
    return this.add("paddingLeft", `${px}px`).add("paddingRight", `${px}px`);
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 0)"; paddingBottom: "calc(var(--t-spacing) * 0)"`. */
  get py0() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 0)").add("paddingBottom", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 1)"; paddingBottom: "calc(var(--t-spacing) * 1)"`. */
  get py1() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 1)").add("paddingBottom", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 2)"; paddingBottom: "calc(var(--t-spacing) * 2)"`. */
  get py2() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 2)").add("paddingBottom", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 3)"; paddingBottom: "calc(var(--t-spacing) * 3)"`. */
  get py3() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 3)").add("paddingBottom", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 4)"; paddingBottom: "calc(var(--t-spacing) * 4)"`. */
  get py4() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 4)").add("paddingBottom", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 5)"; paddingBottom: "calc(var(--t-spacing) * 5)"`. */
  get py5() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 5)").add("paddingBottom", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 6)"; paddingBottom: "calc(var(--t-spacing) * 6)"`. */
  get py6() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 6)").add("paddingBottom", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 7)"; paddingBottom: "calc(var(--t-spacing) * 7)"`. */
  get py7() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 7)").add("paddingBottom", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `paddingTop: "v"; paddingBottom: "v"`. */
  py(v: number | string) {
    return this.add("paddingTop", maybeInc(v)).add("paddingBottom", maybeInc(v));
  }
  /** Sets `paddingTop: px; paddingBottom: px`. */
  pyPx(px: number) {
    return this.add("paddingTop", `${px}px`).add("paddingBottom", `${px}px`);
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 0)"; paddingBottom: "calc(var(--t-spacing) * 0)"; paddingRight: "calc(var(--t-spacing) * 0)"; paddingLeft: "calc(var(--t-spacing) * 0)"`. */
  get p0() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 0)").add("paddingBottom", "calc(var(--t-spacing) * 0)").add(
      "paddingRight",
      "calc(var(--t-spacing) * 0)",
    ).add("paddingLeft", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 1)"; paddingBottom: "calc(var(--t-spacing) * 1)"; paddingRight: "calc(var(--t-spacing) * 1)"; paddingLeft: "calc(var(--t-spacing) * 1)"`. */
  get p1() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 1)").add("paddingBottom", "calc(var(--t-spacing) * 1)").add(
      "paddingRight",
      "calc(var(--t-spacing) * 1)",
    ).add("paddingLeft", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 2)"; paddingBottom: "calc(var(--t-spacing) * 2)"; paddingRight: "calc(var(--t-spacing) * 2)"; paddingLeft: "calc(var(--t-spacing) * 2)"`. */
  get p2() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 2)").add("paddingBottom", "calc(var(--t-spacing) * 2)").add(
      "paddingRight",
      "calc(var(--t-spacing) * 2)",
    ).add("paddingLeft", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 3)"; paddingBottom: "calc(var(--t-spacing) * 3)"; paddingRight: "calc(var(--t-spacing) * 3)"; paddingLeft: "calc(var(--t-spacing) * 3)"`. */
  get p3() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 3)").add("paddingBottom", "calc(var(--t-spacing) * 3)").add(
      "paddingRight",
      "calc(var(--t-spacing) * 3)",
    ).add("paddingLeft", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 4)"; paddingBottom: "calc(var(--t-spacing) * 4)"; paddingRight: "calc(var(--t-spacing) * 4)"; paddingLeft: "calc(var(--t-spacing) * 4)"`. */
  get p4() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 4)").add("paddingBottom", "calc(var(--t-spacing) * 4)").add(
      "paddingRight",
      "calc(var(--t-spacing) * 4)",
    ).add("paddingLeft", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 5)"; paddingBottom: "calc(var(--t-spacing) * 5)"; paddingRight: "calc(var(--t-spacing) * 5)"; paddingLeft: "calc(var(--t-spacing) * 5)"`. */
  get p5() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 5)").add("paddingBottom", "calc(var(--t-spacing) * 5)").add(
      "paddingRight",
      "calc(var(--t-spacing) * 5)",
    ).add("paddingLeft", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 6)"; paddingBottom: "calc(var(--t-spacing) * 6)"; paddingRight: "calc(var(--t-spacing) * 6)"; paddingLeft: "calc(var(--t-spacing) * 6)"`. */
  get p6() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 6)").add("paddingBottom", "calc(var(--t-spacing) * 6)").add(
      "paddingRight",
      "calc(var(--t-spacing) * 6)",
    ).add("paddingLeft", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `paddingTop: "calc(var(--t-spacing) * 7)"; paddingBottom: "calc(var(--t-spacing) * 7)"; paddingRight: "calc(var(--t-spacing) * 7)"; paddingLeft: "calc(var(--t-spacing) * 7)"`. */
  get p7() {
    return this.add("paddingTop", "calc(var(--t-spacing) * 7)").add("paddingBottom", "calc(var(--t-spacing) * 7)").add(
      "paddingRight",
      "calc(var(--t-spacing) * 7)",
    ).add("paddingLeft", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `paddingTop: "v"; paddingBottom: "v"; paddingRight: "v"; paddingLeft: "v"`. */
  p(v: number | string) {
    return this.add("paddingTop", maybeInc(v)).add("paddingBottom", maybeInc(v)).add("paddingRight", maybeInc(v)).add(
      "paddingLeft",
      maybeInc(v),
    );
  }
  /** Sets `paddingTop: px; paddingBottom: px; paddingRight: px; paddingLeft: px`. */
  pPx(px: number) {
    return this.add("paddingTop", `${px}px`).add("paddingBottom", `${px}px`).add("paddingRight", `${px}px`).add(
      "paddingLeft",
      `${px}px`,
    );
  }

  // textAlign
  /** Sets `textAlign: "left"`. */
  get tal() {
    return this.add("textAlign", "left");
  }
  /** Sets `textAlign: "center"`. */
  get tac() {
    return this.add("textAlign", "center");
  }
  /** Sets `textAlign: "right"`. */
  get tar() {
    return this.add("textAlign", "right");
  }
  /** Sets `textAlign: "justify"`. */
  get taj() {
    return this.add("textAlign", "justify");
  }
  /** Sets `textAlign: value`. */
  ta(value: Properties["textAlign"]) {
    return this.add("textAlign", value);
  }

  // textDecoration
  /** Sets `textDecoration: "none"`. */
  get tdn() {
    return this.add("textDecoration", "none");
  }
  /** Sets `textDecoration: "line-through"`. */
  get tdlt() {
    return this.add("textDecoration", "line-through");
  }
  /** Sets `textDecoration: "underline"`. */
  get tdu() {
    return this.add("textDecoration", "underline");
  }
  /** Sets `textDecoration: value`. */
  textDecoration(value: Properties["textDecoration"]) {
    return this.add("textDecoration", value);
  }

  // textTransform
  /** Sets `textTransform: "capitalize"`. */
  get ttc() {
    return this.add("textTransform", "capitalize");
  }
  /** Sets `textTransform: "lowercase"`. */
  get ttl() {
    return this.add("textTransform", "lowercase");
  }
  /** Sets `textTransform: "uppercase"`. */
  get ttu() {
    return this.add("textTransform", "uppercase");
  }
  /** Sets `textTransform: "none"`. */
  get ttn() {
    return this.add("textTransform", "none");
  }
  /** Sets `textTransform: value`. */
  tt(value: Properties["textTransform"]) {
    return this.add("textTransform", value);
  }

  // typeScale
  /** Sets `fontSize: "10px"`. */
  get f10() {
    return this.add("fontSize", "10px");
  }
  /** Sets `fontSize: "12px"`. */
  get f12() {
    return this.add("fontSize", "12px");
  }
  /** Sets `fontSize: "14px"`. */
  get f14() {
    return this.add("fontSize", "14px");
  }
  /** Sets `fontSize: "24px"`. */
  get f24() {
    return this.add("fontSize", "24px");
  }
  /** Sets `fontWeight: 400; fontSize: "10px"; lineHeight: "14px"`. */
  get tiny() {
    return this.add("fontWeight", 400).add("fontSize", "10px").add("lineHeight", "14px");
  }

  // typography
  /** Sets `maxWidth: "30em"`. */
  get measure() {
    return this.add("maxWidth", "30em");
  }
  /** Sets `maxWidth: "34em"`. */
  get measureWide() {
    return this.add("maxWidth", "34em");
  }
  /** Sets `maxWidth: "20em"`. */
  get measureNarrow() {
    return this.add("maxWidth", "20em");
  }
  /** Sets `textIndent: "1em"; marginTop: "0px"; marginBottom: "0px"`. */
  get indent() {
    return this.add("textIndent", "1em").add("marginTop", "0px").add("marginBottom", "0px");
  }
  /** Sets `fontVariant: "small-caps"`. */
  get smallCaps() {
    return this.add("fontVariant", "small-caps");
  }
  /** Sets `whiteSpace: "nowrap"; overflow: "hidden"; textOverflow: "ellipsis"`. */
  get truncate() {
    return this.add("whiteSpace", "nowrap").add("overflow", "hidden").add("textOverflow", "ellipsis");
  }
  /** Sets `fontSize: value`. */
  fs(value: Properties["fontSize"]) {
    return this.add("fontSize", value);
  }
  /** Sets `fontSize: px`. */
  fsPx(px: number) {
    return this.fs(`${px}px`);
  }
  /** Sets `lineHeight: value`. */
  lh(value: Properties["lineHeight"]) {
    return this.add("lineHeight", value);
  }
  /** Sets `lineHeight: px`. */
  lhPx(px: number) {
    return this.lh(`${px}px`);
  }

  // userSelect
  /** Sets `userSelect: "none"`. */
  get usn() {
    return this.add("userSelect", "none");
  }
  /** Sets `userSelect: "text"`. */
  get ust() {
    return this.add("userSelect", "text");
  }
  /** Sets `userSelect: "all"`. */
  get usAll() {
    return this.add("userSelect", "all");
  }
  /** Sets `userSelect: "auto"`. */
  get usAuto() {
    return this.add("userSelect", "auto");
  }
  /** Sets `userSelect: value`. */
  select(value: Properties["userSelect"]) {
    return this.add("userSelect", value);
  }

  // verticalAlign
  /** Sets `verticalAlign: "baseline"`. */
  get vaBaseline() {
    return this.add("verticalAlign", "baseline");
  }
  /** Sets `verticalAlign: "middle"`. */
  get vam() {
    return this.add("verticalAlign", "middle");
  }
  /** Sets `verticalAlign: "top"`. */
  get vat() {
    return this.add("verticalAlign", "top");
  }
  /** Sets `verticalAlign: "bottom"`. */
  get vaBottom() {
    return this.add("verticalAlign", "bottom");
  }
  /** Sets `verticalAlign: value`. */
  va(value: Properties["verticalAlign"]) {
    return this.add("verticalAlign", value);
  }

  // visibility
  /** Sets `visibility: "visible"`. */
  get vv() {
    return this.add("visibility", "visible");
  }
  /** Sets `visibility: "hidden"`. */
  get vh() {
    return this.add("visibility", "hidden");
  }
  /** Sets `visibility: value`. */
  visibility(value: Properties["visibility"]) {
    return this.add("visibility", value);
  }

  // whitespace
  /** Sets `whiteSpace: "pre"`. */
  get wsp() {
    return this.add("whiteSpace", "pre");
  }
  /** Sets `whiteSpace: "normal"`. */
  get wsn() {
    return this.add("whiteSpace", "normal");
  }
  /** Sets `whiteSpace: "nowrap"`. */
  get wsnw() {
    return this.add("whiteSpace", "nowrap");
  }
  /** Sets `whiteSpace: "break-spaces"`. */
  get wsbs() {
    return this.add("whiteSpace", "break-spaces");
  }
  /** Sets `whiteSpace: "pre-wrap"`. */
  get wspw() {
    return this.add("whiteSpace", "pre-wrap");
  }
  /** Sets `whiteSpace: "pre-line"`. */
  get wspl() {
    return this.add("whiteSpace", "pre-line");
  }
  /** Sets `whiteSpace: value`. */
  whiteSpace(value: Properties["whiteSpace"]) {
    return this.add("whiteSpace", value);
  }

  // width
  /** Sets `width: "25%"`. */
  get w25() {
    return this.add("width", "25%");
  }
  /** Sets `width: "50%"`. */
  get w50() {
    return this.add("width", "50%");
  }
  /** Sets `width: "75%"`. */
  get w75() {
    return this.add("width", "75%");
  }
  /** Sets `width: "100%"`. */
  get w100() {
    return this.add("width", "100%");
  }
  /** Sets `width: "fit-content"`. */
  get wfc() {
    return this.add("width", "fit-content");
  }
  /** Sets `width: "max-content"`. */
  get wmaxc() {
    return this.add("width", "max-content");
  }
  /** Sets `width: "min-content"`. */
  get wminc() {
    return this.add("width", "min-content");
  }
  /** Sets `minWidth: 0`. */
  get mw0() {
    return this.add("minWidth", 0);
  }
  /** Sets `minWidth: "25%"`. */
  get mw25() {
    return this.add("minWidth", "25%");
  }
  /** Sets `minWidth: "50%"`. */
  get mw50() {
    return this.add("minWidth", "50%");
  }
  /** Sets `minWidth: "75%"`. */
  get mw75() {
    return this.add("minWidth", "75%");
  }
  /** Sets `minWidth: "100%"`. */
  get mw100() {
    return this.add("minWidth", "100%");
  }
  /** Sets `minWidth: "fit-content"`. */
  get mwfc() {
    return this.add("minWidth", "fit-content");
  }
  /** Sets `minWidth: "min-content"`. */
  get mwminc() {
    return this.add("minWidth", "min-content");
  }
  /** Sets `minWidth: "max-content"`. */
  get mwmaxc() {
    return this.add("minWidth", "max-content");
  }
  /** Sets `minWidth: value`. */
  mw(value: Properties["minWidth"]) {
    return this.add("minWidth", value);
  }
  /** Sets `minWidth: px`. */
  mwPx(px: number) {
    return this.mw(`${px}px`);
  }
  /** Sets `maxWidth: "0"`. */
  get maxw0() {
    return this.add("maxWidth", "0");
  }
  /** Sets `maxWidth: "25%"`. */
  get maxw25() {
    return this.add("maxWidth", "25%");
  }
  /** Sets `maxWidth: "50%"`. */
  get maxw50() {
    return this.add("maxWidth", "50%");
  }
  /** Sets `maxWidth: "75%"`. */
  get maxw75() {
    return this.add("maxWidth", "75%");
  }
  /** Sets `maxWidth: "100%"`. */
  get maxw100() {
    return this.add("maxWidth", "100%");
  }
  /** Sets `maxWidth: "fit-content"`. */
  get maxwfc() {
    return this.add("maxWidth", "fit-content");
  }
  /** Sets `maxWidth: "min-content"`. */
  get maxwminc() {
    return this.add("maxWidth", "min-content");
  }
  /** Sets `maxWidth: "max-content"`. */
  get maxwmaxc() {
    return this.add("maxWidth", "max-content");
  }
  /** Sets `maxWidth: value`. */
  maxw(value: Properties["maxWidth"]) {
    return this.add("maxWidth", value);
  }
  /** Sets `maxWidth: px`. */
  maxwPx(px: number) {
    return this.maxw(`${px}px`);
  }
  /** Sets `width: "calc(var(--t-spacing) * 0)"`. */
  get w0() {
    return this.add("width", "calc(var(--t-spacing) * 0)");
  }
  /** Sets `width: "calc(var(--t-spacing) * 1)"`. */
  get w1() {
    return this.add("width", "calc(var(--t-spacing) * 1)");
  }
  /** Sets `width: "calc(var(--t-spacing) * 2)"`. */
  get w2() {
    return this.add("width", "calc(var(--t-spacing) * 2)");
  }
  /** Sets `width: "calc(var(--t-spacing) * 3)"`. */
  get w3() {
    return this.add("width", "calc(var(--t-spacing) * 3)");
  }
  /** Sets `width: "calc(var(--t-spacing) * 4)"`. */
  get w4() {
    return this.add("width", "calc(var(--t-spacing) * 4)");
  }
  /** Sets `width: "calc(var(--t-spacing) * 5)"`. */
  get w5() {
    return this.add("width", "calc(var(--t-spacing) * 5)");
  }
  /** Sets `width: "calc(var(--t-spacing) * 6)"`. */
  get w6() {
    return this.add("width", "calc(var(--t-spacing) * 6)");
  }
  /** Sets `width: "calc(var(--t-spacing) * 7)"`. */
  get w7() {
    return this.add("width", "calc(var(--t-spacing) * 7)");
  }
  /** Sets `width: "auto"`. */
  get wa() {
    return this.add("width", "auto");
  }
  /** Sets `width: "v"`. */
  w(v: number | string) {
    return this.add("width", maybeInc(v));
  }
  /** Sets `width: px`. */
  wPx(px: number) {
    return this.add("width", `${px}px`);
  }

  // wordBreak
  /** Sets `wordBreak: "normal"`. */
  get wbn() {
    return this.add("wordBreak", "normal");
  }
  /** Sets `wordBreak: "break-all"`. */
  get wbba() {
    return this.add("wordBreak", "break-all");
  }
  /** Sets `wordBreak: "keep-all"`. */
  get wbka() {
    return this.add("wordBreak", "keep-all");
  }
  /** Sets `wordBreak: "break-word"`. */
  get wbbw() {
    return this.add("wordBreak", "break-word");
  }
  /** Sets `wordBreak: value`. */
  wordBreak(value: Properties["wordBreak"]) {
    return this.add("wordBreak", value);
  }

  // zIndex
  /** Sets `zIndex: 0`. */
  get z0() {
    return this.add("zIndex", 0);
  }
  /** Sets `zIndex: 1`. */
  get z1() {
    return this.add("zIndex", 1);
  }
  /** Sets `zIndex: 2`. */
  get z2() {
    return this.add("zIndex", 2);
  }
  /** Sets `zIndex: 3`. */
  get z3() {
    return this.add("zIndex", 3);
  }
  /** Sets `zIndex: 4`. */
  get z4() {
    return this.add("zIndex", 4);
  }
  /** Sets `zIndex: 5`. */
  get z5() {
    return this.add("zIndex", 5);
  }
  /** Sets `zIndex: 999`. */
  get z999() {
    return this.add("zIndex", 999);
  }
  /** Sets `zIndex: 9999`. */
  get z9999() {
    return this.add("zIndex", 9999);
  }
  /** Sets `zIndex: "inherit"`. */
  get zInherit() {
    return this.add("zIndex", "inherit");
  }
  /** Sets `zIndex: "initial"`. */
  get zInitial() {
    return this.add("zIndex", "initial");
  }
  /** Sets `zIndex: "unset"`. */
  get zUnset() {
    return this.add("zIndex", "unset");
  }
  /** Sets `zIndex: value`. */
  z(value: Properties["zIndex"]) {
    return this.add("zIndex", value);
  }

  // customStuff
  /** Sets `color: "#000000"`. */
  get foo() {
    return this.add("color", "#000000");
  }

  // aliases
  get bodyText() {
    return this.f14.black;
  }

  get $(): T & { readonly __kind: S } {
    if (this.opts.runtimeError) {
      throw new Error(this.opts.runtimeError);
    }
    if (this.selector !== undefined) {
      throw new Error("Selector-based Css helpers cannot be used in RuntimeStyle css expressions.");
    }
    return this.rules as any;
  }

  get onHover() {
    return this.newCss({ selector: ":hover" });
  }
  get onFocus() {
    return this.newCss({ selector: ":focus" });
  }
  get onFocusVisible() {
    return this.newCss({ selector: ":focus-visible" });
  }
  get onFocusWithin() {
    return this.newCss({ selector: ":focus-within" });
  }
  get onActive() {
    return this.newCss({ selector: ":active" });
  }
  get onDisabled() {
    return this.newCss({ selector: ":disabled" });
  }
  get ifFirstOfType() {
    return this.newCss({ selector: ":first-of-type" });
  }
  get ifLastOfType() {
    return this.newCss({ selector: ":last-of-type" });
  }

  /** Marks this element as a default hover marker (for ancestor pseudo selectors). */
  get marker(): CssBuilder<T, S> {
    return this.unsupportedRuntime("marker cannot be used in RuntimeStyle css expressions.");
  }

  /** Marks this element with a user-defined marker. */
  markerOf(_marker: Marker): CssBuilder<T, S> {
    return this.unsupportedRuntime("markerOf() cannot be used in RuntimeStyle css expressions.");
  }

  /** Creates a marker token for use with markerOf() and when(). */
  newMarker(): Marker {
    return Symbol("truss-marker");
  }

  typography(key: Typography): CssBuilder<T, S> {
    return (this as any)[key];
  }

  /**
   * Styles after this `when` are applied on the current element for a static selector.
   *
   * `when(":hover")` — same semantics as `onHover`
   * `when(":hover:not(:disabled)")` — hover only while enabled
   * `when('[data-state="open"]')` — match an element state attribute
   */
  when(selector: string): CssBuilder<T, S>;
  /**
   * Styles after this `when` are applied based on a marker relationship + pseudo selector.
   *
   * `when(marker, "ancestor", ":hover")` — react to marker ancestor hover
   * `when(row, "descendant", ":focus")` — react to a marked descendant focus
   */
  when(
    marker: Marker,
    relationship: "ancestor" | "descendant" | "anySibling" | "siblingBefore" | "siblingAfter",
    pseudo: string,
  ): CssBuilder<T, S>;
  /**
   * Apply different styles for each selector in the object.
   *
   * `when({ ":hover": Css.blue.$, '[data-state="open"]': Css.red.$ })`
   */
  when<W extends Record<string, Properties>>(selectors: W): CssBuilder<T & UnionToIntersection<W[keyof W]>, S>;
  when(
    _selectorOrMarker: string | Marker | Record<string, Properties>,
    _relationship?: string,
    _pseudo?: string,
  ): CssBuilder<T, S> {
    return this.unsupportedRuntime("when() cannot be used in RuntimeStyle css expressions.");
  }

  ifContainer(_props: { name?: string; lt?: number; gt?: number }) {
    return this.unsupportedRuntime("ifContainer() cannot be used in RuntimeStyle css expressions.");
  }

  /** Apply styles within a pseudo-element (e.g. `"::placeholder"`, `"::selection"`). */
  element(_pseudoElement: string): CssBuilder<T, S> {
    return this.unsupportedRuntime("element() cannot be used in RuntimeStyle css expressions.");
  }

  get ifPrint() {
    return this.newCss({ selector: "@media print" });
  }
  get ifSm() {
    return this.newCss({ selector: "@media screen and (max-width: 599px)" });
  }
  get ifMd() {
    return this.newCss({ selector: "@media screen and (min-width: 600px) and (max-width: 959px)" });
  }
  get ifSmOrMd() {
    return this.newCss({ selector: "@media screen and (max-width: 959px)" });
  }
  get ifMdAndUp() {
    return this.newCss({ selector: "@media screen and (min-width: 600px)" });
  }
  get ifMdAndDown() {
    return this.newCss({ selector: "@media screen and (max-width: 959px)" });
  }
  get ifLg() {
    return this.newCss({ selector: "@media screen and (min-width: 960px)" });
  }
  get ifMdOrLg() {
    return this.newCss({ selector: "@media screen and (min-width: 600px)" });
  }

  /** Conditionally apply styles when `cond` is true. */
  if(cond: boolean): CssBuilder<T, S>;
  /** Apply styles within a media query (e.g. `Breakpoints.sm` or a raw `@media` string). */
  if(mediaQuery: string): CssBuilder<T, S>;
  if(condOrMediaQuery: boolean | string): CssBuilder<T, S> {
    if (typeof condOrMediaQuery === "boolean") {
      return new CssBuilder({ ...this.opts, enabled: condOrMediaQuery, elseApplied: false }) as CssBuilder<T, S>;
    }
    return this.unsupportedRuntime("if(mediaQuery) cannot be used in RuntimeStyle css expressions.");
  }

  get else(): CssBuilder<T, S> {
    if (this.selector !== undefined) {
      if (this.opts.elseApplied) {
        throw new Error("else was already called");
      }
      return this.newCss({ selector: __invertTrussMediaQuery(this.selector), elseApplied: true });
    }
    if (this.opts.elseApplied) {
      throw new Error("else was already called");
    }
    return new CssBuilder({ ...this.opts, enabled: !this.enabled, elseApplied: true }) as CssBuilder<T, S>;
  }

  /** Reset active conditional modifiers for subsequent styles. */
  get end(): CssBuilder<T, S> {
    return this.newCss({ selector: undefined, elseApplied: false });
  }

  /** Add real CSS property/value pairs, either as add("prop", value) or add({ prop: value, ... }). */
  add<P extends Properties>(props: P): CssBuilder<T & P, S>;
  add<K extends keyof Properties>(prop: K, value: Properties[K]): CssBuilder<T & { [U in K]: Properties[K] }, S>;
  add<K extends keyof Properties>(propOrStyles: K | Properties, value?: Properties[K]): CssBuilder<any, S> {
    if (!this.enabled) {
      return this;
    }

    const newRules = typeof propOrStyles === "string" ? { [propOrStyles]: value } : propOrStyles;
    if (typeof propOrStyles !== "string" && (newRules as any).$css) {
      throw new Error("add() received a Css expression — use with() to compose Css expressions");
    }
    const rules = this.selector
      ? { ...this.rules, [this.selector]: { ...(this.rules as any)[this.selector], ...newRules } }
      : { ...this.rules, ...newRules };
    return this.newCss({ rules: rules as any });
  }

  /** Compose an existing Css expression or partial style hash into this builder, skipping undefined values. */
  with<P extends Properties>(cssProp: P): CssBuilder<T & P, S>;
  with(cssProp: Properties): CssBuilder<any, S> {
    if (!this.enabled) {
      return this;
    }
    const { $css, ...rest } = cssProp as any;
    const filtered = omitUndefinedValues(rest);
    const rules = this.selector
      ? { ...this.rules, [this.selector]: { ...(this.rules as any)[this.selector], ...filtered } }
      : { ...this.rules, ...filtered };
    return this.newCss({ rules: rules as any });
  }

  /** Marker for the build-time transform to append a raw className. */
  className(className: string | undefined): CssBuilder<T, S> {
    void className;
    return this.unsupportedRuntime("className() cannot be used in RuntimeStyle css expressions.");
  }

  /** Marker for the build-time transform to append raw inline styles. */
  style(inlineStyle: InlineStyle): CssBuilder<T, S> {
    void inlineStyle;
    return this.unsupportedRuntime("style() cannot be used in RuntimeStyle css expressions.");
  }

  /** Set CSS custom properties via atomic classes (resolved at build time on web). */
  setVar(_values: Partial<Record<CssSetVarKeys, CssSetVarValue>>): CssBuilder<T, S> {
    void _values;
    return this.unsupportedRuntime("setVar() cannot be used in RuntimeStyle css expressions.");
  }

  /** Convert a style hash into `{ className, style }` props for manual spreading into non-`css=` contexts. */
  props(styles: Properties): Record<string, unknown> {
    return trussProps(styles as any);
  }

  /** Tagged template literal for raw CSS in .css.ts files; passes through the string as-is. */
  raw(strings: TemplateStringsArray, ...values: unknown[]): string {
    return String.raw(strings, ...values);
  }

  private get rules(): T {
    return this.opts.rules;
  }
  private get enabled(): boolean {
    return this.opts.enabled;
  }
  private get selector(): string | undefined {
    return this.opts.selector;
  }
  private unsupportedRuntime(message: string): CssBuilder<T, S> {
    return this.newCss({ runtimeError: message });
  }
  private newCss(opts: Partial<Opts<T>>): CssBuilder<T, S> {
    return new CssBuilder({ ...this.opts, ...opts }) as CssBuilder<T, S>;
  }
}

/** Converts `inc` into a spacing length using `--t-spacing` (build-time atomic CSS). */
export function maybeInc(inc: number | string): string {
  return typeof inc === "string" ? inc : `calc(var(--t-spacing) * ${inc})`;
}

/** Converts `inc` into pixels. */
export function increment(inc: number): number {
  return inc * 6;
}

/** Convert `pixels` to a `px` units string so it's not ambiguous. */
export function px(pixels: number): string {
  return `${pixels}px`;
}

function omitUndefinedValues<T extends object>(value: T): T {
  const entries = Object.entries(value).filter(([, entryValue]) => {
    return entryValue !== undefined;
  });
  return Object.fromEntries(entries) as T;
}

export enum Palette {
  Black = "#353535",
  MidGray = "#888888",
  LightGray = "#cecece",
  White = "#fcfcfa",
  Blue = "#526675",
  BlueFaded = "rgba(82, 102, 117, 0.3)",
  Hollow = "rgba(0, 0, 0, 0)",
}

/** A shortcut for defining Xss types. */
export type Xss<P extends keyof Properties> = Pick<Properties, P>;

/** The shared marker token for `when(marker, relationship, pseudo)`. */
export const marker: Marker = Symbol.for("truss-default-marker");

/** An entry point for build-time Css expressions. Use with `css=` props. */
export const Css = new CssBuilder<Pick<Properties, never>, "buildtime">({
  rules: {} as Pick<Properties, never>,
  enabled: true,
  selector: undefined,
  elseApplied: false,
  runtimeError: undefined,
});

/** An entry point for runtime Css expressions. Use with `useRuntimeStyle`. */
export const RuntimeCss = new CssBuilder<Pick<Properties, never>, "runtime">({
  rules: {} as Pick<Properties, never>,
  enabled: true,
  selector: undefined,
  elseApplied: false,
  runtimeError: undefined,
});

/** Hook that injects dynamic CSS at runtime. Only accepts `RuntimeCss.*.$` expressions. */
export function useRuntimeStyle(css: Record<string, RuntimeStyles | string>): void {
  _useRuntimeStyle(css as any);
}

export type Margin = "margin" | "marginTop" | "marginRight" | "marginBottom" | "marginLeft";

export type Padding = "padding" | "paddingTop" | "paddingRight" | "paddingBottom" | "paddingLeft";

export type Breakpoint = "print" | "sm" | "md" | "smOrMd" | "mdAndUp" | "mdAndDown" | "lg" | "mdOrLg";
export enum Breakpoints {
  print = "@media print",
  sm = "@media screen and (max-width: 599px)",
  md = "@media screen and (min-width: 600px) and (max-width: 959px)",
  smOrMd = "@media screen and (max-width: 959px)",
  mdAndUp = "@media screen and (min-width: 600px)",
  mdAndDown = "@media screen and (max-width: 959px)",
  lg = "@media screen and (min-width: 960px)",
  mdOrLg = "@media screen and (min-width: 600px)",
}
