import { Properties } from "csstype";
import { promises as fs } from "fs";
import { code, Code, def, imp } from "ts-poet";
import { makeBreakpoints } from "src/breakpoints";
import { Config, SectionName, Sections, UtilityMethod } from "src/config";
import { newAliasesMethods, startStylexCollection, stopStylexCollection, StylexEntry } from "src/methods";
import { defaultSections } from "src/sections/tachyons";
import { quote } from "src/utils";
import { pascalCase } from "change-case";
import { reactNativeSections } from "src/sections/tachyons-rn";

const CssProperties = imp("Properties@csstype");

export const defaultTypeAliases: Record<string, Array<keyof Properties>> = {
  Margin: ["margin", "marginTop", "marginRight", "marginBottom", "marginLeft"],
  Padding: ["padding", "paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
};

export async function generate(config: Config): Promise<void> {
  const { outputPath } = config;
  const target: string = config.target ?? "stylex";
  if (target === "stylex") {
    const { sections, entries } = collectStylexGenerationData(config);
    // For stylex target: generate a stylex-friendly CssBuilder (for types/IDE) + a mapping JSON
    const cssOutput = generateStylexCssBuilder(config, sections).toString();
    await fs.writeFile(outputPath, cssOutput);
    const mappingPath = config.mappingOutputPath || outputPath.replace(/\.ts$/, ".json");
    const mapping = generateTrussMapping(config, entries);
    await fs.writeFile(mappingPath, condensedJson(mapping) + "\n");
    return;
  }

  if (target === "react-native") {
    const output = generateCssBuilder(config).toString();
    await fs.writeFile(outputPath, output);
    return;
  }

  throw new Error(`Unsupported truss target "${target}". Use "stylex" (default) or "react-native".`);
}

function generateCssBuilder(config: Config): Code {
  const { fonts, increment, extras, typeAliases, breakpoints = {}, palette } = config;
  const sections = generateSections(config);

  const lines = Object.entries(sections)
    .map(([name, value]) => [`// ${name}`, ...value, ""])
    .flat();

  const typeAliasCode = Object.entries({
    ...defaultTypeAliases,
    ...typeAliases,
  }).map(([name, props]) => {
    return `export type ${name} = ${props.map(quote).join(" | ")};\n\n`;
  });

  const typographyType = code`
    export type ${def("Typography")} = ${Object.keys(fonts).map(quote).join(" | ")};
  `;

  const genBreakpoints = makeBreakpoints(breakpoints);

  const breakpointCode = [
    `export type Breakpoint = ${Object.keys(genBreakpoints).map(quote).join(" | ")};`,
    `export enum Breakpoints {
       ${Object.entries(genBreakpoints).map(([name, value]) => `${name} = "${value}"`)}
    };`,
  ];

  const breakpointIfs = Object.entries(genBreakpoints).map(([name, value]) => {
    return code`
      get if${pascalCase(name)}() {
        return this.newCss({ selector: ${quote(value)} });
      }`;
  });

  const containerQueriesCode = code`
    /**
     * Utility to help write \`@container\` queries
     *
     * @param name - The name of the container.
     * @param lt - The maximum width of the container inclusive.
     * @param gt - The minimum width of the container exclusive.
     */
    type ContainerProps = { name?: string } & ({ lt: number } | { gt: number } | { lt: number; gt: number });
    export function Container(props: ContainerProps) {
      const { name = "" } = props;
      const lt = "lt" in props ? props.lt : undefined;
      const gt = "gt" in props ? props.gt : undefined;

      const ltQuery = lt !== undefined ? \`(max-width: \${lt}px)\` : "";
      const gtQuery = gt !== undefined ? \`(min-width: \${gt + 1}px)\` : "";
      const query = [ltQuery, gtQuery].filter(Boolean).join(" and ");

      return \`@container \${name} \${query}\`;
    }`;

  return code`
// This file is auto-generated by truss: https://github.com/homebound-team/truss.
// See your project's \`truss-config.ts\` to make configuration changes (fonts, increments, etc).

/** Given a type X, and the user's proposed type T, only allow keys in X and nothing else. */
export type Only<X, T> = X & Record<Exclude<keyof T, keyof X>, never>;

export type ${def("Properties")} = ${CssProperties}<string | 0, string>;

export type ${def("InlineStyle")} = Record<string, string | number | undefined>;

${typographyType}

type Opts<T> = {
  rules: T,
  enabled: boolean,
  important: boolean,
  selector: string | undefined,
  elseApplied: boolean,
};

function invertMediaQuery(query: string): string {
  const screenPrefix = "@media screen and ";
  if (query.startsWith(screenPrefix)) {
    const conditions = query.slice(screenPrefix.length).trim();
    const rangeMatch = conditions.match(/^\(min-width: (\d+)px\) and \(max-width: (\d+)px\)$/);
    if (rangeMatch) {
      const min = Number(rangeMatch[1]);
      const max = Number(rangeMatch[2]);
      return \`@media screen and (max-width: \${min - 1}px), screen and (min-width: \${max + 1}px)\`;
    }
    const minMatch = conditions.match(/^\(min-width: (\d+)px\)$/);
    if (minMatch) {
      return \`@media screen and (max-width: \${Number(minMatch[1]) - 1}px)\`;
    }
    const maxMatch = conditions.match(/^\(max-width: (\d+)px\)$/);
    if (maxMatch) {
      return \`@media screen and (min-width: \${Number(maxMatch[1]) + 1}px)\`;
    }
  }
  return query.replace("@media", "@media not");
}

class CssBuilder<T extends Properties> {
  constructor(private opts: Opts<T>) {}

  private get rules(): T { return this.opts.rules };
  private get enabled(): boolean { return this.opts.enabled };
  private get selector(): string | undefined { return this.opts.selector };
  private newCss(opts: Partial<Opts<T>>): CssBuilder<T> {
    return new CssBuilder({ ...this.opts, ...opts });
  }

  ${lines.join("\n  ").replace(/ +\n/g, "\n")}
    
  get $(): T { return maybeImportant(sortObject(this.rules), this.opts.important); }

  if(bp: Breakpoint): CssBuilder<T>;
  if(cond: boolean): CssBuilder<T>;
  if(attr: string, value: boolean | string): CssBuilder<T>;
  if(arg: boolean | Breakpoint | string, value?: boolean | string): CssBuilder<T> {
    if (value !== undefined) {
      return this.newCss({ selector: \`[\${arg}='\${value}']\` });
    } else if (typeof arg === "boolean") {
      return this.newCss({ enabled: arg });
    } else {
      return this.newCss({ selector: Breakpoints[arg as Breakpoint] });
    }
  }

  get onHover() {
    return this.newCss({ selector: ":hover" });
  }

  get onFocusWithin() {
    return this.newCss({ selector: ":focus-within" });
  }

  get ifFirstOfType() {
    return this.newCss({ selector: ":first-of-type" });
  }

  get ifLastOfType() {
    return this.newCss({ selector: ":last-of-type" });
  }

  ifContainer(props: ContainerProps) {
    return this.newCss({ selector: Container(props) });
  }
  
  ${breakpointIfs}

  typography(key: Typography): CssBuilder<T> {
    return (this as any)[key];
  }

  get else() {
    if (this.selector !== undefined) {
      if (this.opts.elseApplied) {
        throw new Error("else was already called");
      } else {
        return this.newCss({ selector: invertMediaQuery(this.selector), elseApplied: true });
      }
    }
    return this.newCss({ enabled: !this.enabled, elseApplied: true });
  }

  /** Reset active conditional modifiers for subsequent styles. */
  get end() {
    return this.newCss({ selector: undefined, elseApplied: false });
  }

  get important() { return this.newCss({ important: true }); }

  /** Adds new properties, either a specific key/value or a Properties object, to the current css. */
  add<P extends Properties>(props: P): CssBuilder<T & P>;
  add<K extends keyof Properties>(prop: K, value: Properties[K]): CssBuilder<T & { [U in K]: Properties[K] }>;
  add<K extends keyof Properties>(propOrProperties: K | Properties, value?: Properties[K]): CssBuilder<any> {
    if (!this.enabled) return this;
    const newRules = typeof propOrProperties === "string" ?  { [propOrProperties]: value } : propOrProperties;
    const rules = this.selector
      ? { ...this.rules, [this.selector]: { ...(this.rules as any)[this.selector], ...newRules } }
      : { ...this.rules, ...newRules };
    return this.newCss({ rules: rules as any });
  }

  /** Adds a partial style hash, skipping any undefined values. */
  addCss<P extends Properties>(props: P): CssBuilder<T & P> {
    return this.add(omitUndefinedValues(props));
  }

  /** Adds new properties, either a specific key/value or a Properties object, to a nested selector. */
  addIn<P extends Properties>(selector: string, props: P | undefined): CssBuilder<T & P>;
  addIn<K extends keyof Properties>(selector: string, prop: K, value: Properties[K]): CssBuilder<T & { [U in K]: Properties[K] }>;
  addIn<K extends keyof Properties>(selector: string, propOrProperties: K | Properties, value?: Properties[K]): CssBuilder<any> {
    const newRules = typeof propOrProperties === "string" ?  { [propOrProperties]: value } : propOrProperties;
    if (!this.enabled) return this;
    if (newRules === undefined) {
      return this;
    }
    const rules = { ...this.rules, [selector]: { ...(this.rules as any)[selector], ...newRules } };
    return this.newCss({ rules: rules as any });
  }

  /** Marker for the build-time transform to append a raw className. */
  className(className: string): CssBuilder<T> {
    void className;
    return this;
  }

  /** Marker for the build-time transform to append raw inline styles. */
  style(inlineStyle: InlineStyle): CssBuilder<T> {
    void inlineStyle;
    return this;
  }

  /** Tagged template literal for raw CSS in .css.ts files; passes through the string as-is. */
  raw(strings: TemplateStringsArray, ...values: unknown[]): string {
    return String.raw(strings, ...values);
  }

}

/** Sort keys so equivalent rule objects have deterministic shape. */
function sortObject<T extends object>(obj: T): T {
  return Object.keys(obj)
    .sort()
    .reduce((acc, key) => {
      acc[key as keyof T] = obj[key as keyof T];
      return acc;
    }, ({} as any) as T) as T;
}

/** Conditionally adds \`important!\` to everything. */
function maybeImportant<T extends object>(obj: T, important: boolean): T {
  if (important) {
    Object.keys(obj).forEach(key => {
      (obj as any)[key] = \`\${(obj as any)[key]} !important\`;
    });
  }
  return obj;
}

/** Converts \`inc\` into pixels value with a \`px\` suffix. */
export function maybeInc(inc: number | string): string {
  return typeof inc === "string" ? inc : \`\${increment(inc)}px\`;
}

/** Converts \`inc\` into pixels. */
export function increment(inc: number): number {
  return inc * ${increment};
}

/** Convert \`pixels\` to a \`px\` units string so it's not ambiguous. */
export function px(pixels: number): string {
  return \`\${pixels}px\`;
}

function omitUndefinedValues<T extends object>(value: T): T {
  const entries = Object.entries(value).filter(([, entryValue]) => {
    return entryValue !== undefined;
  });
  return Object.fromEntries(entries) as T;
}

export enum Palette {
  ${Object.entries(palette).map(([name, value]) => {
    return `${name} = "${value}",`;
  })}
}

/** A shortcut for defining Xss types. */
export type Xss<P extends keyof Properties> = Pick<Properties, P>;

/** An entry point for Css expressions. CssBuilder is immutable so this is safe to share. */
export const Css = new CssBuilder({ rules: {}, enabled: true, important: false, selector: undefined, elseApplied: false });

${typeAliasCode}

${breakpointCode}

${containerQueriesCode}

${extras || ""}
  `;
}

/** Invokes all of the `MethodFns` to create actual `UtilityMethod`s. */
function generateMethods(config: Config, methodFns: Sections): Record<SectionName, UtilityMethod[]> {
  return Object.fromEntries(Object.entries(methodFns).map(([name, fn]) => [name, fn(config)]));
}

/** Returns all utility sections configured for this project. */
function generateSections(config: Config): Record<string, UtilityMethod[]> {
  const { aliases, defaultMethods = "tachyons", sections: customSections } = config;
  return {
    ...(defaultMethods === "tachyons"
      ? generateMethods(config, defaultSections)
      : defaultMethods === "tachyons-rn"
        ? generateMethods(config, reactNativeSections)
        : {}),
    ...(customSections ? generateMethods(config, customSections) : {}),
    ...(aliases && { aliases: newAliasesMethods(aliases) }),
  };
}

/** Runs section generation once with collection enabled for stylex outputs. */
function collectStylexGenerationData(config: Config): {
  sections: Record<string, UtilityMethod[]>;
  entries: StylexEntry[];
} {
  startStylexCollection();
  try {
    const sections = generateSections(config);
    const entries = stopStylexCollection();
    return { sections, entries };
  } catch (error) {
    stopStylexCollection();
    throw error;
  }
}

// ── StyleX Code Generator ─────────────────────────────────────────────

/**
 * For the "stylex" target, we generate a stylex-friendly CssBuilder whose public
 * TypeScript surface matches the runtime targets: `.$` is typed as the accumulated
 * style object shape, even though the build-time plugin later rewrites it to StyleX refs.
 *
 * The actual StyleX transformation happens at build time via the truss Vite plugin,
 * which reads the companion `Css.json` to understand what each abbreviation
 * produces, and rewrites `Css.*.$` into file-local `stylex.create()` + `stylex.props()` calls.
 */
function generateStylexCssBuilder(config: Config, sections: Record<string, UtilityMethod[]>): Code {
  const { fonts, increment, extras, typeAliases, palette, breakpoints = {} } = config;

  const lines = Object.entries(sections)
    .map(([name, value]) => [`// ${name}`, ...value, ""])
    .flat();

  const typeAliasCode = Object.entries({
    ...defaultTypeAliases,
    ...typeAliases,
  }).map(([name, props]) => {
    return `export type ${name} = ${props.map(quote).join(" | ")};\n\n`;
  });

  const genBreakpointsMap = makeBreakpoints(breakpoints);

  const breakpointIfs = Object.entries(genBreakpointsMap).map(([name, value]) => {
    return code`
      get if${pascalCase(name)}() {
        return this.newCss({ selector: ${quote(value)} });
      }`;
  });

  const breakpointCode = [
    `export type Breakpoint = ${Object.keys(genBreakpointsMap).map(quote).join(" | ")};`,
    `export enum Breakpoints {`,
    ...Object.entries(genBreakpointsMap).map(([name, value]) => `  ${name} = "${value}",`),
    `}`,
  ];

  const typographyType = code`
    export type ${def("Typography")} = ${Object.keys(fonts).map(quote).join(" | ")};
  `;

  return code`
// This file is auto-generated by truss: https://github.com/homebound-team/truss.
// See your project's \`truss-config.ts\` to make configuration changes (fonts, increments, etc).
// Target: native (build-time plugin)

import { trussProps } from "@homebound/truss/runtime";
export { RuntimeStyle, useRuntimeStyle } from "@homebound/truss/runtime";

/** Given a type X, and the user's proposed type T, only allow keys in X and nothing else. */
export type Only<X, T> = X & Record<Exclude<keyof T, keyof X>, never>;

export type ${def("Properties")} = ${CssProperties}<string | 0, string>;

export type ${def("InlineStyle")} = Record<string, string | number | undefined>;

/** A marker token used with \`when\`/\`markerOf\` etc. */
export type Marker = symbol;

${typographyType}

// Augment React types so all JSX elements accept the \`css\` prop:
// - HTMLAttributes/SVGAttributes cover intrinsic elements (div, svg, etc.)
// - JSX.IntrinsicAttributes covers custom components (Card, Page, etc.)
declare module "react" {
  interface HTMLAttributes<T> {
    css?: Properties;
  }
  interface SVGAttributes<T> {
    css?: Properties;
  }
  namespace JSX {
    interface IntrinsicAttributes {
      css?: Properties;
    }
  }
}

type Opts<T> = {
  rules: T;
  enabled: boolean;
  selector: string | undefined;
  elseApplied: boolean;
  runtimeError: string | undefined;
};

class CssBuilder<T extends Properties> {
  constructor(private opts: Opts<T>) {}

  ${lines.join("\n  ").replace(/ +\n/g, "\n")}

  get $(): T {
    if (this.opts.runtimeError) {
      throw new Error(this.opts.runtimeError);
    }
    if (this.selector !== undefined) {
      throw new Error("Selector-based Css helpers cannot be used in RuntimeStyle css expressions.");
    }
    return this.rules as any;
  }

  get onHover() {
    return this.newCss({ selector: ":hover" });
  }
  get onFocus() {
    return this.newCss({ selector: ":focus" });
  }
  get onFocusVisible() {
    return this.newCss({ selector: ":focus-visible" });
  }
  get onFocusWithin() {
    return this.newCss({ selector: ":focus-within" });
  }
  get onActive() {
    return this.newCss({ selector: ":active" });
  }
  get onDisabled() {
    return this.newCss({ selector: ":disabled" });
  }
  get ifFirstOfType() {
    return this.newCss({ selector: ":first-of-type" });
  }
  get ifLastOfType() {
    return this.newCss({ selector: ":last-of-type" });
  }

  /** Marks this element as a default hover marker (for ancestor pseudo selectors). */
  get marker(): CssBuilder<T> {
    return this.unsupportedRuntime("marker cannot be used in RuntimeStyle css expressions.");
  }

  /** Marks this element with a user-defined marker. */
  markerOf(_marker: Marker): CssBuilder<T> {
    return this.unsupportedRuntime("markerOf() cannot be used in RuntimeStyle css expressions.");
  }

  /** Creates a marker token for use with markerOf() and when(). */
  newMarker(): Marker {
    return Symbol("truss-marker");
  }

  typography(key: Typography): CssBuilder<T> {
    return (this as any)[key];
  }

  /**
    * Styles after this \`when\` are applied on the current element for a static selector.
    *
    * \`when(\":hover\")\` — same semantics as \`onHover\`
    * \`when(\":hover:not(:disabled)\")\` — hover only while enabled
    */
  when(selector: string): CssBuilder<T>;
  /**
    * Styles after this \`when\` are applied based on a marker relationship + pseudo selector.
    *
    * \`when(marker, "ancestor", ":hover")\` — react to marker ancestor hover
    * \`when(row, "descendant", ":focus")\` — react to a marked descendant focus
    */
  when(marker: Marker, relationship: "ancestor" | "descendant" | "anySibling" | "siblingBefore" | "siblingAfter", pseudo: string): CssBuilder<T>;
  /**
    * Apply different styles for each selector in the object.
    *
    * \`when({ ":hover": Css.blue.$, ":focus": Css.red.$ })\`
    */
  when(selectors: Record<string, T>): CssBuilder<T>;
  when(_selectorOrMarker: string | Marker | Record<string, T>, _relationship?: string, _pseudo?: string): CssBuilder<T> {
    return this.unsupportedRuntime("when() cannot be used in RuntimeStyle css expressions.");
  }

  ifContainer(_props: { name?: string; lt?: number; gt?: number }) {
    return this.unsupportedRuntime("ifContainer() cannot be used in RuntimeStyle css expressions.");
  }

  /** Apply styles within a pseudo-element (e.g. \`"::placeholder"\`, \`"::selection"\`). */
  element(_pseudoElement: string): CssBuilder<T> {
    return this.unsupportedRuntime("element() cannot be used in RuntimeStyle css expressions.");
  }

  ${breakpointIfs}

  /** Conditionally apply styles when \`cond\` is true. */
  if(cond: boolean): CssBuilder<T>;
  /** Apply styles within a media query (e.g. \`Breakpoints.sm\` or a raw \`@media\` string). */
  if(mediaQuery: string): CssBuilder<T>;
  if(condOrMediaQuery: boolean | string): CssBuilder<T> {
    if (typeof condOrMediaQuery === "boolean") {
      return new CssBuilder({ ...this.opts, enabled: condOrMediaQuery, elseApplied: false });
    }
    return this.unsupportedRuntime("if(mediaQuery) cannot be used in RuntimeStyle css expressions.");
  }

  get else(): CssBuilder<T> {
    if (this.selector !== undefined) {
      if (this.opts.elseApplied) {
        throw new Error("else was already called");
      }
      return this.newCss({ selector: invertMediaQuery(this.selector), elseApplied: true });
    }
    if (this.opts.elseApplied) {
      throw new Error("else was already called");
    }
    return new CssBuilder({ ...this.opts, enabled: !this.enabled, elseApplied: true });
  }

  /** Reset active conditional modifiers for subsequent styles. */
  get end(): CssBuilder<T> {
    return this.newCss({ selector: undefined, elseApplied: false });
  }

  add<P extends Properties>(props: P): CssBuilder<T & P>;
  add<K extends keyof Properties>(prop: K, value: Properties[K]): CssBuilder<T & { [U in K]: Properties[K] }>;
  add<K extends keyof Properties>(propOrStyles: K | Properties, value?: Properties[K]): CssBuilder<any> {
    if (!this.enabled) return this;

    const newRules = typeof propOrStyles === "string" ? { [propOrStyles]: value } : propOrStyles;
    const rules = this.selector
      ? { ...this.rules, [this.selector]: { ...(this.rules as any)[this.selector], ...newRules } }
      : { ...this.rules, ...newRules };
    return this.newCss({ rules: rules as any });
  }

  /** Inline a partial style hash, skipping any undefined values. */
  addCss<P extends Properties>(props: P): CssBuilder<T & P> {
    return this.add(omitUndefinedValues(props));
  }

  /** Marker for the build-time transform to append a raw className. */
  className(className: string): CssBuilder<T> {
    void className;
    return this.unsupportedRuntime("className() cannot be used in RuntimeStyle css expressions.");
  }

  /** Marker for the build-time transform to append raw inline styles. */
  style(inlineStyle: InlineStyle): CssBuilder<T> {
    void inlineStyle;
    return this.unsupportedRuntime("style() cannot be used in RuntimeStyle css expressions.");
  }

  /** Convert a style hash into \`{ className, style }\` props for manual spreading into non-\`css=\` contexts. */
  props(styles: Properties): Record<string, unknown> {
    return trussProps(styles as any);
  }

  /** Tagged template literal for raw CSS in .css.ts files; passes through the string as-is. */
  raw(strings: TemplateStringsArray, ...values: unknown[]): string {
    return String.raw(strings, ...values);
  }

  private get rules(): T {
    return this.opts.rules;
  }
  private get enabled(): boolean {
    return this.opts.enabled;
  }
  private get selector(): string | undefined {
    return this.opts.selector;
  }
  private unsupportedRuntime(message: string): CssBuilder<T> {
    return this.newCss({ runtimeError: message });
  }
  private newCss(opts: Partial<Opts<T>>): CssBuilder<T> {
    return new CssBuilder({ ...this.opts, ...opts });
  }
}

/** Converts \`inc\` into pixels value with a \`px\` suffix. */
export function maybeInc(inc: number | string): string {
  return typeof inc === "string" ? inc : \`\${inc * ${increment}}px\`;
}

/** Converts \`inc\` into pixels. */
export function increment(inc: number): number {
  return inc * ${increment};
}

/** Convert \`pixels\` to a \`px\` units string so it's not ambiguous. */
export function px(pixels: number): string {
  return \`\${pixels}px\`;
}

function omitUndefinedValues<T extends object>(value: T): T {
  const entries = Object.entries(value).filter(([, entryValue]) => {
    return entryValue !== undefined;
  });
  return Object.fromEntries(entries) as T;
}

export enum Palette {
  ${Object.entries(palette).map(([name, value]) => {
    return `${name} = "${value}",`;
  })}
}

/** A shortcut for defining Xss types. */
export type Xss<P extends keyof Properties> = Pick<Properties, P>;

/** The shared marker token for \`when(marker, relationship, pseudo)\`. */
export const marker: Marker = Symbol.for("truss-default-marker");

/** An entry point for Css expressions. CssBuilder is immutable so this is safe to share. */
export const Css = new CssBuilder({
  rules: {},
  enabled: true,
  selector: undefined,
  elseApplied: false,
  runtimeError: undefined,
});

${typeAliasCode}

${breakpointCode}

function invertMediaQuery(query: string): string {
  const screenPrefix = "@media screen and ";
  if (query.startsWith(screenPrefix)) {
    const conditions = query.slice(screenPrefix.length).trim();
    const rangeMatch = conditions.match(/^\(min-width: (\d+)px\) and \(max-width: (\d+)px\)$/);
    if (rangeMatch) {
      const min = Number(rangeMatch[1]);
      const max = Number(rangeMatch[2]);
      return \`@media screen and (max-width: \${min - 1}px), screen and (min-width: \${max + 1}px)\`;
    }
    const minMatch = conditions.match(/^\(min-width: (\d+)px\)$/);
    if (minMatch) {
      return \`@media screen and (max-width: \${Number(minMatch[1]) - 1}px)\`;
    }
    const maxMatch = conditions.match(/^\(max-width: (\d+)px\)$/);
    if (maxMatch) {
      return \`@media screen and (min-width: \${Number(maxMatch[1]) + 1}px)\`;
    }
  }
  return query.replace("@media", "@media not");
}


${extras || ""}
  `;
}

// ── Truss Mapping Generator ──────────────────────────────────────────

/** The shape of the Css.json mapping file consumed by the Vite plugin. */
export interface TrussMapping {
  increment: number;
  breakpoints?: Record<string, string>;
  typography?: string[];
  abbreviations: Record<string, TrussMappingEntry>;
}

export type TrussMappingEntry =
  | { kind: "static"; defs: Record<string, unknown> }
  | { kind: "variable"; props: string[]; incremented: boolean; extraDefs?: Record<string, unknown> }
  | { kind: "delegate"; target: string }
  | { kind: "alias"; chain: string[] };

/**
 * Generates the truss mapping JSON that the Vite plugin uses to resolve
 * Css abbreviation chains into CSS properties at build time.
 */
function generateTrussMapping(config: Config, entries: StylexEntry[]): TrussMapping {
  const { breakpoints = {} } = config;

  const abbreviations: Record<string, TrussMappingEntry> = {};

  for (const entry of entries) {
    switch (entry.kind) {
      case "static":
      case "cssvar":
        abbreviations[entry.abbr] = { kind: "static", defs: entry.defs || {} };
        break;
      case "param":
        abbreviations[entry.abbr] = {
          kind: "variable",
          props: entry.props || [],
          incremented: false,
          extraDefs: entry.extraDefs,
        };
        break;
      case "increment-param":
        abbreviations[entry.abbr] = {
          kind: "variable",
          props: entry.props || [],
          incremented: true,
          extraDefs: entry.extraDefs,
        };
        break;
      case "px-delegate":
        // The target is the abbreviation without the Px suffix
        abbreviations[entry.abbr] = {
          kind: "delegate",
          target: entry.abbr.replace(/Px$/, ""),
        };
        break;
      case "alias":
        abbreviations[entry.abbr] = {
          kind: "alias",
          chain: entry.aliasTargets || [],
        };
        break;
    }
  }

  // Generate breakpoint mapping: { ifSm: "@media ...", ifMd: "@media ...", ... }
  const genBreakpointsMap = makeBreakpoints(breakpoints);
  const breakpointEntries: Record<string, string> = {};
  for (const [name, mediaQuery] of Object.entries(genBreakpointsMap)) {
    breakpointEntries[`if${pascalCase(name)}`] = mediaQuery;
  }

  return {
    increment: config.increment,
    ...(Object.keys(breakpointEntries).length > 0 ? { breakpoints: breakpointEntries } : {}),
    ...(Object.keys(config.fonts).length > 0 ? { typography: Object.keys(config.fonts) } : {}),
    abbreviations,
  };
}

/** Produce compact JSON with one line per abbreviation entry. */
function condensedJson(mapping: TrussMapping): string {
  const lines: string[] = [];
  lines.push("{");
  lines.push(`  "increment": ${mapping.increment},`);
  if (mapping.breakpoints && Object.keys(mapping.breakpoints).length > 0) {
    lines.push(`  "breakpoints": ${JSON.stringify(mapping.breakpoints)},`);
  }
  if (mapping.typography && mapping.typography.length > 0) {
    lines.push(`  "typography": ${JSON.stringify(mapping.typography)},`);
  }
  lines.push(`  "abbreviations": {`);
  const entries = Object.entries(mapping.abbreviations);
  for (let i = 0; i < entries.length; i++) {
    const [key, value] = entries[i];
    const comma = i < entries.length - 1 ? "," : "";
    lines.push(`    ${JSON.stringify(key)}: ${JSON.stringify(value)}${comma}`);
  }
  lines.push("  }");
  lines.push("}");
  return lines.join("\n");
}
