import { Properties } from "csstype";
import { promises as fs } from "fs";
import { code, Code, def, imp } from "ts-poet";
import { makeBreakpoints } from "src/breakpoints";
import { Config, SectionName, Sections, UtilityMethod } from "src/config";
import { newAliasesMethods, startStylexCollection, stopStylexCollection, StylexEntry } from "src/methods";
import { defaultSections } from "src/sections/tachyons";
import { quote } from "src/utils";
import { pascalCase } from "change-case";
import { reactNativeSections } from "src/sections/tachyons-rn";

export const defaultTypeAliases: Record<string, Array<keyof Properties>> = {
  Margin: ["margin", "marginTop", "marginRight", "marginBottom", "marginLeft"],
  Padding: ["padding", "paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
};

export async function generate(config: Config): Promise<void> {
  const { outputPath, target = "emotion" } = config;
  const output = target === "stylex" ? generateStylexCssBuilder(config) : generateCssBuilder(config).toString();
  await fs.writeFile(outputPath, output);
}

function generateCssBuilder(config: Config): Code {
  const {
    aliases,
    fonts,
    increment,
    extras,
    typeAliases,
    breakpoints = {},
    palette,
    defaultMethods = "tachyons",
    sections: customSections,
  } = config;

  // Combine our out-of-the-box utility methods with any custom ones
  const sections: Record<string, string[]> = {
    // We only ship with tachyons & tachyons-rn methods currently
    ...(defaultMethods === "tachyons"
      ? generateMethods(config, defaultSections)
      : defaultMethods === "tachyons-rn"
      ? generateMethods(config, reactNativeSections)
      : {}),
    ...(customSections ? generateMethods(config, customSections) : {}),
    ...(aliases && { aliases: newAliasesMethods(aliases) }),
  };

  const Properties = imp("Properties@csstype");

  const lines = Object.entries(sections)
    .map(([name, value]) => [`// ${name}`, ...value, ""])
    .flat();

  const typeAliasCode = Object.entries({
    ...defaultTypeAliases,
    ...typeAliases,
  }).map(([name, props]) => {
    return `export type ${name} = ${props.map(quote).join(" | ")};\n\n`;
  });

  const typographyType = code`
    export type ${def("Typography")} = ${Object.keys(fonts).map(quote).join(" | ")};
  `;

  const genBreakpoints = makeBreakpoints(breakpoints);

  const breakpointCode = [
    `export type Breakpoint = ${Object.keys(genBreakpoints).map(quote).join(" | ")};`,
    `export enum Breakpoints {
       ${Object.entries(genBreakpoints).map(([name, value]) => `${name} = "${value}"`)}
    };`,
  ];

  const breakpointIfs = Object.entries(genBreakpoints).map(([name, value]) => {
    return code`
      get if${pascalCase(name)}() {
        return this.newCss({ selector: ${quote(value)} });
      }`;
  });

  const containerQueriesCode = code`
    /**
     * Utility to help write \`@container\` queries
     *
     * @param name - The name of the container.
     * @param lt - The maximum width of the container inclusive.
     * @param gt - The minimum width of the container exclusive.
     */
    type ContainerProps = { name?: string } & ({ lt: number } | { gt: number } | { lt: number; gt: number });
    export function Container(props: ContainerProps) {
      const { name = "" } = props;
      const lt = "lt" in props ? props.lt : undefined;
      const gt = "gt" in props ? props.gt : undefined;

      const ltQuery = lt !== undefined ? \`(max-width: \${lt}px)\` : "";
      const gtQuery = gt !== undefined ? \`(min-width: \${gt + 1}px)\` : "";
      const query = [ltQuery, gtQuery].filter(Boolean).join(" and ");

      return \`@container \${name} \${query}\`;
    }`;

  return code`
// This file is auto-generated by truss: https://github.com/homebound-team/truss.
// See your project's \`truss-config.ts\` to make configuration changes (fonts, increments, etc).

/** Given a type X, and the user's proposed type T, only allow keys in X and nothing else. */
export type Only<X, T> = X & Record<Exclude<keyof T, keyof X>, never>;

export type ${def("Properties")} = ${Properties}<string | 0, string>;

${typographyType}

type Opts<T> = {
  rules: T,
  enabled: boolean,
  important: boolean,
  selector: string | undefined
};

class CssBuilder<T extends Properties> {
  constructor(private opts: Opts<T>) {}

  private get rules(): T { return this.opts.rules };
  private get enabled(): boolean { return this.opts.enabled };
  private get selector(): string | undefined { return this.opts.selector };
  private newCss(opts: Partial<Opts<T>>): CssBuilder<T> {
    return new CssBuilder({ ...this.opts, ...opts });
  }

  ${lines.join("\n  ").replace(/ +\n/g, "\n")}
    
  get $(): T { return maybeImportant(sortObject(this.rules), this.opts.important); }

  if(bp: Breakpoint): CssBuilder<T>;
  if(cond: boolean): CssBuilder<T>;
  if(attr: string, value: boolean | string): CssBuilder<T>;
  if(arg: boolean | Breakpoint | string, value?: boolean | string): CssBuilder<T> {
    if (value !== undefined) {
      return this.newCss({ selector: \`[\${arg}='\${value}']\` });
    } else if (typeof arg === "boolean") {
      return this.newCss({ enabled: arg });
    } else {
      return this.newCss({ selector: Breakpoints[arg as Breakpoint] });
    }
  }

  get onHover() {
    return this.newCss({ selector: ":hover" });
  }
  
  ifContainer(props: ContainerProps) {
    return this.newCss({ selector: Container(props) });
  }
  
  ${breakpointIfs}

  get else() {
    if (this.selector !== undefined) {
      if (this.selector.includes("not")) {
        throw new Error("else was already called");
      } else {
        return this.newCss({ selector: this.selector.replace("@media", "@media not") });
      }
    }
    return this.newCss({ enabled: !this.enabled });
  }

  get important() { return this.newCss({ important: true }); }

  /** Adds new properties, either a specific key/value or a Properties object, to the current css. */
  add<P extends Properties>(props: P): CssBuilder<T & P>;
  add<K extends keyof Properties>(prop: K, value: Properties[K]): CssBuilder<T & { [U in K]: Properties[K] }>;
  add<K extends keyof Properties>(propOrProperties: K | Properties, value?: Properties[K]): CssBuilder<any> {
    if (!this.enabled) return this;
    const newRules = typeof propOrProperties === "string" ?  { [propOrProperties]: value } : propOrProperties;
    const rules = this.selector
      ? { ...this.rules, [this.selector]: { ...(this.rules as any)[this.selector], ...newRules } }
      : { ...this.rules, ...newRules };
    return this.newCss({ rules: rules as any });
  }

  /** Adds new properties, either a specific key/value or a Properties object, to a nested selector. */
  addIn<P extends Properties>(selector: string, props: P | undefined): CssBuilder<T & P>;
  addIn<K extends keyof Properties>(selector: string, prop: K, value: Properties[K]): CssBuilder<T & { [U in K]: Properties[K] }>;
  addIn<K extends keyof Properties>(selector: string, propOrProperties: K | Properties, value?: Properties[K]): CssBuilder<any> {
    const newRules = typeof propOrProperties === "string" ?  { [propOrProperties]: value } : propOrProperties;
    if (!this.enabled) return this;
    if (newRules === undefined) {
      return this;
    }
    const rules = { ...this.rules, [selector]: { ...(this.rules as any)[selector], ...newRules } };
    return this.newCss({ rules: rules as any });
  }
}

/** Emotion treats the same rules, ordered differently as different classes, but naively they can be the same. */
function sortObject<T extends object>(obj: T): T {
  return Object.keys(obj)
    .sort()
    .reduce((acc, key) => {
      acc[key as keyof T] = obj[key as keyof T];
      return acc;
    }, ({} as any) as T) as T;
}

/** Conditionally adds \`important!\` to everything. */
function maybeImportant<T extends object>(obj: T, important: boolean): T {
  if (important) {
    Object.keys(obj).forEach(key => {
      (obj as any)[key] = \`\${(obj as any)[key]} !important\`;
    });
  }
  return obj;
}

/** Converts \`inc\` into pixels value with a \`px\` suffix. */
export function maybeInc(inc: number | string): string {
  return typeof inc === "string" ? inc : \`\${increment(inc)}px\`;
}

/** Converts \`inc\` into pixels. */
export function increment(inc: number): number {
  return inc * ${increment};
}

/** Convert \`pixels\` to a \`px\` units string so it's not ambiguous. */
export function px(pixels: number): string {
  return \`\${pixels}px\`;
}

export enum Palette {
  ${Object.entries(palette).map(([name, value]) => {
    return `${name} = "${value}",`;
  })}
}

/** A shortcut for defining Xss types. */
export type Xss<P extends keyof Properties> = Pick<Properties, P>;

/** An entry point for Css expressions. CssBuilder is immutable so this is safe to share. */
export const Css = new CssBuilder({ rules: {}, enabled: true, important: false, selector: undefined });

${typeAliasCode}

${breakpointCode}

${containerQueriesCode}

${extras || ""}
  `;
}

/** Invokes all of the `MethodFns` to create actual `UtilityMethod`s. */
function generateMethods(config: Config, methodFns: Sections): Record<SectionName, UtilityMethod[]> {
  return Object.fromEntries(Object.entries(methodFns).map(([name, fn]) => [name, fn(config)]));
}

// ── StyleX Code Generator ─────────────────────────────────────────────

/**
 * Generates a Css.ts file that uses StyleX for build-time CSS extraction.
 *
 * Instead of accumulating a plain `{ prop: value }` object (as the emotion target does),
 * the generated CssBuilder accumulates an array of StyleX style references. The terminal
 * `$` getter calls `stylex.props()` to produce `{ className?, style? }`.
 */
function generateStylexCssBuilder(config: Config): string {
  const { aliases, fonts, increment, extras, palette, defaultMethods = "tachyons", sections: customSections } = config;

  // 1. Run sections with the collector enabled to get structured data
  startStylexCollection();

  const sectionFns: Record<string, (c: Config) => string[]> = {
    ...(defaultMethods === "tachyons" ? defaultSections : defaultMethods === "tachyons-rn" ? reactNativeSections : {}),
    ...(customSections || {}),
  };

  // Execute all section functions (we ignore the string return values)
  const sectionNames: string[] = [];
  for (const [name, fn] of Object.entries(sectionFns)) {
    fn(config);
    sectionNames.push(name);
  }

  // Also process aliases
  if (aliases) {
    newAliasesMethods(aliases);
  }

  const entries = stopStylexCollection();

  // 2. Group entries by section. We'll assign entries to sections based on
  //    the order they were collected vs. the order sections were called.
  const sectionEntries = groupEntriesBySections(config, sectionFns, entries, aliases);

  // 3. Build the output string
  const lines: string[] = [];

  lines.push(`// This file is auto-generated by truss: https://github.com/homebound-team/truss.`);
  lines.push(`// See your project's \`truss-config.ts\` to make configuration changes (fonts, increments, etc).`);
  lines.push(`// Target: stylex`);
  lines.push(``);
  lines.push(`import * as stylex from "@stylexjs/stylex";`);
  lines.push(`import type { Properties as CSSTypeProperties } from "csstype";`);
  lines.push(``);
  lines.push(`export type Properties = CSSTypeProperties<string | 0, string>;`);
  lines.push(``);

  // Typography type
  lines.push(`export type Typography = ${Object.keys(fonts).map(quote).join(" | ")};`);
  lines.push(``);

  // Palette enum
  lines.push(`export enum Palette {`);
  for (const [name, value] of Object.entries(palette)) {
    lines.push(`  ${name} = "${value}",`);
  }
  lines.push(`}`);
  lines.push(``);

  // 4. Generate stylex.create() calls per section (static + dynamic entries in one call)
  for (const [sectionName, sEntries] of Object.entries(sectionEntries)) {
    const statics = sEntries.filter((e) => e.kind === "static" || e.kind === "cssvar");
    const dynamics = sEntries.filter((e) => e.kind === "param" || e.kind === "increment-param");

    if (statics.length === 0 && dynamics.length === 0) continue;

    lines.push(`const ${sectionName} = stylex.create({`);
    for (const entry of statics) {
      const propsStr = formatStylexProps(entry.defs || {});
      lines.push(`  ${entry.abbr}: ${propsStr},`);
    }
    for (const entry of dynamics) {
      const props = entry.props || [];
      if (props.length === 1) {
        lines.push(`  ${entry.abbr}: (v: string) => ({ ${props[0]}: v }),`);
      } else {
        const propAssigns = props.map((p) => `${p}: v`).join(", ");
        lines.push(`  ${entry.abbr}: (v: string) => ({ ${propAssigns} }),`);
      }
    }
    lines.push(`});`);
    lines.push(``);
  }

  // 5. Utility helpers
  lines.push(`/** Converts \`inc\` into pixels value with a \`px\` suffix. */`);
  lines.push(`function maybeInc(inc: number | string): string {`);
  lines.push(`  return typeof inc === "string" ? inc : \`\${inc * ${increment}}px\`;`);
  lines.push(`}`);
  lines.push(``);

  // 6. CssBuilder class
  lines.push(`type StyleRef = ReturnType<typeof stylex.create>[string];`);
  lines.push(``);
  lines.push(`/** The type accepted by the \`css\` JSX prop. An array of StyleX style refs. */`);
  lines.push(`export type CssProp = StyleRef[];`);
  lines.push(``);
  lines.push(`class CssBuilder {`);
  lines.push(`  constructor(private styleRefs: StyleRef[], private enabled: boolean) {}`);
  lines.push(``);
  lines.push(`  private addStyle(ref: StyleRef): CssBuilder {`);
  lines.push(`    if (!this.enabled) return this;`);
  lines.push(`    return new CssBuilder([...this.styleRefs, ref], this.enabled);`);
  lines.push(`  }`);
  lines.push(``);

  // Generate builder methods per section
  for (const [sectionName, sEntries] of Object.entries(sectionEntries)) {
    lines.push(`  // ${sectionName}`);

    for (const entry of sEntries) {
      switch (entry.kind) {
        case "static":
        case "cssvar":
          lines.push(`  get ${entry.abbr}() { return this.addStyle(${sectionName}.${entry.abbr}); }`);
          break;
        case "param":
          {
            const prop = entry.props![0];
            lines.push(
              `  ${entry.abbr}(value: Properties["${prop}"]) { return this.addStyle(${sectionName}.${entry.abbr}(String(value))); }`,
            );
          }
          break;
        case "increment-param":
          lines.push(
            `  ${entry.abbr}(v: number | string) { return this.addStyle(${sectionName}.${entry.abbr}(maybeInc(v))); }`,
          );
          break;
        case "px-delegate":
          // Delegates to the base method with a px string. The base abbreviation is
          // the name without the trailing "Px".
          const baseAbbr = entry.abbr.replace(/Px$/, "");
          lines.push(`  ${entry.abbr}(px: number) { return this.${baseAbbr}(\`\${px}px\`); }`);
          break;
        case "alias":
          lines.push(`  get ${entry.abbr}() { return this${entry.aliasTargets!.map((t) => `.${t}`).join("")}; }`);
          break;
      }
    }
    lines.push(``);
  }

  // Conditional support
  lines.push(`  /** Conditionally apply styles. */`);
  lines.push(`  if(cond: boolean): CssBuilder {`);
  lines.push(`    return new CssBuilder([...this.styleRefs], cond);`);
  lines.push(`  }`);
  lines.push(``);
  lines.push(`  get else(): CssBuilder {`);
  lines.push(`    return new CssBuilder([...this.styleRefs], !this.enabled);`);
  lines.push(`  }`);
  lines.push(``);

  // Terminal $ getter
  lines.push(
    `  /** Returns the accumulated style refs. Pass to the \`css\` JSX prop or spread with other CssProp arrays. */`,
  );
  lines.push(`  get $(): CssProp {`);
  lines.push(`    return [...this.styleRefs];`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);

  // Css singleton
  lines.push(`/** An entry point for Css expressions. CssBuilder is immutable so this is safe to share. */`);
  lines.push(`export const Css = new CssBuilder([], true);`);
  lines.push(``);

  // Extras
  if (extras) {
    for (const extra of extras) {
      lines.push(String(extra));
    }
    lines.push(``);
  }

  return lines.join("\n");
}

/** Format a CSS properties object as a stylex-compatible object literal string. */
function formatStylexProps(defs: Record<string, unknown>): string {
  const entries = Object.entries(defs).map(([prop, value]) => {
    if (typeof value === "number") {
      return `${prop}: ${value}`;
    }
    return `${prop}: "${value}"`;
  });
  return `{ ${entries.join(", ")} }`;
}

/**
 * Groups the flat collected StylexEntry array back into sections, preserving
 * the section ordering. We do this by re-running the section functions one
 * at a time and counting how many entries each produces.
 */
function groupEntriesBySections(
  config: Config,
  sectionFns: Record<string, (c: Config) => string[]>,
  allEntries: StylexEntry[],
  aliases?: Record<string, string[]>,
): Record<string, StylexEntry[]> {
  // Re-run each section to count entries
  const result: Record<string, StylexEntry[]> = {};
  let offset = 0;

  for (const [name] of Object.entries(sectionFns)) {
    startStylexCollection();
    sectionFns[name](config);
    const sectionEntries = stopStylexCollection();
    const count = sectionEntries.length;
    result[name] = allEntries.slice(offset, offset + count);
    offset += count;
  }

  if (aliases) {
    startStylexCollection();
    newAliasesMethods(aliases);
    const aliasEntries = stopStylexCollection();
    result["aliases"] = allEntries.slice(offset, offset + aliasEntries.length);
    offset += aliasEntries.length;
  }

  return result;
}
