version: 2.1

orbs:
  node: circleci/node@5.0.1

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: npm-readonly
      - publish:
          context:
            - npm-publish
            - github
          requires:
            - build
          filters:
            branches:
              only:
                - main

jobs:
  build:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/project
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build
      - run: yarn test

  publish:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/project
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build
      - run: yarn semantic-release
