// This file is auto-generated by truss: https://github.com/homebound-team/truss.
// See your project's `truss-config.ts` to make configuration changes (fonts, increments, etc).
// Target: stylex

import * as stylex from "@stylexjs/stylex";
import type { Properties as CSSTypeProperties } from "csstype";

export type Properties = CSSTypeProperties<string | 0, string>;

export type Typography = "f24" | "f18" | "f16" | "f14" | "f12" | "f10";

export enum Palette {
  Black = "#353535",
  MidGray = "#888888",
  LightGray = "#cecece",
  White = "#fcfcfa",
  Blue = "#526675",
  Primary = "var(--primary)",
}

const border = stylex.create({
  ba: { borderStyle: "solid", borderWidth: "1px" },
  bt: { borderTopStyle: "solid", borderTopWidth: "1px" },
  br: { borderRightStyle: "solid", borderRightWidth: "1px" },
  bb: { borderBottomStyle: "solid", borderBottomWidth: "1px" },
  bl: { borderLeftStyle: "solid", borderLeftWidth: "1px" },
  bn: { borderStyle: "none", borderWidth: "0" },
});

const borderColor = stylex.create({
  bcBlack: { borderColor: "#353535" },
  bcMidGray: { borderColor: "#888888" },
  bcLightGray: { borderColor: "#cecece" },
  bcWhite: { borderColor: "#fcfcfa" },
  bcBlue: { borderColor: "#526675" },
  bcPrimary: { borderColor: "var(--primary)" },
  bc: (v: string) => ({ borderColor: v }),
});

const borderRadius = stylex.create({
  br0: { borderRadius: "0" },
  br1: { borderRadius: ".125rem" },
  br2: { borderRadius: ".25rem" },
  br3: { borderRadius: ".5rem" },
  br4: { borderRadius: "1rem" },
  br100: { borderRadius: "100%" },
  brPill: { borderRadius: "9999px" },
  borderRadius: (v: string) => ({ borderRadius: v }),
});

const borderStyle = stylex.create({
  bsDashed: { borderStyle: "dashed" },
  bsDotted: { borderStyle: "dotted" },
  bsn: { borderStyle: "none" },
  bss: { borderStyle: "solid" },
  bs: (v: string) => ({ borderStyle: v }),
});

const borderWidth = stylex.create({
  bw1: { borderWidth: "1px" },
  bw2: { borderWidth: "2px" },
  bw: (v: string) => ({ borderWidth: v }),
});

const boxShadow = stylex.create({
  shadowNone: { boxShadow: "none" },
});

const container = stylex.create({
  cts: { containerType: "size" },
  ctis: { containerType: "inline-size" },
  ctn: { containerType: "normal" },
  ct: (v: string) => ({ containerType: v }),
  cn: (v: string) => ({ containerName: v }),
});

const coordinates = stylex.create({
  top0: { top: "0px" },
  top1: { top: "8px" },
  top2: { top: "16px" },
  top3: { top: "24px" },
  top4: { top: "32px" },
  right0: { right: "0px" },
  right1: { right: "8px" },
  right2: { right: "16px" },
  right3: { right: "24px" },
  right4: { right: "32px" },
  bottom0: { bottom: "0px" },
  bottom1: { bottom: "8px" },
  bottom2: { bottom: "16px" },
  bottom3: { bottom: "24px" },
  bottom4: { bottom: "32px" },
  left0: { left: "0px" },
  left1: { left: "8px" },
  left2: { left: "16px" },
  left3: { left: "24px" },
  left4: { left: "32px" },
  top: (v: string) => ({ top: v }),
  right: (v: string) => ({ right: v }),
  bottom: (v: string) => ({ bottom: v }),
  left: (v: string) => ({ left: v }),
});

const cursor = stylex.create({
  cursorPointer: { cursor: "pointer" },
  cursorNotAllowed: { cursor: "not-allowed" },
  cursor: (v: string) => ({ cursor: v }),
});

const display = stylex.create({
  dn: { display: "none" },
  db: { display: "block" },
  dib: { display: "inline-block" },
  dit: { display: "inline-table" },
  dt: { display: "table" },
  dtc: { display: "table-cell" },
  dtRow: { display: "table-row" },
  dtColumn: { display: "table-column" },
  dtColumnGroup: { display: "table-column-group" },
  dg: { display: "grid" },
  dig: { display: "inline-grid" },
  df: { display: "flex" },
  dif: { display: "inline-flex" },
  display: (v: string) => ({ display: v }),
});

const flexbox = stylex.create({
  fi: { flex: "initial" },
  fa: { flex: "auto" },
  fn: { flex: "none" },
  f1: { flex: "1" },
  f2: { flex: "2" },
  f3: { flex: "3" },
  f4: { flex: "4" },
  f5: { flex: "5" },
  jcfs: { justifyContent: "flex-start" },
  jcfe: { justifyContent: "flex-end" },
  jcc: { justifyContent: "center" },
  jcsb: { justifyContent: "space-between" },
  jcsa: { justifyContent: "space-around" },
  jcse: { justifyContent: "space-evenly" },
  jsa: { justifySelf: "auto" },
  jsc: { justifySelf: "center" },
  jss: { justifySelf: "start" },
  jse: { justifySelf: "end" },
  jifs: { justifyItems: "flex-start" },
  jife: { justifyItems: "flex-end" },
  jic: { justifyItems: "center" },
  jisb: { justifyItems: "space-between" },
  jisa: { justifyItems: "space-around" },
  jise: { justifyItems: "space-evenly" },
  asfs: { alignSelf: "flex-start" },
  asfe: { alignSelf: "flex-end" },
  asc: { alignSelf: "center" },
  asb: { alignSelf: "baseline" },
  asStretch: { alignSelf: "stretch" },
  aifs: { alignItems: "flex-start" },
  aife: { alignItems: "flex-end" },
  ais: { alignItems: "start" },
  aie: { alignItems: "end" },
  aic: { alignItems: "center" },
  aib: { alignItems: "baseline" },
  aiStretch: { alignItems: "stretch" },
  psa: { placeSelf: "auto" },
  psc: { placeSelf: "center" },
  pss: { placeSelf: "start" },
  pse: { placeSelf: "end" },
  psfs: { placeSelf: "flex-start" },
  psfe: { placeSelf: "flex-end" },
  psStretch: { placeSelf: "stretch" },
  pcc: { placeContent: "center" },
  pcs: { placeContent: "start" },
  pce: { placeContent: "end" },
  pcsb: { placeContent: "space-between" },
  pcsa: { placeContent: "space-around" },
  pcse: { placeContent: "space-evenly" },
  pcb: { placeContent: "baseline" },
  pcStretch: { placeContent: "stretch" },
  pic: { placeItems: "center" },
  pis: { placeItems: "start" },
  pie: { placeItems: "end" },
  pisb: { placeItems: "space-between" },
  pisa: { placeItems: "space-around" },
  pise: { placeItems: "space-evenly" },
  pib: { placeItems: "baseline" },
  piStretch: { placeItems: "stretch" },
  fb1: { flexBasis: "100%" },
  fb2: { flexBasis: "50%" },
  fb3: { flexBasis: "33.333333%" },
  fb4: { flexBasis: "25%" },
  fb5: { flexBasis: "20%" },
  fb6: { flexBasis: "16.666666%" },
  fb7: { flexBasis: "14.285714%" },
  fb0: { flexBasis: "12.5%" },
  fg0: { flexGrow: 0 },
  fg1: { flexGrow: 1 },
  fs0: { flexShrink: 0 },
  fs1: { flexShrink: 1 },
  fdr: { flexDirection: "row" },
  fdrr: { flexDirection: "row-reverse" },
  fdc: { flexDirection: "column" },
  fdcr: { flexDirection: "column-reverse" },
  fww: { flexWrap: "wrap" },
  fwr: { flexWrap: "wrap-reverse" },
  fwnw: { flexWrap: "nowrap" },
  f: (v: string) => ({ flex: v }),
  jc: (v: string) => ({ justifyContent: v }),
  js: (v: string) => ({ justifySelf: v }),
  ji: (v: string) => ({ justifyItems: v }),
  as: (v: string) => ({ alignSelf: v }),
  ai: (v: string) => ({ alignItems: v }),
  ps: (v: string) => ({ placeSelf: v }),
  pc: (v: string) => ({ placeContent: v }),
  pi: (v: string) => ({ placeItems: v }),
  fb: (v: string) => ({ flexBasis: v }),
  flexGrow: (v: string) => ({ flexGrow: v }),
  flexShrink: (v: string) => ({ flexShrink: v }),
  fd: (v: string) => ({ flexDirection: v }),
  flexWrap: (v: string) => ({ flexWrap: v }),
  order: (v: string) => ({ order: v }),
});

const float = stylex.create({
  fl: { float: "left" },
  fr: { float: "right" },
  float: (v: string) => ({ float: v }),
});

const fontWeight = stylex.create({
  fwn: { fontWeight: "normal" },
  fwb: { fontWeight: "bold" },
  fw1: { fontWeight: 100 },
  fw2: { fontWeight: 200 },
  fw3: { fontWeight: 300 },
  fw4: { fontWeight: 400 },
  fw5: { fontWeight: 500 },
  fw6: { fontWeight: 600 },
  fw7: { fontWeight: 700 },
  fw8: { fontWeight: 800 },
  fw9: { fontWeight: 900 },
  fw: (v: string) => ({ fontWeight: v }),
});

const grid = stylex.create({
  gap0: { gap: "0px" },
  gap1: { gap: "8px" },
  gap2: { gap: "16px" },
  gap3: { gap: "24px" },
  gap4: { gap: "32px" },
  rg0: { rowGap: "0px" },
  rg1: { rowGap: "8px" },
  rg2: { rowGap: "16px" },
  rg3: { rowGap: "24px" },
  rg4: { rowGap: "32px" },
  cg0: { columnGap: "0px" },
  cg1: { columnGap: "8px" },
  cg2: { columnGap: "16px" },
  cg3: { columnGap: "24px" },
  cg4: { columnGap: "32px" },
  gtc: (v: string) => ({ gridTemplateColumns: v }),
  gtr: (v: string) => ({ gridTemplateRows: v }),
  gr: (v: string) => ({ gridRow: v }),
  gc: (v: string) => ({ gridColumn: v }),
  gar: (v: string) => ({ gridAutoRows: v }),
  gac: (v: string) => ({ gridAutoColumns: v }),
  gap: (v: string) => ({ gap: v }),
  rg: (v: string) => ({ rowGap: v }),
  cg: (v: string) => ({ columnGap: v }),
});

const height = stylex.create({
  h0: { height: "0px" },
  h1: { height: "8px" },
  h2: { height: "16px" },
  h3: { height: "24px" },
  h4: { height: "32px" },
  ha: { height: "auto" },
  h25: { height: "25%" },
  h50: { height: "50%" },
  h75: { height: "75%" },
  h100: { height: "100%" },
  vh25: { height: "25vh" },
  vh50: { height: "50vh" },
  vh75: { height: "75vh" },
  vh100: { height: "100vh" },
  hfc: { height: "fit-content" },
  hmaxc: { height: "max-content" },
  hminc: { height: "min-content" },
  mh0: { minHeight: 0 },
  mh25: { minHeight: "25%" },
  mh50: { minHeight: "50%" },
  mh75: { minHeight: "75%" },
  mh100: { minHeight: "100%" },
  mvh100: { minHeight: "100vh" },
  maxh0: { maxHeight: "0" },
  maxh25: { maxHeight: "25%" },
  maxh50: { maxHeight: "50%" },
  maxh75: { maxHeight: "75%" },
  maxh100: { maxHeight: "100%" },
  h: (v: string) => ({ height: v }),
  mh: (v: string) => ({ minHeight: v }),
  maxh: (v: string) => ({ maxHeight: v }),
});

const lineClamp = stylex.create({
  lineClamp1: { overflow: "hidden", display: "-webkit-box", WebkitBoxOrient: "vertical", textOverflow: "ellipsis", WebkitLineClamp: 1 },
  lineClamp2: { overflow: "hidden", display: "-webkit-box", WebkitBoxOrient: "vertical", textOverflow: "ellipsis", WebkitLineClamp: 2 },
  lineClamp3: { overflow: "hidden", display: "-webkit-box", WebkitBoxOrient: "vertical", textOverflow: "ellipsis", WebkitLineClamp: 3 },
  lineClamp4: { overflow: "hidden", display: "-webkit-box", WebkitBoxOrient: "vertical", textOverflow: "ellipsis", WebkitLineClamp: 4 },
  lineClamp5: { overflow: "hidden", display: "-webkit-box", WebkitBoxOrient: "vertical", textOverflow: "ellipsis", WebkitLineClamp: 5 },
  lineClamp6: { overflow: "hidden", display: "-webkit-box", WebkitBoxOrient: "vertical", textOverflow: "ellipsis", WebkitLineClamp: 6 },
  lineClampNone: { WebkitLineClamp: "unset" },
  lineClamp: (v: string) => ({ WebkitLineClamp: v }),
});

const objectFit = stylex.create({
  objectContain: { objectFit: "contain" },
  objectCover: { objectFit: "cover" },
  objectFill: { objectFit: "fill" },
  objectNone: { objectFit: "none" },
  objectScaleDown: { objectFit: "scale-down" },
  objectFit: (v: string) => ({ objectFit: v }),
});

const opacity = stylex.create({
  o0: { opacity: "0" },
  o25: { opacity: "0.25" },
  o50: { opacity: "0.5" },
  o75: { opacity: "0.75" },
  o100: { opacity: "1" },
  o: (v: string) => ({ opacity: v }),
});

const outline = stylex.create({
  outline1: { outline: "1px solid" },
  outlineTransparent: { outline: "1px solid transparent" },
  outline0: { outline: "0" },
  outline: (v: string) => ({ outline: v }),
});

const overflow = stylex.create({
  ov: { overflow: "visible" },
  oh: { overflow: "hidden" },
  os: { overflow: "scroll" },
  oa: { overflow: "auto" },
  oyv: { overflowY: "visible" },
  oyh: { overflowY: "hidden" },
  oys: { overflowY: "scroll" },
  oya: { overflowY: "auto" },
  oxv: { overflowX: "visible" },
  oxh: { overflowX: "hidden" },
  oxs: { overflowX: "scroll" },
  oxa: { overflowX: "auto" },
  overflow: (v: string) => ({ overflow: v }),
  overflowY: (v: string) => ({ overflowY: v }),
  overflowX: (v: string) => ({ overflowX: v }),
});

const position = stylex.create({
  absolute: { position: "absolute" },
  fixed: { position: "fixed" },
  static: { position: "static" },
  relative: { position: "relative" },
  sticky: { position: "sticky" },
  position: (v: string) => ({ position: v }),
});

const skins = stylex.create({
  black: { color: "#353535" },
  midGray: { color: "#888888" },
  lightGray: { color: "#cecece" },
  white: { color: "#fcfcfa" },
  blue: { color: "#526675" },
  primary: { color: "var(--primary)" },
  bgBlack: { backgroundColor: "#353535" },
  bgMidGray: { backgroundColor: "#888888" },
  bgLightGray: { backgroundColor: "#cecece" },
  bgWhite: { backgroundColor: "#fcfcfa" },
  bgBlue: { backgroundColor: "#526675" },
  bgPrimary: { backgroundColor: "var(--primary)" },
  fBlack: { fill: "#353535" },
  fMidGray: { fill: "#888888" },
  fLightGray: { fill: "#cecece" },
  fWhite: { fill: "#fcfcfa" },
  fBlue: { fill: "#526675" },
  fPrimary: { fill: "var(--primary)" },
  color: (v: string) => ({ color: v }),
  bgColor: (v: string) => ({ backgroundColor: v }),
  fill: (v: string) => ({ fill: v }),
});

const spacing = stylex.create({
  mt0: { marginTop: "0px" },
  mt1: { marginTop: "8px" },
  mt2: { marginTop: "16px" },
  mt3: { marginTop: "24px" },
  mt4: { marginTop: "32px" },
  mta: { marginTop: "auto" },
  mr0: { marginRight: "0px" },
  mr1: { marginRight: "8px" },
  mr2: { marginRight: "16px" },
  mr3: { marginRight: "24px" },
  mr4: { marginRight: "32px" },
  mra: { marginRight: "auto" },
  mb0: { marginBottom: "0px" },
  mb1: { marginBottom: "8px" },
  mb2: { marginBottom: "16px" },
  mb3: { marginBottom: "24px" },
  mb4: { marginBottom: "32px" },
  mba: { marginBottom: "auto" },
  ml0: { marginLeft: "0px" },
  ml1: { marginLeft: "8px" },
  ml2: { marginLeft: "16px" },
  ml3: { marginLeft: "24px" },
  ml4: { marginLeft: "32px" },
  mla: { marginLeft: "auto" },
  mx0: { marginLeft: "0px", marginRight: "0px" },
  mx1: { marginLeft: "8px", marginRight: "8px" },
  mx2: { marginLeft: "16px", marginRight: "16px" },
  mx3: { marginLeft: "24px", marginRight: "24px" },
  mx4: { marginLeft: "32px", marginRight: "32px" },
  mxa: { marginLeft: "auto", marginRight: "auto" },
  my0: { marginTop: "0px", marginBottom: "0px" },
  my1: { marginTop: "8px", marginBottom: "8px" },
  my2: { marginTop: "16px", marginBottom: "16px" },
  my3: { marginTop: "24px", marginBottom: "24px" },
  my4: { marginTop: "32px", marginBottom: "32px" },
  mya: { marginTop: "auto", marginBottom: "auto" },
  m0: { marginTop: "0px", marginBottom: "0px", marginRight: "0px", marginLeft: "0px" },
  m1: { marginTop: "8px", marginBottom: "8px", marginRight: "8px", marginLeft: "8px" },
  m2: { marginTop: "16px", marginBottom: "16px", marginRight: "16px", marginLeft: "16px" },
  m3: { marginTop: "24px", marginBottom: "24px", marginRight: "24px", marginLeft: "24px" },
  m4: { marginTop: "32px", marginBottom: "32px", marginRight: "32px", marginLeft: "32px" },
  ma: { marginTop: "auto", marginBottom: "auto", marginRight: "auto", marginLeft: "auto" },
  pt0: { paddingTop: "0px" },
  pt1: { paddingTop: "8px" },
  pt2: { paddingTop: "16px" },
  pt3: { paddingTop: "24px" },
  pt4: { paddingTop: "32px" },
  pr0: { paddingRight: "0px" },
  pr1: { paddingRight: "8px" },
  pr2: { paddingRight: "16px" },
  pr3: { paddingRight: "24px" },
  pr4: { paddingRight: "32px" },
  pb0: { paddingBottom: "0px" },
  pb1: { paddingBottom: "8px" },
  pb2: { paddingBottom: "16px" },
  pb3: { paddingBottom: "24px" },
  pb4: { paddingBottom: "32px" },
  pl0: { paddingLeft: "0px" },
  pl1: { paddingLeft: "8px" },
  pl2: { paddingLeft: "16px" },
  pl3: { paddingLeft: "24px" },
  pl4: { paddingLeft: "32px" },
  px0: { paddingLeft: "0px", paddingRight: "0px" },
  px1: { paddingLeft: "8px", paddingRight: "8px" },
  px2: { paddingLeft: "16px", paddingRight: "16px" },
  px3: { paddingLeft: "24px", paddingRight: "24px" },
  px4: { paddingLeft: "32px", paddingRight: "32px" },
  py0: { paddingTop: "0px", paddingBottom: "0px" },
  py1: { paddingTop: "8px", paddingBottom: "8px" },
  py2: { paddingTop: "16px", paddingBottom: "16px" },
  py3: { paddingTop: "24px", paddingBottom: "24px" },
  py4: { paddingTop: "32px", paddingBottom: "32px" },
  p0: { paddingTop: "0px", paddingBottom: "0px", paddingRight: "0px", paddingLeft: "0px" },
  p1: { paddingTop: "8px", paddingBottom: "8px", paddingRight: "8px", paddingLeft: "8px" },
  p2: { paddingTop: "16px", paddingBottom: "16px", paddingRight: "16px", paddingLeft: "16px" },
  p3: { paddingTop: "24px", paddingBottom: "24px", paddingRight: "24px", paddingLeft: "24px" },
  p4: { paddingTop: "32px", paddingBottom: "32px", paddingRight: "32px", paddingLeft: "32px" },
  mt: (v: string) => ({ marginTop: v }),
  mr: (v: string) => ({ marginRight: v }),
  mb: (v: string) => ({ marginBottom: v }),
  ml: (v: string) => ({ marginLeft: v }),
  mx: (v: string) => ({ marginLeft: v, marginRight: v }),
  my: (v: string) => ({ marginTop: v, marginBottom: v }),
  m: (v: string) => ({ marginTop: v, marginBottom: v, marginRight: v, marginLeft: v }),
  pt: (v: string) => ({ paddingTop: v }),
  pr: (v: string) => ({ paddingRight: v }),
  pb: (v: string) => ({ paddingBottom: v }),
  pl: (v: string) => ({ paddingLeft: v }),
  px: (v: string) => ({ paddingLeft: v, paddingRight: v }),
  py: (v: string) => ({ paddingTop: v, paddingBottom: v }),
  p: (v: string) => ({ paddingTop: v, paddingBottom: v, paddingRight: v, paddingLeft: v }),
});

const textAlign = stylex.create({
  tal: { textAlign: "left" },
  tac: { textAlign: "center" },
  tar: { textAlign: "right" },
  taj: { textAlign: "justify" },
  ta: (v: string) => ({ textAlign: v }),
});

const textDecoration = stylex.create({
  tdn: { textDecoration: "none" },
  tdlt: { textDecoration: "line-through" },
  tdu: { textDecoration: "underline" },
  textDecoration: (v: string) => ({ textDecoration: v }),
});

const textTransform = stylex.create({
  ttc: { textTransform: "capitalize" },
  ttl: { textTransform: "lowercase" },
  ttu: { textTransform: "uppercase" },
  ttn: { textTransform: "none" },
  tt: (v: string) => ({ textTransform: v }),
});

const typeScale = stylex.create({
  f24: { fontSize: "24px" },
  f18: { fontSize: "18px" },
  f16: { fontSize: "16px" },
  f14: { fontSize: "14px" },
  f12: { fontSize: "12px" },
  f10: { fontSize: "10px", fontWeight: 500 },
});

const typography = stylex.create({
  measure: { maxWidth: "30em" },
  measureWide: { maxWidth: "34em" },
  measureNarrow: { maxWidth: "20em" },
  indent: { textIndent: "1em", marginTop: 0, marginBottom: 0 },
  smallCaps: { fontVariant: "small-caps" },
  truncate: { whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  fs: (v: string) => ({ fontSize: v }),
  lh: (v: string) => ({ lineHeight: v }),
});

const userSelect = stylex.create({
  usn: { userSelect: "none" },
  ust: { userSelect: "text" },
  usAll: { userSelect: "all" },
  usAuto: { userSelect: "auto" },
  select: (v: string) => ({ userSelect: v }),
});

const verticalAlign = stylex.create({
  vaBaseline: { verticalAlign: "baseline" },
  vam: { verticalAlign: "middle" },
  vat: { verticalAlign: "top" },
  vaBottom: { verticalAlign: "bottom" },
  va: (v: string) => ({ verticalAlign: v }),
});

const visibility = stylex.create({
  vv: { visibility: "visible" },
  vh: { visibility: "hidden" },
  visibility: (v: string) => ({ visibility: v }),
});

const whitespace = stylex.create({
  wsp: { whiteSpace: "pre" },
  wsn: { whiteSpace: "normal" },
  wsnw: { whiteSpace: "nowrap" },
  wsbs: { whiteSpace: "break-spaces" },
  wspw: { whiteSpace: "pre-wrap" },
  wspl: { whiteSpace: "pre-line" },
  whiteSpace: (v: string) => ({ whiteSpace: v }),
});

const width = stylex.create({
  w25: { width: "25%" },
  w50: { width: "50%" },
  w75: { width: "75%" },
  w100: { width: "100%" },
  wfc: { width: "fit-content" },
  wmaxc: { width: "max-content" },
  wminc: { width: "min-content" },
  mw0: { minWidth: 0 },
  mw25: { minWidth: "25%" },
  mw50: { minWidth: "50%" },
  mw75: { minWidth: "75%" },
  mw100: { minWidth: "100%" },
  mwfc: { minWidth: "fit-content" },
  mwminc: { minWidth: "min-content" },
  mwmaxc: { minWidth: "max-content" },
  maxw0: { maxWidth: "0" },
  maxw25: { maxWidth: "25%" },
  maxw50: { maxWidth: "50%" },
  maxw75: { maxWidth: "75%" },
  maxw100: { maxWidth: "100%" },
  maxwfc: { maxWidth: "fit-content" },
  maxwminc: { maxWidth: "min-content" },
  maxwmaxc: { maxWidth: "max-content" },
  w0: { width: "0px" },
  w1: { width: "8px" },
  w2: { width: "16px" },
  w3: { width: "24px" },
  w4: { width: "32px" },
  wa: { width: "auto" },
  mw: (v: string) => ({ minWidth: v }),
  maxw: (v: string) => ({ maxWidth: v }),
  w: (v: string) => ({ width: v }),
});

const wordBreak = stylex.create({
  wbn: { wordBreak: "normal" },
  wbba: { wordBreak: "break-all" },
  wbka: { wordBreak: "keep-all" },
  wbbw: { wordBreak: "break-word" },
  wordBreak: (v: string) => ({ wordBreak: v }),
});

const zIndex = stylex.create({
  z0: { zIndex: 0 },
  z1: { zIndex: 1 },
  z2: { zIndex: 2 },
  z3: { zIndex: 3 },
  z4: { zIndex: 4 },
  z5: { zIndex: 5 },
  z999: { zIndex: 999 },
  z9999: { zIndex: 9999 },
  zInherit: { zIndex: "inherit" },
  zInitial: { zIndex: "initial" },
  zUnset: { zIndex: "unset" },
  z: (v: string) => ({ zIndex: v }),
});

/** Converts `inc` into pixels value with a `px` suffix. */
function maybeInc(inc: number | string): string {
  return typeof inc === "string" ? inc : `${inc * 8}px`;
}

type StyleRef = ReturnType<typeof stylex.create>[string];

/** The type accepted by the `css` JSX prop. An array of StyleX style refs. */
export type CssProp = StyleRef[];

class CssBuilder {
  constructor(private styleRefs: StyleRef[], private enabled: boolean) {}

  private addStyle(ref: StyleRef): CssBuilder {
    if (!this.enabled) return this;
    return new CssBuilder([...this.styleRefs, ref], this.enabled);
  }

  // border
  get ba() { return this.addStyle(border.ba); }
  get bt() { return this.addStyle(border.bt); }
  get br() { return this.addStyle(border.br); }
  get bb() { return this.addStyle(border.bb); }
  get bl() { return this.addStyle(border.bl); }
  get bn() { return this.addStyle(border.bn); }

  // borderColor
  get bcBlack() { return this.addStyle(borderColor.bcBlack); }
  get bcMidGray() { return this.addStyle(borderColor.bcMidGray); }
  get bcLightGray() { return this.addStyle(borderColor.bcLightGray); }
  get bcWhite() { return this.addStyle(borderColor.bcWhite); }
  get bcBlue() { return this.addStyle(borderColor.bcBlue); }
  get bcPrimary() { return this.addStyle(borderColor.bcPrimary); }
  bc(value: Properties["borderColor"]) { return this.addStyle(borderColor.bc(String(value))); }

  // borderRadius
  get br0() { return this.addStyle(borderRadius.br0); }
  get br1() { return this.addStyle(borderRadius.br1); }
  get br2() { return this.addStyle(borderRadius.br2); }
  get br3() { return this.addStyle(borderRadius.br3); }
  get br4() { return this.addStyle(borderRadius.br4); }
  get br100() { return this.addStyle(borderRadius.br100); }
  get brPill() { return this.addStyle(borderRadius.brPill); }
  borderRadius(value: Properties["borderRadius"]) { return this.addStyle(borderRadius.borderRadius(String(value))); }

  // borderStyle
  get bsDashed() { return this.addStyle(borderStyle.bsDashed); }
  get bsDotted() { return this.addStyle(borderStyle.bsDotted); }
  get bsn() { return this.addStyle(borderStyle.bsn); }
  get bss() { return this.addStyle(borderStyle.bss); }
  bs(value: Properties["borderStyle"]) { return this.addStyle(borderStyle.bs(String(value))); }

  // borderWidth
  get bw1() { return this.addStyle(borderWidth.bw1); }
  get bw2() { return this.addStyle(borderWidth.bw2); }
  bw(value: Properties["borderWidth"]) { return this.addStyle(borderWidth.bw(String(value))); }

  // boxShadow
  get shadowNone() { return this.addStyle(boxShadow.shadowNone); }

  // container
  get cts() { return this.addStyle(container.cts); }
  get ctis() { return this.addStyle(container.ctis); }
  get ctn() { return this.addStyle(container.ctn); }
  ct(value: Properties["containerType"]) { return this.addStyle(container.ct(String(value))); }
  cn(value: Properties["containerName"]) { return this.addStyle(container.cn(String(value))); }

  // coordinates
  get top0() { return this.addStyle(coordinates.top0); }
  get top1() { return this.addStyle(coordinates.top1); }
  get top2() { return this.addStyle(coordinates.top2); }
  get top3() { return this.addStyle(coordinates.top3); }
  get top4() { return this.addStyle(coordinates.top4); }
  top(v: number | string) { return this.addStyle(coordinates.top(maybeInc(v))); }
  topPx(px: number) { return this.top(`${px}px`); }
  get right0() { return this.addStyle(coordinates.right0); }
  get right1() { return this.addStyle(coordinates.right1); }
  get right2() { return this.addStyle(coordinates.right2); }
  get right3() { return this.addStyle(coordinates.right3); }
  get right4() { return this.addStyle(coordinates.right4); }
  right(v: number | string) { return this.addStyle(coordinates.right(maybeInc(v))); }
  rightPx(px: number) { return this.right(`${px}px`); }
  get bottom0() { return this.addStyle(coordinates.bottom0); }
  get bottom1() { return this.addStyle(coordinates.bottom1); }
  get bottom2() { return this.addStyle(coordinates.bottom2); }
  get bottom3() { return this.addStyle(coordinates.bottom3); }
  get bottom4() { return this.addStyle(coordinates.bottom4); }
  bottom(v: number | string) { return this.addStyle(coordinates.bottom(maybeInc(v))); }
  bottomPx(px: number) { return this.bottom(`${px}px`); }
  get left0() { return this.addStyle(coordinates.left0); }
  get left1() { return this.addStyle(coordinates.left1); }
  get left2() { return this.addStyle(coordinates.left2); }
  get left3() { return this.addStyle(coordinates.left3); }
  get left4() { return this.addStyle(coordinates.left4); }
  left(v: number | string) { return this.addStyle(coordinates.left(maybeInc(v))); }
  leftPx(px: number) { return this.left(`${px}px`); }

  // cursor
  get cursorPointer() { return this.addStyle(cursor.cursorPointer); }
  get cursorNotAllowed() { return this.addStyle(cursor.cursorNotAllowed); }
  cursor(value: Properties["cursor"]) { return this.addStyle(cursor.cursor(String(value))); }

  // display
  get dn() { return this.addStyle(display.dn); }
  get db() { return this.addStyle(display.db); }
  get dib() { return this.addStyle(display.dib); }
  get dit() { return this.addStyle(display.dit); }
  get dt() { return this.addStyle(display.dt); }
  get dtc() { return this.addStyle(display.dtc); }
  get dtRow() { return this.addStyle(display.dtRow); }
  get dtColumn() { return this.addStyle(display.dtColumn); }
  get dtColumnGroup() { return this.addStyle(display.dtColumnGroup); }
  get dg() { return this.addStyle(display.dg); }
  get dig() { return this.addStyle(display.dig); }
  get df() { return this.addStyle(display.df); }
  get dif() { return this.addStyle(display.dif); }
  display(value: Properties["display"]) { return this.addStyle(display.display(String(value))); }

  // flexbox
  get fi() { return this.addStyle(flexbox.fi); }
  get fa() { return this.addStyle(flexbox.fa); }
  get fn() { return this.addStyle(flexbox.fn); }
  get f1() { return this.addStyle(flexbox.f1); }
  get f2() { return this.addStyle(flexbox.f2); }
  get f3() { return this.addStyle(flexbox.f3); }
  get f4() { return this.addStyle(flexbox.f4); }
  get f5() { return this.addStyle(flexbox.f5); }
  f(value: Properties["flex"]) { return this.addStyle(flexbox.f(String(value))); }
  get jcfs() { return this.addStyle(flexbox.jcfs); }
  get jcfe() { return this.addStyle(flexbox.jcfe); }
  get jcc() { return this.addStyle(flexbox.jcc); }
  get jcsb() { return this.addStyle(flexbox.jcsb); }
  get jcsa() { return this.addStyle(flexbox.jcsa); }
  get jcse() { return this.addStyle(flexbox.jcse); }
  jc(value: Properties["justifyContent"]) { return this.addStyle(flexbox.jc(String(value))); }
  get jsa() { return this.addStyle(flexbox.jsa); }
  get jsc() { return this.addStyle(flexbox.jsc); }
  get jss() { return this.addStyle(flexbox.jss); }
  get jse() { return this.addStyle(flexbox.jse); }
  js(value: Properties["justifySelf"]) { return this.addStyle(flexbox.js(String(value))); }
  get jifs() { return this.addStyle(flexbox.jifs); }
  get jife() { return this.addStyle(flexbox.jife); }
  get jic() { return this.addStyle(flexbox.jic); }
  get jisb() { return this.addStyle(flexbox.jisb); }
  get jisa() { return this.addStyle(flexbox.jisa); }
  get jise() { return this.addStyle(flexbox.jise); }
  ji(value: Properties["justifyItems"]) { return this.addStyle(flexbox.ji(String(value))); }
  get asfs() { return this.addStyle(flexbox.asfs); }
  get asfe() { return this.addStyle(flexbox.asfe); }
  get asc() { return this.addStyle(flexbox.asc); }
  get asb() { return this.addStyle(flexbox.asb); }
  get asStretch() { return this.addStyle(flexbox.asStretch); }
  as(value: Properties["alignSelf"]) { return this.addStyle(flexbox.as(String(value))); }
  get aifs() { return this.addStyle(flexbox.aifs); }
  get aife() { return this.addStyle(flexbox.aife); }
  get ais() { return this.addStyle(flexbox.ais); }
  get aie() { return this.addStyle(flexbox.aie); }
  get aic() { return this.addStyle(flexbox.aic); }
  get aib() { return this.addStyle(flexbox.aib); }
  get aiStretch() { return this.addStyle(flexbox.aiStretch); }
  ai(value: Properties["alignItems"]) { return this.addStyle(flexbox.ai(String(value))); }
  get psa() { return this.addStyle(flexbox.psa); }
  get psc() { return this.addStyle(flexbox.psc); }
  get pss() { return this.addStyle(flexbox.pss); }
  get pse() { return this.addStyle(flexbox.pse); }
  get psfs() { return this.addStyle(flexbox.psfs); }
  get psfe() { return this.addStyle(flexbox.psfe); }
  get psStretch() { return this.addStyle(flexbox.psStretch); }
  ps(value: Properties["placeSelf"]) { return this.addStyle(flexbox.ps(String(value))); }
  get pcc() { return this.addStyle(flexbox.pcc); }
  get pcs() { return this.addStyle(flexbox.pcs); }
  get pce() { return this.addStyle(flexbox.pce); }
  get pcsb() { return this.addStyle(flexbox.pcsb); }
  get pcsa() { return this.addStyle(flexbox.pcsa); }
  get pcse() { return this.addStyle(flexbox.pcse); }
  get pcb() { return this.addStyle(flexbox.pcb); }
  get pcStretch() { return this.addStyle(flexbox.pcStretch); }
  pc(value: Properties["placeContent"]) { return this.addStyle(flexbox.pc(String(value))); }
  get pic() { return this.addStyle(flexbox.pic); }
  get pis() { return this.addStyle(flexbox.pis); }
  get pie() { return this.addStyle(flexbox.pie); }
  get pisb() { return this.addStyle(flexbox.pisb); }
  get pisa() { return this.addStyle(flexbox.pisa); }
  get pise() { return this.addStyle(flexbox.pise); }
  get pib() { return this.addStyle(flexbox.pib); }
  get piStretch() { return this.addStyle(flexbox.piStretch); }
  pi(value: Properties["placeItems"]) { return this.addStyle(flexbox.pi(String(value))); }
  get fb1() { return this.addStyle(flexbox.fb1); }
  get fb2() { return this.addStyle(flexbox.fb2); }
  get fb3() { return this.addStyle(flexbox.fb3); }
  get fb4() { return this.addStyle(flexbox.fb4); }
  get fb5() { return this.addStyle(flexbox.fb5); }
  get fb6() { return this.addStyle(flexbox.fb6); }
  get fb7() { return this.addStyle(flexbox.fb7); }
  get fb0() { return this.addStyle(flexbox.fb0); }
  fb(value: Properties["flexBasis"]) { return this.addStyle(flexbox.fb(String(value))); }
  get fg0() { return this.addStyle(flexbox.fg0); }
  get fg1() { return this.addStyle(flexbox.fg1); }
  flexGrow(value: Properties["flexGrow"]) { return this.addStyle(flexbox.flexGrow(String(value))); }
  get fs0() { return this.addStyle(flexbox.fs0); }
  get fs1() { return this.addStyle(flexbox.fs1); }
  flexShrink(value: Properties["flexShrink"]) { return this.addStyle(flexbox.flexShrink(String(value))); }
  get fdr() { return this.addStyle(flexbox.fdr); }
  get fdrr() { return this.addStyle(flexbox.fdrr); }
  get fdc() { return this.addStyle(flexbox.fdc); }
  get fdcr() { return this.addStyle(flexbox.fdcr); }
  fd(value: Properties["flexDirection"]) { return this.addStyle(flexbox.fd(String(value))); }
  get fww() { return this.addStyle(flexbox.fww); }
  get fwr() { return this.addStyle(flexbox.fwr); }
  get fwnw() { return this.addStyle(flexbox.fwnw); }
  flexWrap(value: Properties["flexWrap"]) { return this.addStyle(flexbox.flexWrap(String(value))); }
  order(value: Properties["order"]) { return this.addStyle(flexbox.order(String(value))); }

  // float
  get fl() { return this.addStyle(float.fl); }
  get fr() { return this.addStyle(float.fr); }
  float(value: Properties["float"]) { return this.addStyle(float.float(String(value))); }

  // fontWeight
  get fwn() { return this.addStyle(fontWeight.fwn); }
  get fwb() { return this.addStyle(fontWeight.fwb); }
  get fw1() { return this.addStyle(fontWeight.fw1); }
  get fw2() { return this.addStyle(fontWeight.fw2); }
  get fw3() { return this.addStyle(fontWeight.fw3); }
  get fw4() { return this.addStyle(fontWeight.fw4); }
  get fw5() { return this.addStyle(fontWeight.fw5); }
  get fw6() { return this.addStyle(fontWeight.fw6); }
  get fw7() { return this.addStyle(fontWeight.fw7); }
  get fw8() { return this.addStyle(fontWeight.fw8); }
  get fw9() { return this.addStyle(fontWeight.fw9); }
  fw(value: Properties["fontWeight"]) { return this.addStyle(fontWeight.fw(String(value))); }

  // grid
  gtc(value: Properties["gridTemplateColumns"]) { return this.addStyle(grid.gtc(String(value))); }
  gtr(value: Properties["gridTemplateRows"]) { return this.addStyle(grid.gtr(String(value))); }
  gr(value: Properties["gridRow"]) { return this.addStyle(grid.gr(String(value))); }
  gc(value: Properties["gridColumn"]) { return this.addStyle(grid.gc(String(value))); }
  gar(value: Properties["gridAutoRows"]) { return this.addStyle(grid.gar(String(value))); }
  gac(value: Properties["gridAutoColumns"]) { return this.addStyle(grid.gac(String(value))); }
  get gap0() { return this.addStyle(grid.gap0); }
  get gap1() { return this.addStyle(grid.gap1); }
  get gap2() { return this.addStyle(grid.gap2); }
  get gap3() { return this.addStyle(grid.gap3); }
  get gap4() { return this.addStyle(grid.gap4); }
  gap(v: number | string) { return this.addStyle(grid.gap(maybeInc(v))); }
  gapPx(px: number) { return this.gap(`${px}px`); }
  get rg0() { return this.addStyle(grid.rg0); }
  get rg1() { return this.addStyle(grid.rg1); }
  get rg2() { return this.addStyle(grid.rg2); }
  get rg3() { return this.addStyle(grid.rg3); }
  get rg4() { return this.addStyle(grid.rg4); }
  rg(v: number | string) { return this.addStyle(grid.rg(maybeInc(v))); }
  rgPx(px: number) { return this.rg(`${px}px`); }
  get cg0() { return this.addStyle(grid.cg0); }
  get cg1() { return this.addStyle(grid.cg1); }
  get cg2() { return this.addStyle(grid.cg2); }
  get cg3() { return this.addStyle(grid.cg3); }
  get cg4() { return this.addStyle(grid.cg4); }
  cg(v: number | string) { return this.addStyle(grid.cg(maybeInc(v))); }
  cgPx(px: number) { return this.cg(`${px}px`); }

  // height
  get h0() { return this.addStyle(height.h0); }
  get h1() { return this.addStyle(height.h1); }
  get h2() { return this.addStyle(height.h2); }
  get h3() { return this.addStyle(height.h3); }
  get h4() { return this.addStyle(height.h4); }
  get ha() { return this.addStyle(height.ha); }
  h(v: number | string) { return this.addStyle(height.h(maybeInc(v))); }
  hPx(px: number) { return this.h(`${px}px`); }
  get h25() { return this.addStyle(height.h25); }
  get h50() { return this.addStyle(height.h50); }
  get h75() { return this.addStyle(height.h75); }
  get h100() { return this.addStyle(height.h100); }
  get vh25() { return this.addStyle(height.vh25); }
  get vh50() { return this.addStyle(height.vh50); }
  get vh75() { return this.addStyle(height.vh75); }
  get vh100() { return this.addStyle(height.vh100); }
  get hfc() { return this.addStyle(height.hfc); }
  get hmaxc() { return this.addStyle(height.hmaxc); }
  get hminc() { return this.addStyle(height.hminc); }
  get mh0() { return this.addStyle(height.mh0); }
  get mh25() { return this.addStyle(height.mh25); }
  get mh50() { return this.addStyle(height.mh50); }
  get mh75() { return this.addStyle(height.mh75); }
  get mh100() { return this.addStyle(height.mh100); }
  get mvh100() { return this.addStyle(height.mvh100); }
  mh(value: Properties["minHeight"]) { return this.addStyle(height.mh(String(value))); }
  mhPx(px: number) { return this.mh(`${px}px`); }
  get maxh0() { return this.addStyle(height.maxh0); }
  get maxh25() { return this.addStyle(height.maxh25); }
  get maxh50() { return this.addStyle(height.maxh50); }
  get maxh75() { return this.addStyle(height.maxh75); }
  get maxh100() { return this.addStyle(height.maxh100); }
  maxh(value: Properties["maxHeight"]) { return this.addStyle(height.maxh(String(value))); }
  maxhPx(px: number) { return this.maxh(`${px}px`); }

  // lineClamp
  get lineClamp1() { return this.addStyle(lineClamp.lineClamp1); }
  get lineClamp2() { return this.addStyle(lineClamp.lineClamp2); }
  get lineClamp3() { return this.addStyle(lineClamp.lineClamp3); }
  get lineClamp4() { return this.addStyle(lineClamp.lineClamp4); }
  get lineClamp5() { return this.addStyle(lineClamp.lineClamp5); }
  get lineClamp6() { return this.addStyle(lineClamp.lineClamp6); }
  get lineClampNone() { return this.addStyle(lineClamp.lineClampNone); }
  lineClamp(value: Properties["WebkitLineClamp"]) { return this.addStyle(lineClamp.lineClamp(String(value))); }

  // objectFit
  get objectContain() { return this.addStyle(objectFit.objectContain); }
  get objectCover() { return this.addStyle(objectFit.objectCover); }
  get objectFill() { return this.addStyle(objectFit.objectFill); }
  get objectNone() { return this.addStyle(objectFit.objectNone); }
  get objectScaleDown() { return this.addStyle(objectFit.objectScaleDown); }
  objectFit(value: Properties["objectFit"]) { return this.addStyle(objectFit.objectFit(String(value))); }

  // opacity
  get o0() { return this.addStyle(opacity.o0); }
  get o25() { return this.addStyle(opacity.o25); }
  get o50() { return this.addStyle(opacity.o50); }
  get o75() { return this.addStyle(opacity.o75); }
  get o100() { return this.addStyle(opacity.o100); }
  o(value: Properties["opacity"]) { return this.addStyle(opacity.o(String(value))); }

  // outline
  get outline1() { return this.addStyle(outline.outline1); }
  get outlineTransparent() { return this.addStyle(outline.outlineTransparent); }
  get outline0() { return this.addStyle(outline.outline0); }
  outline(value: Properties["outline"]) { return this.addStyle(outline.outline(String(value))); }

  // overflow
  get ov() { return this.addStyle(overflow.ov); }
  get oh() { return this.addStyle(overflow.oh); }
  get os() { return this.addStyle(overflow.os); }
  get oa() { return this.addStyle(overflow.oa); }
  overflow(value: Properties["overflow"]) { return this.addStyle(overflow.overflow(String(value))); }
  get oyv() { return this.addStyle(overflow.oyv); }
  get oyh() { return this.addStyle(overflow.oyh); }
  get oys() { return this.addStyle(overflow.oys); }
  get oya() { return this.addStyle(overflow.oya); }
  overflowY(value: Properties["overflowY"]) { return this.addStyle(overflow.overflowY(String(value))); }
  get oxv() { return this.addStyle(overflow.oxv); }
  get oxh() { return this.addStyle(overflow.oxh); }
  get oxs() { return this.addStyle(overflow.oxs); }
  get oxa() { return this.addStyle(overflow.oxa); }
  overflowX(value: Properties["overflowX"]) { return this.addStyle(overflow.overflowX(String(value))); }

  // position
  get absolute() { return this.addStyle(position.absolute); }
  get fixed() { return this.addStyle(position.fixed); }
  get static() { return this.addStyle(position.static); }
  get relative() { return this.addStyle(position.relative); }
  get sticky() { return this.addStyle(position.sticky); }
  position(value: Properties["position"]) { return this.addStyle(position.position(String(value))); }

  // skins
  get black() { return this.addStyle(skins.black); }
  get midGray() { return this.addStyle(skins.midGray); }
  get lightGray() { return this.addStyle(skins.lightGray); }
  get white() { return this.addStyle(skins.white); }
  get blue() { return this.addStyle(skins.blue); }
  get primary() { return this.addStyle(skins.primary); }
  color(value: Properties["color"]) { return this.addStyle(skins.color(String(value))); }
  get bgBlack() { return this.addStyle(skins.bgBlack); }
  get bgMidGray() { return this.addStyle(skins.bgMidGray); }
  get bgLightGray() { return this.addStyle(skins.bgLightGray); }
  get bgWhite() { return this.addStyle(skins.bgWhite); }
  get bgBlue() { return this.addStyle(skins.bgBlue); }
  get bgPrimary() { return this.addStyle(skins.bgPrimary); }
  bgColor(value: Properties["backgroundColor"]) { return this.addStyle(skins.bgColor(String(value))); }
  get fBlack() { return this.addStyle(skins.fBlack); }
  get fMidGray() { return this.addStyle(skins.fMidGray); }
  get fLightGray() { return this.addStyle(skins.fLightGray); }
  get fWhite() { return this.addStyle(skins.fWhite); }
  get fBlue() { return this.addStyle(skins.fBlue); }
  get fPrimary() { return this.addStyle(skins.fPrimary); }
  fill(value: Properties["fill"]) { return this.addStyle(skins.fill(String(value))); }

  // spacing
  get mt0() { return this.addStyle(spacing.mt0); }
  get mt1() { return this.addStyle(spacing.mt1); }
  get mt2() { return this.addStyle(spacing.mt2); }
  get mt3() { return this.addStyle(spacing.mt3); }
  get mt4() { return this.addStyle(spacing.mt4); }
  get mta() { return this.addStyle(spacing.mta); }
  mt(v: number | string) { return this.addStyle(spacing.mt(maybeInc(v))); }
  mtPx(px: number) { return this.mt(`${px}px`); }
  get mr0() { return this.addStyle(spacing.mr0); }
  get mr1() { return this.addStyle(spacing.mr1); }
  get mr2() { return this.addStyle(spacing.mr2); }
  get mr3() { return this.addStyle(spacing.mr3); }
  get mr4() { return this.addStyle(spacing.mr4); }
  get mra() { return this.addStyle(spacing.mra); }
  mr(v: number | string) { return this.addStyle(spacing.mr(maybeInc(v))); }
  mrPx(px: number) { return this.mr(`${px}px`); }
  get mb0() { return this.addStyle(spacing.mb0); }
  get mb1() { return this.addStyle(spacing.mb1); }
  get mb2() { return this.addStyle(spacing.mb2); }
  get mb3() { return this.addStyle(spacing.mb3); }
  get mb4() { return this.addStyle(spacing.mb4); }
  get mba() { return this.addStyle(spacing.mba); }
  mb(v: number | string) { return this.addStyle(spacing.mb(maybeInc(v))); }
  mbPx(px: number) { return this.mb(`${px}px`); }
  get ml0() { return this.addStyle(spacing.ml0); }
  get ml1() { return this.addStyle(spacing.ml1); }
  get ml2() { return this.addStyle(spacing.ml2); }
  get ml3() { return this.addStyle(spacing.ml3); }
  get ml4() { return this.addStyle(spacing.ml4); }
  get mla() { return this.addStyle(spacing.mla); }
  ml(v: number | string) { return this.addStyle(spacing.ml(maybeInc(v))); }
  mlPx(px: number) { return this.ml(`${px}px`); }
  get mx0() { return this.addStyle(spacing.mx0); }
  get mx1() { return this.addStyle(spacing.mx1); }
  get mx2() { return this.addStyle(spacing.mx2); }
  get mx3() { return this.addStyle(spacing.mx3); }
  get mx4() { return this.addStyle(spacing.mx4); }
  get mxa() { return this.addStyle(spacing.mxa); }
  mx(v: number | string) { return this.addStyle(spacing.mx(maybeInc(v))); }
  mxPx(px: number) { return this.mx(`${px}px`); }
  get my0() { return this.addStyle(spacing.my0); }
  get my1() { return this.addStyle(spacing.my1); }
  get my2() { return this.addStyle(spacing.my2); }
  get my3() { return this.addStyle(spacing.my3); }
  get my4() { return this.addStyle(spacing.my4); }
  get mya() { return this.addStyle(spacing.mya); }
  my(v: number | string) { return this.addStyle(spacing.my(maybeInc(v))); }
  myPx(px: number) { return this.my(`${px}px`); }
  get m0() { return this.addStyle(spacing.m0); }
  get m1() { return this.addStyle(spacing.m1); }
  get m2() { return this.addStyle(spacing.m2); }
  get m3() { return this.addStyle(spacing.m3); }
  get m4() { return this.addStyle(spacing.m4); }
  get ma() { return this.addStyle(spacing.ma); }
  m(v: number | string) { return this.addStyle(spacing.m(maybeInc(v))); }
  mPx(px: number) { return this.m(`${px}px`); }
  get pt0() { return this.addStyle(spacing.pt0); }
  get pt1() { return this.addStyle(spacing.pt1); }
  get pt2() { return this.addStyle(spacing.pt2); }
  get pt3() { return this.addStyle(spacing.pt3); }
  get pt4() { return this.addStyle(spacing.pt4); }
  pt(v: number | string) { return this.addStyle(spacing.pt(maybeInc(v))); }
  ptPx(px: number) { return this.pt(`${px}px`); }
  get pr0() { return this.addStyle(spacing.pr0); }
  get pr1() { return this.addStyle(spacing.pr1); }
  get pr2() { return this.addStyle(spacing.pr2); }
  get pr3() { return this.addStyle(spacing.pr3); }
  get pr4() { return this.addStyle(spacing.pr4); }
  pr(v: number | string) { return this.addStyle(spacing.pr(maybeInc(v))); }
  prPx(px: number) { return this.pr(`${px}px`); }
  get pb0() { return this.addStyle(spacing.pb0); }
  get pb1() { return this.addStyle(spacing.pb1); }
  get pb2() { return this.addStyle(spacing.pb2); }
  get pb3() { return this.addStyle(spacing.pb3); }
  get pb4() { return this.addStyle(spacing.pb4); }
  pb(v: number | string) { return this.addStyle(spacing.pb(maybeInc(v))); }
  pbPx(px: number) { return this.pb(`${px}px`); }
  get pl0() { return this.addStyle(spacing.pl0); }
  get pl1() { return this.addStyle(spacing.pl1); }
  get pl2() { return this.addStyle(spacing.pl2); }
  get pl3() { return this.addStyle(spacing.pl3); }
  get pl4() { return this.addStyle(spacing.pl4); }
  pl(v: number | string) { return this.addStyle(spacing.pl(maybeInc(v))); }
  plPx(px: number) { return this.pl(`${px}px`); }
  get px0() { return this.addStyle(spacing.px0); }
  get px1() { return this.addStyle(spacing.px1); }
  get px2() { return this.addStyle(spacing.px2); }
  get px3() { return this.addStyle(spacing.px3); }
  get px4() { return this.addStyle(spacing.px4); }
  px(v: number | string) { return this.addStyle(spacing.px(maybeInc(v))); }
  pxPx(px: number) { return this.px(`${px}px`); }
  get py0() { return this.addStyle(spacing.py0); }
  get py1() { return this.addStyle(spacing.py1); }
  get py2() { return this.addStyle(spacing.py2); }
  get py3() { return this.addStyle(spacing.py3); }
  get py4() { return this.addStyle(spacing.py4); }
  py(v: number | string) { return this.addStyle(spacing.py(maybeInc(v))); }
  pyPx(px: number) { return this.py(`${px}px`); }
  get p0() { return this.addStyle(spacing.p0); }
  get p1() { return this.addStyle(spacing.p1); }
  get p2() { return this.addStyle(spacing.p2); }
  get p3() { return this.addStyle(spacing.p3); }
  get p4() { return this.addStyle(spacing.p4); }
  p(v: number | string) { return this.addStyle(spacing.p(maybeInc(v))); }
  pPx(px: number) { return this.p(`${px}px`); }

  // textAlign
  get tal() { return this.addStyle(textAlign.tal); }
  get tac() { return this.addStyle(textAlign.tac); }
  get tar() { return this.addStyle(textAlign.tar); }
  get taj() { return this.addStyle(textAlign.taj); }
  ta(value: Properties["textAlign"]) { return this.addStyle(textAlign.ta(String(value))); }

  // textDecoration
  get tdn() { return this.addStyle(textDecoration.tdn); }
  get tdlt() { return this.addStyle(textDecoration.tdlt); }
  get tdu() { return this.addStyle(textDecoration.tdu); }
  textDecoration(value: Properties["textDecoration"]) { return this.addStyle(textDecoration.textDecoration(String(value))); }

  // textTransform
  get ttc() { return this.addStyle(textTransform.ttc); }
  get ttl() { return this.addStyle(textTransform.ttl); }
  get ttu() { return this.addStyle(textTransform.ttu); }
  get ttn() { return this.addStyle(textTransform.ttn); }
  tt(value: Properties["textTransform"]) { return this.addStyle(textTransform.tt(String(value))); }

  // typeScale
  get f24() { return this.addStyle(typeScale.f24); }
  get f18() { return this.addStyle(typeScale.f18); }
  get f16() { return this.addStyle(typeScale.f16); }
  get f14() { return this.addStyle(typeScale.f14); }
  get f12() { return this.addStyle(typeScale.f12); }
  get f10() { return this.addStyle(typeScale.f10); }

  // typography
  get measure() { return this.addStyle(typography.measure); }
  get measureWide() { return this.addStyle(typography.measureWide); }
  get measureNarrow() { return this.addStyle(typography.measureNarrow); }
  get indent() { return this.addStyle(typography.indent); }
  get smallCaps() { return this.addStyle(typography.smallCaps); }
  get truncate() { return this.addStyle(typography.truncate); }
  fs(value: Properties["fontSize"]) { return this.addStyle(typography.fs(String(value))); }
  fsPx(px: number) { return this.fs(`${px}px`); }
  lh(value: Properties["lineHeight"]) { return this.addStyle(typography.lh(String(value))); }
  lhPx(px: number) { return this.lh(`${px}px`); }

  // userSelect
  get usn() { return this.addStyle(userSelect.usn); }
  get ust() { return this.addStyle(userSelect.ust); }
  get usAll() { return this.addStyle(userSelect.usAll); }
  get usAuto() { return this.addStyle(userSelect.usAuto); }
  select(value: Properties["userSelect"]) { return this.addStyle(userSelect.select(String(value))); }

  // verticalAlign
  get vaBaseline() { return this.addStyle(verticalAlign.vaBaseline); }
  get vam() { return this.addStyle(verticalAlign.vam); }
  get vat() { return this.addStyle(verticalAlign.vat); }
  get vaBottom() { return this.addStyle(verticalAlign.vaBottom); }
  va(value: Properties["verticalAlign"]) { return this.addStyle(verticalAlign.va(String(value))); }

  // visibility
  get vv() { return this.addStyle(visibility.vv); }
  get vh() { return this.addStyle(visibility.vh); }
  visibility(value: Properties["visibility"]) { return this.addStyle(visibility.visibility(String(value))); }

  // whitespace
  get wsp() { return this.addStyle(whitespace.wsp); }
  get wsn() { return this.addStyle(whitespace.wsn); }
  get wsnw() { return this.addStyle(whitespace.wsnw); }
  get wsbs() { return this.addStyle(whitespace.wsbs); }
  get wspw() { return this.addStyle(whitespace.wspw); }
  get wspl() { return this.addStyle(whitespace.wspl); }
  whiteSpace(value: Properties["whiteSpace"]) { return this.addStyle(whitespace.whiteSpace(String(value))); }

  // width
  get w25() { return this.addStyle(width.w25); }
  get w50() { return this.addStyle(width.w50); }
  get w75() { return this.addStyle(width.w75); }
  get w100() { return this.addStyle(width.w100); }
  get wfc() { return this.addStyle(width.wfc); }
  get wmaxc() { return this.addStyle(width.wmaxc); }
  get wminc() { return this.addStyle(width.wminc); }
  get mw0() { return this.addStyle(width.mw0); }
  get mw25() { return this.addStyle(width.mw25); }
  get mw50() { return this.addStyle(width.mw50); }
  get mw75() { return this.addStyle(width.mw75); }
  get mw100() { return this.addStyle(width.mw100); }
  get mwfc() { return this.addStyle(width.mwfc); }
  get mwminc() { return this.addStyle(width.mwminc); }
  get mwmaxc() { return this.addStyle(width.mwmaxc); }
  mw(value: Properties["minWidth"]) { return this.addStyle(width.mw(String(value))); }
  mwPx(px: number) { return this.mw(`${px}px`); }
  get maxw0() { return this.addStyle(width.maxw0); }
  get maxw25() { return this.addStyle(width.maxw25); }
  get maxw50() { return this.addStyle(width.maxw50); }
  get maxw75() { return this.addStyle(width.maxw75); }
  get maxw100() { return this.addStyle(width.maxw100); }
  get maxwfc() { return this.addStyle(width.maxwfc); }
  get maxwminc() { return this.addStyle(width.maxwminc); }
  get maxwmaxc() { return this.addStyle(width.maxwmaxc); }
  maxw(value: Properties["maxWidth"]) { return this.addStyle(width.maxw(String(value))); }
  maxwPx(px: number) { return this.maxw(`${px}px`); }
  get w0() { return this.addStyle(width.w0); }
  get w1() { return this.addStyle(width.w1); }
  get w2() { return this.addStyle(width.w2); }
  get w3() { return this.addStyle(width.w3); }
  get w4() { return this.addStyle(width.w4); }
  get wa() { return this.addStyle(width.wa); }
  w(v: number | string) { return this.addStyle(width.w(maybeInc(v))); }
  wPx(px: number) { return this.w(`${px}px`); }

  // wordBreak
  get wbn() { return this.addStyle(wordBreak.wbn); }
  get wbba() { return this.addStyle(wordBreak.wbba); }
  get wbka() { return this.addStyle(wordBreak.wbka); }
  get wbbw() { return this.addStyle(wordBreak.wbbw); }
  wordBreak(value: Properties["wordBreak"]) { return this.addStyle(wordBreak.wordBreak(String(value))); }

  // zIndex
  get z0() { return this.addStyle(zIndex.z0); }
  get z1() { return this.addStyle(zIndex.z1); }
  get z2() { return this.addStyle(zIndex.z2); }
  get z3() { return this.addStyle(zIndex.z3); }
  get z4() { return this.addStyle(zIndex.z4); }
  get z5() { return this.addStyle(zIndex.z5); }
  get z999() { return this.addStyle(zIndex.z999); }
  get z9999() { return this.addStyle(zIndex.z9999); }
  get zInherit() { return this.addStyle(zIndex.zInherit); }
  get zInitial() { return this.addStyle(zIndex.zInitial); }
  get zUnset() { return this.addStyle(zIndex.zUnset); }
  z(value: Properties["zIndex"]) { return this.addStyle(zIndex.z(String(value))); }

  // aliases
  get bodyText() { return this.f14.black; }

  /** Conditionally apply styles. */
  if(cond: boolean): CssBuilder {
    return new CssBuilder([...this.styleRefs], cond);
  }

  get else(): CssBuilder {
    return new CssBuilder([...this.styleRefs], !this.enabled);
  }

  /** Returns the accumulated style refs. Pass to the `css` JSX prop or spread with other CssProp arrays. */
  get $(): CssProp {
    return [...this.styleRefs];
  }
}

/** An entry point for Css expressions. CssBuilder is immutable so this is safe to share. */
export const Css = new CssBuilder([], true);
